(in-package #:trivial-simd)

(defvar *sbcl-simd-available-p* nil)

#+(and sbcl x86-64)
(when (ignore-errors (require :sb-simd))
  (when (find-package :sb-simd-sse2)
    (load (asdf:system-relative-pathname "trivial-simd" "sbcl-simd.lisp"))
    (setf *sbcl-simd-available-p* t)))

(defun select-backend ()
  (let ((requested (uiop:getenv "TRIVIAL_SIMD_BACKEND")))
    (cond ((or (null requested) (string= requested "")
               (string-equal requested "auto"))
           (cond (*sbcl-simd-available-p* :sbcl)
                 (*native-available-p* :native)
                 (t :lisp)))
          ((string-equal requested "lisp") :lisp)
          ((and (string-equal requested "native") *native-available-p*) :native)
          ((and (string-equal requested "sbcl") *sbcl-simd-available-p*) :sbcl)
          (t (error "Requested SIMD backend ~S is unavailable" requested)))))

(defvar *backend* (select-backend))

(defun backend ()
  "Return :SBCL, :NATIVE, or :LISP for the active backend."
  *backend*)

(defun lisp-binary (operation destination left right)
  (ecase operation
    (:add (dotimes (i (length destination))
            (setf (aref destination i) (+ (aref left i) (aref right i)))))
    (:subtract (dotimes (i (length destination))
                 (setf (aref destination i) (- (aref left i) (aref right i)))))
    (:multiply (dotimes (i (length destination))
                 (setf (aref destination i) (* (aref left i) (aref right i)))))
    (:divide (dotimes (i (length destination))
               (setf (aref destination i) (/ (aref left i) (aref right i))))))
  destination)

(defun lisp-sum (input)
  (let ((result (if (typep input '(simple-array single-float (*))) 0.0f0 0.0d0)))
    (dotimes (i (length input) result)
      (incf result (aref input i)))))

(defun lisp-dot (left right)
  (let ((result (if (typep left '(simple-array single-float (*))) 0.0f0 0.0d0)))
    (dotimes (i (length left) result)
      (incf result (* (aref left i) (aref right i))))))

(defun sbcl-binary (operation destination left right)
  #-(and sbcl x86-64)
  (declare (ignore operation destination left right))
  #+(and sbcl x86-64)
  (funcall (ecase operation
             (:add (if (typep destination '(simple-array single-float (*)))
                       #'%sbcl-add-f32 #'%sbcl-add-f64))
             (:subtract (if (typep destination '(simple-array single-float (*)))
                            #'%sbcl-subtract-f32 #'%sbcl-subtract-f64))
             (:multiply (if (typep destination '(simple-array single-float (*)))
                            #'%sbcl-multiply-f32 #'%sbcl-multiply-f64))
             (:divide (if (typep destination '(simple-array single-float (*)))
                          #'%sbcl-divide-f32 #'%sbcl-divide-f64)))
           destination left right)
  #-(and sbcl x86-64)
  (error "SBCL SIMD is unavailable on this platform"))

(defun sbcl-sum (input)
  #-(and sbcl x86-64)
  (declare (ignore input))
  #+(and sbcl x86-64)
  (if (typep input '(simple-array single-float (*)))
      (%sbcl-sum-f32 input)
      (%sbcl-sum-f64 input))
  #-(and sbcl x86-64)
  (error "SBCL SIMD is unavailable on this platform"))

(defun sbcl-dot (left right)
  #-(and sbcl x86-64)
  (declare (ignore left right))
  #+(and sbcl x86-64)
  (if (typep left '(simple-array single-float (*)))
      (%sbcl-dot-f32 left right)
      (%sbcl-dot-f64 left right))
  #-(and sbcl x86-64)
  (error "SBCL SIMD is unavailable on this platform"))
