(in-package #:trivial-simd)

(eval-when (:compile-toplevel :load-toplevel :execute)
  ;; TODO: structural dedup scans earlier passes; hash-cons large graphs (#137).
  (defun kernel-pass-plan (expression arguments)
    (let ((originals nil) (passes nil))
      (labels ((walk (form)
                 (cond ((or (atom form) (kernel-scalar-p form)) form)
                       ((member (first form) *kernel-reducers*)
                        (unless (= (length form) 2) (error "A reduction needs one expression"))
                        (let ((known (position form originals :test #'equal)))
                          (if known `(kernel-scalar ,known)
                              (let* ((body (walk (second form))) (slot (length passes)))
                                (setf originals (append originals (list form))
                                      passes (append passes (list (list (first form) body))))
                                `(kernel-scalar ,slot)))))
                       ((member (first form) '(count any all))
                        (error "Mask reductions must be top-level"))
                       (t (cons (first form) (mapcar #'walk (rest form)))))))
        (let* ((reducer (and (consp expression)
                             (member (first expression) (list* 'count 'any 'all *kernel-reducers*))
                             (first expression)))
               (body (if reducer
                         (progn (unless (= (length expression) 2)
                                  (error "A reduction needs one expression"))
                                (second expression))
                         expression))
               (body (walk body))
               (kind (mask-kernel-kind body arguments)))
          (when (and reducer (not (eq kind (if (member reducer '(count any all)) :mask :numeric))))
            (error "Kernel reduction has the wrong expression kind"))
          (values passes (if reducer (list reducer body) body) reducer kind)))))

  (defun kernel-pass-function-form (name declarations expression)
    (let ((expansion (if (some #'consp declarations)
                         (declared-kernel-expansion name declarations expression)
                         (macroexpand-1 `(define-single-row-kernel ,name ,declarations ,expression)))))
      (labels ((localize (form)
                 (cond ((atom form) form)
                       ((and (eq (first form) 'defun) (eq (second form) name))
                        `(labels ((,name ,@(cddr form))) #',name))
                       (t (mapcar #'localize form)))))
        (localize expansion))))

  (defun planned-kernel-expansion (name declarations expression)
    (multiple-value-bind (arguments specs)
        (if declarations (normalize-kernel-inputs declarations) (values nil nil))
      (multiple-value-bind (passes final reducer kind) (kernel-pass-plan expression arguments)
        (let* ((functions (loop repeat (1+ (length passes)) collect (gensym "PASS")))
               (destination (unless reducer (gensym "DESTINATION")))
               (options (gensym "OPTIONS"))
               (runners (gensym "RUNNERS"))
               (declared-p (some #'consp declarations))
               (starts (mapcar (lambda (arg) (intern (format nil "~A-START" arg) :keyword)) arguments))
               (strides (mapcar (lambda (arg) (intern (format nil "~A-ROW-STRIDE" arg) :keyword)) arguments)))
          `(let ((,runners
                   (vector ,@(loop for function in functions for form in (append passes (list final))
                                   collect (kernel-pass-function-form function declarations form)))))
             (defun ,name (,@(when destination (list destination)) ,@arguments &rest ,options)
               (run-planned-kernel ,runners ',(append passes (list final)) ',arguments ',specs
                                   ,(not (null declared-p)) ',reducer ',kind
                                   (list ,@arguments) ,destination ,options ',starts ',strides))))))))

(defun planned-slice (inputs specs declared-p destination kind options starts)
  (if declared-p
      (multiple-value-bind (type count)
          (resolve-declared-kernel inputs specs destination kind (getf options :start) (getf options :end)
                                   (mapcar (lambda (key) (getf options key)) starts)
                                   (getf options :destination-start))
        (values type count))
      (if (eq kind :mask)
          (let ((type (vector-type (first inputs))))
            (unless (every (lambda (input) (eq type (vector-type input))) inputs)
              (error "Kernel inputs have different types"))
            (when (and destination (not (eq (vector-type destination) :u8)))
              (error "Mask destination has the wrong type"))
            (values type
                    (resolve-mixed-slice (append (when destination (list destination)) inputs)
                                         (append (when destination (list (getf options :destination-start)))
                                                 (mapcar (lambda (key) (getf options key)) starts))
                                         (getf options :start) (getf options :end))))
          (resolve-slice (append (when destination (list destination)) inputs)
                         (append (when destination (list (getf options :destination-start)))
                                 (mapcar (lambda (key) (getf options key)) starts))
                         (getf options :start) (getf options :end)))))

(defun validate-kernel-passes (forms arguments type)
  (dolist (form forms)
    (let* ((reducer (and (consp form) (member (first form) *kernel-reducers*) (first form)))
           (body (if reducer (second form) form))
           (tree (mask-kernel-tree body arguments)))
      (when (integer-type-p type) (validate-integer-kernel tree type reducer))
      (when (complex-type-p type) (validate-complex-kernel tree reducer)))))

(defun execute-kernel-passes (functions inputs destination options type count)
  (let ((*kernel-scalars* (make-array (1- (length functions)) :initial-element 0)))
    (when (plusp count)
      (dotimes (pass (length *kernel-scalars*))
        (setf (aref *kernel-scalars* pass)
              (kernel-constant-value
               (apply (aref functions pass)
                      (append inputs (loop for (key value) on options by #'cddr
                                           unless (eq key :destination-start) append (list key value))))
               type))))
    (let ((*backend* (if (and (eq *backend* :native) (complex-type-p type)) :lisp *backend*)))
      (apply (aref functions (1- (length functions)))
             (append (when destination (list destination)) inputs options)))))

(defun kernel-row-span (vector start stride rows count)
  (let* ((limit (declared-kernel-limit (vector-type vector)))
         (shift (if (and (plusp rows) (plusp count)) (* (1- rows) stride) 0))
         (low (+ start (min 0 shift)))
         (high (+ start (max 0 shift) (if (plusp rows) count 0))))
    (unless (and (typep start `(integer 0 ,limit)) (typep stride '(signed-byte 64))
                 (<= 0 low high (vector-length vector) limit))
      (error "Invalid kernel row span"))
    (declared-kernel-span vector low (- high low) 1 0)
    (list low high)))

;; TODO: setup scales with rows and passes; batch native pass graphs (#137).
(defun run-planned-rows (functions forms arguments inputs specs destination reducer kind options starts strides)
  (unless (and destination (eq kind :numeric) (member reducer '(nil sum)))
    (error "Row batching supports numeric elementwise and SUM kernels"))
  (when (or (member :start options) (member :end options))
    (error "Batch calls use :ROW-LENGTH instead of :START/:END"))
  (unless (member :row-length options) (error "Batch calls require :ROW-LENGTH"))
  (let* ((type (declared-kernel-precision inputs specs destination kind))
         (limit (declared-kernel-limit type))
         (rows (getf options :rows)) (count (getf options :row-length))
         (output-start (or (getf options :destination-start) 0)))
    (unless (and (typep rows `(integer 0 ,limit)) (typep count `(integer 0 ,limit)))
      (error "Invalid batch dimensions"))
    (when (and reducer (member :destination-row-stride options))
      (error "SUM batches use contiguous scalar output"))
    (let* ((width (if reducer 1 count))
           (output-stride (if reducer 1 (getf options :destination-row-stride count)))
           (input-starts (mapcar (lambda (key) (or (getf options key) 0)) starts))
           (input-strides (loop for key in strides for (nil repeat) in specs
                                collect (or (getf options key) (ceiling count repeat))))
           (spans (loop for input in inputs for start in input-starts
                        for stride in input-strides for (nil repeat) in specs
                        collect (kernel-row-span input start stride rows (ceiling count repeat))))
           (output-span (kernel-row-span destination output-start output-stride rows width)))
      (when (and (> rows 1) (plusp width) (< (abs output-stride) width))
        (error "Kernel output rows overlap"))
      (check-declared-kernel-overlap inputs spans destination (first output-span)
                                     (- (second output-span) (first output-span)))
      (validate-kernel-passes forms arguments type)
      (dotimes (row rows)
        (let* ((row-options (append (list :end count)
                                   (loop for key in starts for start in input-starts for stride in input-strides
                                         append (list key (+ start (* row stride))))))
               (offset (+ output-start (* row output-stride))))
          (if reducer
              (setf (vector-ref destination offset)
                    (execute-kernel-passes functions inputs nil row-options type count))
              (execute-kernel-passes functions inputs destination
                                     (append (list :destination-start offset) row-options) type count))))
      destination)))

(defun run-planned-kernel (functions forms arguments specs declared-p reducer kind inputs destination options starts strides)
  (unless (and (evenp (length options))
               (loop for (key nil) on options by #'cddr
                     always (member key (append '(:start :end :destination-start :rows :row-length
                                                  :destination :destination-row-stride) starts strides))))
    (error "Invalid kernel keywords"))
  (when (and destination (loop for (key nil) on options by #'cddr thereis (eq key :destination)))
    (error "Elementwise kernels use a positional destination"))
  (let ((*backend* (if (and (eq *backend* :native) (not *native-kernel-transcendentals-p*)
                            (some #'kernel-transcendental-p forms)) :lisp *backend*)))
    (if (member :rows options)
        (run-planned-rows functions forms arguments inputs specs
                          (if reducer (getf options :destination) destination)
                          reducer kind options starts strides)
        (progn
          (when (loop for (key nil) on options by #'cddr
                      thereis (member key (append '(:row-length :destination :destination-row-stride) strides)))
            (error "Batch keywords require :ROWS"))
          (if (= (length functions) 1)
              (apply (aref functions 0) (append (when destination (list destination)) inputs options))
              (multiple-value-bind (type count) (planned-slice inputs specs declared-p destination kind options starts)
                (validate-kernel-passes forms arguments type)
                (execute-kernel-passes functions inputs destination options type count)))))))

(defmacro define-kernel (name (&rest arguments) expression)
  "Define a numeric or mask kernel, including dependent numeric reduction passes."
  (let* ((names (mapcar (lambda (arg) (if (consp arg) (first arg) arg)) arguments))
         (outer (and (consp expression) (member (first expression) (list* 'count 'any 'all *kernel-reducers*))
                     (first expression))))
    (multiple-value-bind (passes final reducer kind) (kernel-pass-plan expression names)
      (declare (ignore final reducer))
      (if (or passes (kernel-transcendental-p expression)
              (and (null outer) (eq kind :numeric)))
          (planned-kernel-expansion name arguments expression)
          (macroexpand-1 `(define-basic-kernel ,name ,arguments ,expression))))))
