(in-package #:trivial-simd)

(defconstant +kernel-registers+ 8)

(defparameter *kernel-opcodes*
  '((:copy . 0) (:constant . 1) (:add . 2) (:subtract . 3)
    (:multiply . 4) (:divide . 5) (:negate . 6) (:spill . 7) (:reload . 8)
    (:sqrt . 9) (:abs . 10) (:min . 11) (:max . 12) (:fma . 13)))

(defconstant +kernel-output+ #xFF)
(defconstant +kernel-input-base+ +kernel-registers+)
(defconstant +kernel-max-arguments+ (- +kernel-output+ +kernel-input-base+))

(defparameter *kernel-operators*
  '((+ . :add) (- . :subtract) (* . :multiply) (/ . :divide)
    (sqrt . :sqrt) (abs . :abs) (min . :min) (max . :max) (fma . :fma)))

(defun parse-kernel-expression (expression arguments)
  "Parse an elementwise expression into a typed operator tree."
  (cond ((and (symbolp expression) (position expression arguments))
         (list :argument (position expression arguments)))
        ((realp expression) (list :constant expression))
        ((and (consp expression) (assoc (first expression) *kernel-operators*))
         (let ((kind (cdr (assoc (first expression) *kernel-operators*)))
               (operands (mapcar (lambda (operand)
                                   (parse-kernel-expression operand arguments))
                                 (rest expression))))
           (cond ((null operands)
                  (error "Kernel operator ~S needs an operand" (first expression)))
                 ((member kind '(:sqrt :abs))
                  (unless (= 1 (length operands))
                    (error "Kernel operator ~S needs one operand" (first expression)))
                  (list :unary kind (first operands)))
                 ((eq kind :fma)
                  (unless (= 3 (length operands)) (error "Kernel FMA needs three operands"))
                  (cons :fma operands))
                 ((rest operands)
                  (reduce (lambda (left right) (list :operation kind left right))
                          operands))
                 ((eq kind :subtract) (list :negate (first operands)))
                 ((eq kind :divide)
                  (list :operation :divide (list :constant 1) (first operands)))
                 (t (first operands)))))
        (t (error "Unsupported kernel expression ~S" expression))))

(defun register-need (node)
  (ecase (first node)
    (:argument 0)
    (:constant 1)
    (:negate (max 1 (register-need (second node))))
    (:unary (max 1 (register-need (third node))))
    (:fma (loop for need in (sort (mapcar #'register-need (rest node)) #'>)
                for held from 0 maximize (max 3 (+ held need))))
    (:operation (let ((left (register-need (third node)))
                      (right (register-need (fourth node))))
                  (max 1 (if (= left right) (1+ left) (max left right)))))))

;; TODO: 16-bit scratch indexes cap live slots at 65,536; widen bytecode (#50).
(defun kernel-scratch-index (index)
  (unless (typep index '(unsigned-byte 16))
    (error "Kernel scratch index ~D exceeds the 65,536-slot limit" index))
  index)

(defun lower-kernel (tree)
  "Return instructions, constants, and scratch count. Instructions are (op dst a b).
SPILL/RELOAD use a register and slot; other operands name registers or inputs."
  (let ((free (loop for register below +kernel-registers+ collect register))
        (instructions '())
        (constants '())
        (scratch-free '())
        (scratch-count 0))
    (labels ((allocate ()
               (or (pop free)
                   (error "Internal kernel register allocation exhausted")))
             (register-p (operand) (< operand +kernel-input-base+))
             (release (operand) (when (register-p operand) (push operand free)))
             (emit (op destination a b)
               (push (list op destination a b) instructions))
             (scratch-slot ()
               (or (pop scratch-free)
                   (prog1 (kernel-scratch-index scratch-count)
                     (incf scratch-count))))
             (generate-pair (first second)
               (let* ((operand (generate first nil))
                      (slot (when (and (register-p operand)
                                       (> (register-need second) (length free)))
                              (let ((slot (scratch-slot)))
                                (emit :spill operand slot 0)
                                (release operand)
                                slot)))
                      (other (generate second nil)))
                 (when slot
                   (setf operand (allocate))
                   (emit :reload operand slot 0)
                   (push slot scratch-free))
                 (values operand other)))
             (generate-many (nodes)
               (let ((operands (make-array (length nodes))) (held '()) (spilled '()))
                 (dolist (index (stable-sort (loop for i below (length nodes) collect i)
                                            #'> :key (lambda (i) (register-need (nth i nodes)))))
                   (loop while (and held (> (register-need (nth index nodes)) (length free)))
                         for previous = (pop held)
                         do (let ((slot (scratch-slot)))
                              (emit :spill (aref operands previous) slot 0)
                              (release (aref operands previous))
                              (push (cons previous slot) spilled)))
                   (setf (aref operands index) (generate (nth index nodes) nil))
                   (when (register-p (aref operands index)) (push index held)))
                 (dolist (spill spilled)
                   (let ((register (allocate)))
                     (emit :reload register (cdr spill) 0)
                     (setf (aref operands (car spill)) register)
                     (push (cdr spill) scratch-free)))
                 (coerce operands 'list)))
             (constant-index (value)
               (or (position value constants)
                   (progn (setf constants (append constants (list value)))
                          (1- (length constants)))))
             (destination-for (top-p &rest operands)
               (cond (top-p +kernel-output+)
                     ((find-if #'register-p operands))
                     (t (allocate))))
             (generate (node top-p)
               (ecase (first node)
                 (:argument
                  (let ((operand (+ +kernel-input-base+ (second node))))
                    (if top-p
                        (progn (emit :copy +kernel-output+ operand 0) +kernel-output+)
                        operand)))
                 (:constant
                  (let ((destination (destination-for top-p)))
                    (emit :constant destination (constant-index (second node)) 0)
                    destination))
                 (:negate
                  (let* ((operand (generate (second node) nil))
                         (destination (destination-for top-p operand)))
                    (emit :negate destination operand 0)
                    (unless (eql destination operand) (release operand))
                    destination))
                 (:unary
                  (let* ((operand (generate (third node) nil))
                         (destination (destination-for top-p operand)))
                    (emit (second node) destination operand 0)
                    (unless (eql destination operand) (release operand))
                    destination))
                 (:fma
                  (destructuring-bind (a b c) (generate-many (rest node))
                    (let ((destination (if (register-p c) c (allocate))))
                      (unless (eql destination c) (emit :copy destination c 0))
                      (emit :fma destination a b)
                      (dolist (operand (list a b)) (release operand))
                      (if top-p
                          (progn (emit :copy +kernel-output+ destination 0)
                                 (release destination) +kernel-output+)
                          destination))))
                 (:operation
                  (destructuring-bind (kind left right) (rest node)
                    (let (left-operand right-operand)
                      (if (>= (register-need left) (register-need right))
                          (multiple-value-setq (left-operand right-operand)
                            (generate-pair left right))
                          (multiple-value-setq (right-operand left-operand)
                            (generate-pair right left)))
                      (let ((destination (destination-for top-p left-operand right-operand)))
                        (emit kind destination left-operand right-operand)
                        (dolist (operand (list left-operand right-operand))
                          (unless (eql operand destination) (release operand)))
                        destination)))))))
      (generate tree t))
    (values (nreverse instructions) constants scratch-count)))

(defun kernel-bytes (instructions)
  (loop for (op destination a b) in instructions
        append (if (member op '(:spill :reload))
                   (let ((index (kernel-scratch-index a)))
                     (list (cdr (assoc op *kernel-opcodes*)) destination
                           (ldb (byte 8 0) index) (ldb (byte 8 8) index)))
                   (list (cdr (assoc op *kernel-opcodes*)) destination a b))))

(defun kernel-element-type (type)
  (ecase type (:f32 'single-float) (:f64 'double-float)))

(defun scalar-kernel-form (node type arguments offsets index)
  (let ((element (kernel-element-type type))
        (inputs (loop for nil in arguments collect (gensym "ELEMENT")))
        (temporaries '()) (free '()) (assignments '()))
    (labels ((allocate ()
               (or (pop free)
                   (let ((name (gensym "VALUE"))) (push name temporaries) name)))
             (operation (operator operands)
               (let ((result (or (find-if (lambda (operand) (member operand temporaries)) operands)
                                 (allocate))))
                 (push `(setf ,result (,operator ,@operands)) assignments)
                 (dolist (operand operands)
                   (when (and (member operand temporaries) (not (eq operand result)))
                     (push operand free)))
                 result))
             (walk (node)
               (ecase (first node)
                 (:argument (nth (second node) inputs))
                 (:constant (coerce (second node) element))
                 (:negate (operation '- (list (walk (second node)))))
                 (:unary (operation (if (eq (second node) :sqrt) 'kernel-sqrt 'abs)
                                    (list (walk (third node)))))
                 (:fma (operation 'fma (mapcar #'walk (rest node))))
                 (:operation
                  (operation (case (second node)
                               (:min 'kernel-min) (:max 'kernel-max)
                               (t (car (rassoc (second node) *kernel-operators*))))
                             (list (walk (third node)) (walk (fourth node))))))))
      (let ((result (walk node)))
        `(let ,(loop for input in inputs for argument in arguments for offset in offsets
                     collect `(,input (aref ,argument (+ ,offset ,index))))
           ,@(when inputs `((declare (type ,element ,@inputs))))
           (let ,(loop for temporary in temporaries collect `(,temporary ,(coerce 0 element)))
             ,@(when temporaries `((declare (type ,element ,@temporaries))))
             ,@(nreverse assignments)
             ,result))))))

(defun lisp-kernel-form (tree type destination arguments d-offset offsets count)
  (let ((index (gensym "I")) (sum (gensym "SUM"))
        (element (kernel-element-type type))
        (variables (if destination (cons destination arguments) arguments)))
    `(let ,(mapcar (lambda (variable) (list variable variable)) variables)
       (declare (type (simple-array ,element (*)) ,@variables)
                (type fixnum ,count ,@(when destination (list d-offset)) ,@offsets))
       ,(if destination
            `(dotimes (,index ,count)
               (setf (aref ,destination (+ ,d-offset ,index))
                     ,(scalar-kernel-form tree type arguments offsets index)))
            `(let ((,sum ,(coerce 0 element)))
               (declare (type ,element ,sum))
               (dotimes (,index ,count ,sum)
                 (incf ,sum ,(scalar-kernel-form tree type arguments offsets index))))))))

#+(and sbcl x86-64)
(defun sbcl-kernel-form (tree type destination arguments d-offset offsets count)
  (destructuring-bind (package width prefix)
      (ecase type (:f32 '("SB-SIMD-SSE" 4 "F32.4")) (:f64 '("SB-SIMD-SSE2" 2 "F64.2")))
    (flet ((symbol-for (suffix)
             (or (find-symbol (concatenate 'string prefix suffix) package)
                 (error "sb-simd symbol ~A~A is missing" prefix suffix))))
      (let ((index (gensym "I"))
            (variables (if destination (cons destination arguments) arguments))
            (aref (symbol-for "-AREF"))
            (cast (symbol-for ""))
            (assignments '())
            (temporaries '())
            (free '())
            (inputs (make-array (length arguments) :initial-element nil))
            (sum (gensym "SUM")) (sum-pack (gensym "SUM-PACK")))
        (labels ((allocate ()
                   (or (pop free)
                       (let ((name (gensym "PACK")))
                         (push name temporaries)
                         name)))
                 (emit (name form)
                   (push `(setf ,name ,form) assignments)
                   name)
                 (operation (operator operands)
                   (let ((result (or (find-if (lambda (operand) (member operand temporaries))
                                             operands)
                                     (allocate))))
                     (emit result (cons operator operands))
                     (dolist (operand operands)
                       (when (and (member operand temporaries) (not (eq operand result)))
                         (push operand free)))
                     result))
                 (pack-math (kind operands)
                   (let* ((result (or (find-if (lambda (operand) (member operand temporaries)) operands)
                                      (allocate)))
                          (packed (mapcar (lambda (operand) `(,cast ,operand)) operands))
                          (form
                            (case kind
                              (:abs `(,(symbol-for "-ANDC1") (,cast ,(- (coerce 0 (kernel-element-type type))))
                                      ,(first packed)))
                              ((:min :max) `(,(symbol-for (if (eq kind :min) "-MIN" "-MAX"))
                                            ,(second packed) ,(first packed)))
                              (t
                               (let ((lanes (loop for nil in operands
                                                  collect (loop repeat width collect (gensym "LANE")))))
                                 (labels ((bind-lanes (remaining packs body)
                                            (if remaining
                                                `(multiple-value-bind ,(first remaining)
                                                     (,(symbol-for "-VALUES") ,(first packs))
                                                   ,(bind-lanes (rest remaining) (rest packs) body))
                                                body)))
                                   (bind-lanes
                                    lanes packed
                                    (if (eq kind :sqrt)
                                        `(progn
                                           (when (or ,@(mapcar (lambda (lane) `(minusp ,lane)) (first lanes)))
                                             (error "Negative kernel square root operand"))
                                           (,(symbol-for "-SQRT") ,(first packed)))
                                        `(,(find-symbol (concatenate 'string "MAKE-" prefix) package)
                                          ,@(loop for i below width
                                                  collect `(fma ,@(mapcar (lambda (group) (nth i group)) lanes))))))))))))
                     (emit result form)
                     (dolist (operand operands)
                       (when (and (member operand temporaries) (not (eq operand result)))
                         (push operand free)))
                     result))
                 (walk (node)
                   (ecase (first node)
                     (:argument
                      (let ((argument (second node)))
                        (or (aref inputs argument)
                            (setf (aref inputs argument)
                                  (emit (gensym "INPUT")
                                        `(,aref ,(nth argument arguments)
                                                (+ ,(nth argument offsets) ,index)))))))
                     (:constant (coerce (second node) (kernel-element-type type)))
                     (:negate (operation (symbol-for "-") (list `(,cast 0) (walk (second node)))))
                     (:unary (pack-math (second node) (list (walk (third node)))))
                     (:fma (pack-math :fma (mapcar #'walk (rest node))))
                     (:operation
                      (if (member (second node) '(:min :max))
                          (pack-math (second node) (list (walk (third node)) (walk (fourth node))))
                          (operation (symbol-for (string (car (rassoc (second node) *kernel-operators*))))
                                 (list (walk (third node)) (walk (fourth node)))))))))
          ;; A long LET* also exhausts SBCL's compiler stack; use flat assignments.
          (let* ((result (walk tree))
                 (packs (append (remove nil (coerce inputs 'list)) temporaries))
                 (lanes (loop repeat width collect (gensym "LANE"))))
            `(let ,(mapcar (lambda (variable) (list variable variable)) variables)
               (declare (type (simple-array ,(kernel-element-type type) (*)) ,@variables)
                        (type fixnum ,count ,@(when destination (list d-offset)) ,@offsets))
               (let ((,index 0)
                     ,@(unless destination
                         `((,sum ,(coerce 0 (kernel-element-type type))) (,sum-pack (,cast 0)))))
                 (declare (type fixnum ,index)
                          ,@(unless destination
                              `((type ,(kernel-element-type type) ,sum) (type ,cast ,sum-pack))))
                 (loop while (<= (+ ,index ,width) ,count) do
                   (let ,(loop for name in packs collect `(,name (,cast 0)))
                     ,@(when packs `((declare (type ,cast ,@packs))))
                     ,@(nreverse assignments)
                     ,(if destination
                          `(setf (,aref ,destination (+ ,d-offset ,index)) (,cast ,result))
                          `(setf ,sum-pack (,(symbol-for "+") ,sum-pack (,cast ,result)))))
                   (incf ,index ,width))
                 ,@(unless destination
                     `((multiple-value-bind ,lanes (,(symbol-for "-VALUES") ,sum-pack)
                         (setf ,sum (+ ,@lanes)))))
                 (loop while (< ,index ,count) do
                   ,(if destination
                        `(setf (aref ,destination (+ ,d-offset ,index))
                               ,(scalar-kernel-form tree type arguments offsets index))
                        `(incf ,sum ,(scalar-kernel-form tree type arguments offsets index)))
                   (incf ,index))
                 ,@(unless destination (list sum))))))))))

;; TODO: pointer/output setup dominates short kernels; specialize runners if worthwhile (#59).
(defun native-kernel-form (program foreign destination arguments d-offset offsets count)
  (let ((pointers (loop for nil in arguments collect (gensym "POINTER")))
        (output (gensym "OUTPUT")) (table (gensym "TABLE")))
    `(with-native-vectors (,foreign (,@(when destination `((,output ,destination ,d-offset)))
                                    ,@(mapcar #'list pointers arguments offsets))
                          :outputs ,(when destination (list output))
                          :count ,count)
       (cffi:with-foreign-object (,table :pointer ,(max 1 (length arguments)))
         ,@(loop for pointer in pointers for index from 0
                 collect `(setf (cffi:mem-aref ,table :pointer ,index)
                                ,pointer))
         ,(if destination
              `(call-native-kernel ,program ,foreign ,table
                                   ,output ,count)
              `(cffi:with-foreign-object (,output ,foreign)
                 (call-native-kernel ,program ,foreign ,table ,output ,count :sum-p t)
                 (cffi:mem-ref ,output ,foreign)))))))

#+ecl
(declaim (notinline compile-native-kernel-runner))
;; TODO: per-kernel compilation costs hundreds of ms; share runners by signature (#58).
#+ecl
(defun compile-native-kernel-runner (form fallback)
  (handler-case
      (let ((*compile-verbose* nil) (*compile-print* nil))
        (multiple-value-bind (function warnings failure) (compile nil form)
          (declare (ignore warnings))
          (if failure fallback function)))
    (error () fallback)))

#+ecl
(defun ensure-native-kernel-runner (program form fallback)
  (or (native-program-runner program)
      (setf (native-program-runner program)
            (compile-native-kernel-runner form fallback))))

(defmacro define-kernel (name (&rest arguments) expression)
  "Define an elementwise destination kernel or a scalar (SUM expression) kernel.
Both accept START, END, and per-input start keywords. Experimental."
  (when (> (length arguments) +kernel-max-arguments+)
    (error "A kernel takes at most ~D arguments" +kernel-max-arguments+))
  (let* ((reduction-p (and (consp expression) (eq (first expression) 'sum)))
         (destination (unless reduction-p (gensym "DESTINATION"))))
    (when reduction-p
      (unless (and arguments (= 2 (length expression)))
        (error "A sum kernel needs input vectors and one expression")))
    (let ((tree (parse-kernel-expression (if reduction-p (second expression) expression) arguments)))
      (multiple-value-bind (instructions constants scratch-count) (lower-kernel tree)
        (let* ((count (gensym "COUNT"))
               (d-offset (when destination (gensym "D-OFFSET")))
               (offsets (loop for nil in arguments collect (gensym "OFFSET")))
               (program (gensym "PROGRAM")) (type (gensym "TYPE"))
               (offsets-variable (gensym "OFFSETS"))
               (starts (mapcar (lambda (argument) (intern (format nil "~A-START" argument))) arguments))
               (vectors (if destination (cons destination arguments) arguments))
               (all-starts (if destination (cons 'destination-start starts) starts))
               (all-offsets (if destination (cons d-offset offsets) offsets))
               (bytes (kernel-bytes instructions))
               (native-form `(if (eq ,type :f32)
                                 ,(native-kernel-form program :float destination arguments d-offset offsets count)
                                 ,(native-kernel-form program :double destination arguments d-offset offsets count)))
               #+ecl (runner (gensym "RUNNER"))
               #+ecl (runner-arguments (append (list program type count) vectors all-offsets))
               #+ecl (runner-form `(lambda ,runner-arguments ,native-form)))
          `(let ((,program nil)
                 #+ecl (,runner ,runner-form))
             (defun ,name (,@vectors &key start end ,@all-starts)
               ,(if reduction-p "Return the sum of the kernel expression over the input slice."
                    "Compute the kernel expression into destination and return it.")
               (multiple-value-bind (,type ,count ,offsets-variable)
                   (resolve-slice (list ,@vectors) (list ,@all-starts) start end)
                 (destructuring-bind ,all-offsets ,offsets-variable
                   (declare (type fixnum ,@all-offsets))
                   (ecase *backend*
                     (:lisp (if (eq ,type :f32)
                                ,(lisp-kernel-form tree :f32 destination arguments d-offset offsets count)
                                ,(lisp-kernel-form tree :f64 destination arguments d-offset offsets count)))
                     (:sbcl
                      ,(if (and (boundp '*sbcl-simd-available-p*) *sbcl-simd-available-p*)
                           #+(and sbcl x86-64)
                           `(if (eq ,type :f32)
                                ,(sbcl-kernel-form tree :f32 destination arguments d-offset offsets count)
                                ,(sbcl-kernel-form tree :f64 destination arguments d-offset offsets count))
                           #-(and sbcl x86-64)
                           '(error "SBCL SIMD is unavailable on this platform")
                           '(error "SBCL SIMD is unavailable on this platform")))
                     (:native
                      (let ((,program (or ,program
                                          (setf ,program (make-native-program ',bytes ',constants ,scratch-count)))))
                        #+ecl (funcall (ensure-native-kernel-runner ,program ',runner-form ,runner)
                                       ,@runner-arguments)
                        #-ecl ,native-form))))
                 ,@(when destination (list destination))))))))))
