(require :asdf)
(asdf:load-system :trivial-simd)
(defpackage #:trivial-simd/activation-bench
  (:use #:cl)
  (:local-nicknames (#:simd #:trivial-simd)))
(in-package #:trivial-simd/activation-bench)
(simd:define-kernel logarithm (x) (log x))
(simd:define-kernel hyperbolic (x) (tanh x))
(simd:define-kernel sigmoid (x) (simd:sigmoid x))
(simd:define-kernel silu (x) (* x (simd:sigmoid x)))
(simd:define-kernel gelu (x)
  (* 0.5 x (+ 1 (tanh (* 0.7978845608028654d0 (+ x (* 0.044715d0 x x x)))))))
(declaim (inline sigmoid-value silu-value gelu-value))
(defun sigmoid-value (x) (simd:sigmoid x))
(defun silu-value (x) (* x (simd:sigmoid x)))
(defun gelu-value (x)
  (* (float 0.5 x) x (+ (float 1 x) (tanh (* (float 0.7978845608028654d0 x)
                                            (+ x (* (float 0.044715d0 x) x x x)))))))
(defmacro typed-loop (name element scalar)
  `(defun ,name (out x)
     (declare (type (simple-array ,element (*)) out x) (optimize (speed 3) (safety 1)))
     (dotimes (i (length x) out) (setf (aref out i) (,scalar (aref x i))))))
(typed-loop log-f32 single-float log)
(typed-loop log-f64 double-float log)
(typed-loop tanh-f32 single-float tanh)
(typed-loop tanh-f64 double-float tanh)
(typed-loop sigmoid-f32 single-float sigmoid-value)
(typed-loop sigmoid-f64 double-float sigmoid-value)
(typed-loop silu-f32 single-float silu-value)
(typed-loop silu-f64 double-float silu-value)
(typed-loop gelu-f32 single-float gelu-value)
(typed-loop gelu-f64 double-float gelu-value)
(format t "~&dtype,size,operation,path,microseconds~%")
(dolist (type '(single-float double-float))
  (dolist (n '(32 1024 65536))
    (let* ((x (make-array n :element-type type :initial-contents
                           (loop for i below n collect (coerce (+ 0.001d0 (/ (mod i 21) 5)) type))))
           (out (make-array n :element-type type))
           (repetitions (max 20 (floor 2000000 n))))
      (dolist (entry (list (list 'log #'logarithm (if (eq type 'single-float) #'log-f32 #'log-f64))
                          (list 'tanh #'hyperbolic (if (eq type 'single-float) #'tanh-f32 #'tanh-f64))
                          (list 'sigmoid #'sigmoid (if (eq type 'single-float) #'sigmoid-f32 #'sigmoid-f64))
                          (list 'silu #'silu (if (eq type 'single-float) #'silu-f32 #'silu-f64))
                          (list 'gelu #'gelu (if (eq type 'single-float) #'gelu-f32 #'gelu-f64))))
        (dolist (backend '(:typed :lisp :native))
          (when (or (not (eq backend :native)) simd::*native-available-p*)
            (let* ((simd::*backend* (if (eq backend :typed) :lisp backend))
                   (function (if (eq backend :typed) (third entry) (second entry))))
              (let ((expected (make-array n :element-type type)))
                (funcall (third entry) expected x)
                (funcall function out x)
                (assert (every (lambda (a b)
                                 (<= (abs (- a b))
                                     (* (if (eq type 'single-float) 2e-6 2d-14)
                                        (max 1 (abs b))))) out expected)))
              (let ((start (get-internal-real-time)))
                (dotimes (i repetitions) (funcall function out x))
                (format t "~A,~D,~A,~A,~,3F~%" type n (first entry) backend
                        (/ (* 1d6 (- (get-internal-real-time) start))
                           (* internal-time-units-per-second repetitions)))))))))))
