(in-package #:trivial-simd/tests)

(in-suite :trivial-simd)

(simd:define-kernel complex-equal (a b) (= a b))
(simd:define-kernel complex-unequal (a b) (/= a b))
(simd:define-kernel complex-choice (a b) (simd:select (= a b) (+ a b) (- a b)))
(simd:define-kernel complex-nested-choice (a b)
  (simd:select (= (+ a 1) b) (simd:select (/= a 0) (* a b) 0) (- b)))
(simd:define-kernel complex-match-count (a b) (simd:count (= a b)))
(simd:define-kernel complex-match-any (a b) (simd:any (= a b)))
(simd:define-kernel complex-match-all (a b) (simd:all (= a b)))
(simd:define-kernel complex-choice-sum (a b) (simd:sum (simd:select (= a b) a b)))
(simd:define-kernel complex-choice-asum (a b) (simd:asum (simd:select (= a b) a b)))
(simd:define-kernel complex-choice-nrm2 (a b) (simd:nrm2 (simd:select (= a b) a b)))
(simd:define-kernel complex-choice-root (a b) (simd:select (= a b) (sqrt a) (/ a b)))
(simd:define-kernel complex-mask-plan (a b)
  (simd:select (= a (/ (simd:sum a) (simd:sum 1))) (/ a (simd:nrm2 a)) b))
(simd:define-kernel complex-plan-count (a b) (simd:count (= a (/ (simd:sum b) (simd:sum 1)))))

(macrolet ((define-complex-spilling ()
             (labels ((tree (depth)
                        (if (zerop depth) 'a
                            `(simd:select (= a b) ,(tree (1- depth)) ,(tree (1- depth))))))
               `(simd:define-kernel complex-spilled (a b) (simd:count (= ,(tree 8) b))))))
  (define-complex-spilling))

(defun complex-mask-inputs (length type)
  (let ((real (second type)))
    (flet ((number (re im) (complex (coerce re real) (coerce im real))))
      (let* ((a (make-array length :element-type type
                                  :initial-contents (loop for i below length
                                                         collect (number (mod i 5) (mod i 3)))))
             (b (copy-seq a)))
        (dotimes (i length)
          (unless (zerop (mod i 3))
            (incf (aref b i) (if (oddp i) (number 0 1) (number 1 0)))))
        (values a b)))))

(test complex-mask-expressions
  (dolist (type '((complex single-float) (complex double-float)))
    (dolist (length '(0 1 2 3 4 5 19 255 256 257 513))
      (multiple-value-bind (a b) (complex-mask-inputs length type)
        (let* ((mask (make-array length :element-type '(unsigned-byte 8)))
               (out (make-array length :element-type type))
               (equal (map 'vector (lambda (x y) (if (= x y) 1 0)) a b))
               (choice (map 'vector (lambda (x y) (if (= x y) (+ x y) (- x y))) a b))
               (nested (map 'vector (lambda (x y) (if (= (+ x 1) y) (if (/= x 0) (* x y) 0) (- y))) a b))
               (count (count 1 equal)))
          (dolist (backend (available-backends))
            (with-backend (backend)
              (is (eq mask (complex-equal mask a b)))
              (is (equalp mask equal))
              (complex-unequal mask a b)
              (is (equalp mask (map 'vector (lambda (x) (- 1 x)) equal)))
              (is (eq out (complex-choice out a b)))
              (is (equalp out choice))
              (complex-nested-choice out a b)
              (is (equalp out nested))
              (is (= count (complex-match-count a b)))
              (is (eql (plusp count) (complex-match-any a b)))
              (is (eql (= count length) (complex-match-all a b)))
              (is (complex-match-all a a))
              (is (= length (complex-match-count a a))))))))))

(test complex-mask-reductions-and-passes
  (dolist (type '((complex single-float) (complex double-float)))
    (let ((real (second type)))
      (dolist (length '(0 1 5 255 256 257 513))
        (multiple-value-bind (a b) (complex-mask-inputs length type)
          (let* ((chosen (map 'vector (lambda (x y) (if (= x y) x y)) a b))
                 (sum (reduce #'+ chosen :initial-value (coerce 0 type)))
                 (asum (reduce #'+ chosen :key #'abs :initial-value (coerce 0 real)))
                 (norm (sqrt (reduce #'+ chosen :key (lambda (z) (+ (expt (realpart z) 2)
                                                                  (expt (imagpart z) 2)))
                                     :initial-value (coerce 0 real)))))
            (dolist (backend (available-backends))
              (with-backend (backend)
                (let ((actual (complex-choice-sum a b)))
                  (is (typep actual type))
                  (is (= sum actual)))
                (let ((actual (complex-choice-asum a b)))
                  (is (typep actual real))
                  (is (close-enough-p actual asum real)))
                (let ((actual (complex-choice-nrm2 a b)))
                  (is (typep actual real))
                  (is (close-enough-p actual norm real))))))))
      (let* ((z (complex (coerce 3 real) (coerce 4 real)))
             (a (make-array 257 :element-type type :initial-element z))
             (b (copy-seq a)) (out (copy-seq a))
             (expected (/ z (* (coerce 5 real) (sqrt (coerce 257 real))))))
        (dolist (backend (available-backends))
          (with-backend (backend)
            (complex-mask-plan out a b)
            (is (every (lambda (value) (close-enough-p value expected real)) out))
            (is (= 257 (complex-plan-count a b)))))))))

(test complex-mask-slices-views-and-overlap
  (dolist (type '((complex single-float) (complex double-float)))
    (multiple-value-bind (a b) (complex-mask-inputs 600 type)
      (dolist (backend (available-backends))
        (with-backend (backend)
          (let ((out (copy-seq a)) (mask (make-array 600 :element-type '(unsigned-byte 8) :initial-element 9)))
            (complex-equal mask a b :start 1 :end 258 :a-start 2 :b-start 4 :destination-start 3)
            (is (= 9 (aref mask 2)))
            (is (= 9 (aref mask 260)))
            (is (loop for i below 257 always
                      (= (aref mask (+ i 3)) (if (= (aref a (+ i 2)) (aref b (+ i 4))) 1 0))))
            (dolist (shift '(1 -1))
              (let* ((input-start (if (plusp shift) 0 1))
                     (output-start (if (plusp shift) 1 0))
                     (expected (map 'vector (lambda (x y) (if (= x y) (+ x y) (- x y)))
                                    (subseq out input-start (+ input-start 257)) (subseq b 0 257))))
                (complex-choice out out b :end 257 :a-start input-start :destination-start output-start)
                (is (equalp expected (subseq out output-start (+ output-start 257))))))
            (let ((simd::*view-block-size* 5))
              (check-views #'complex-choice (list (copy-seq a) a b))
              (check-views #'complex-equal (list mask a b))
              (check-views #'complex-choice-sum (list a b))
              (check-views #'complex-choice-asum (list a b) :test #'numerically-close-p)
              (check-views #'complex-choice-nrm2 (list a b) :test #'numerically-close-p)
              (check-views #'complex-match-count (list a b)))))))))

(test complex-mask-validation-and-fallback
  (dolist (type '((complex single-float) (complex double-float)))
    (let ((a (make-array 3 :element-type type :initial-element (coerce 1 type)))
          (out (make-array 3 :element-type type :initial-element (coerce 9 type)))
          (mask (make-array 3 :element-type '(unsigned-byte 8) :initial-element 9)))
      (dolist (backend (available-backends))
        (with-backend (backend)
          (fill out (coerce 9 type))
          (dolist (end '(0 3))
            (signals error (mask-kernel-compare mask a a :end end))
            (signals error (mask-kernel-select out a a :end end)))
          (is (every (lambda (x) (= x 9)) out))
          (is (equalp mask #(9 9 9)))
          (signals error (complex-equal out a a))
          (signals error (complex-equal mask a #(1 2 3)))
          (signals error (complex-choice out a a :end 4))
          (let ((simd::*native-complex-kernels-p* nil))
            (complex-choice out a a)
            (is (every (lambda (x) (= x 2)) out))
            (is (= 3 (complex-match-count a a)))
            (is (= 3 (complex-choice-sum a a)))))))))

(test complex-mask-native-dispatch-and-redefinition
  (when simd::*native-complex-kernels-p*
    (let ((original (symbol-function 'simd::call-native-complex-kernel)) (calls 0))
      (unwind-protect
           (progn
             (setf (symbol-function 'simd::call-native-complex-kernel)
                   (lambda (&rest arguments) (incf calls) (apply original arguments)))
             (dolist (type '((complex single-float) (complex double-float)))
               (let* ((a (make-array 257 :element-type type :initial-element (coerce 1 type)))
                      (out (copy-seq a)))
                 (with-backend (:native)
                   (complex-choice out a a)
                   (is (plusp calls))
                   (setf calls 0)
                   (complex-mask-plan out a a)
                   (is (= 4 calls))
                   (setf calls 0)
                   (eval '(simd:define-kernel complex-redefined (a b) (simd:count (= a b))))
                   (let ((old (symbol-function 'complex-redefined)))
                     (is (= 257 (funcall old a a)))
                     (eval '(simd:define-kernel complex-redefined (a b) (simd:count (/= a b))))
                     (is (= 0 (funcall (symbol-function 'complex-redefined) a a)))
                     (is (= 257 (funcall old a a))))))))
        (setf (symbol-function 'simd::call-native-complex-kernel) original)))))

(test complex-mask-math-and-extreme-norms
  (dolist (type '((complex single-float) (complex double-float)))
    (let* ((real (second type))
           (a (make-array 5 :element-type type
                             :initial-contents (mapcar (lambda (z) (coerce z type))
                                                       '(#c(3 4) #c(-3 -4) #c(1 1) #c(2 -1) #c(4 3)))))
           (b (copy-seq a)) (out (copy-seq a)))
      (incf (aref b 2) (coerce 1 type))
      (dolist (backend (available-backends))
        (with-backend (backend)
          (complex-choice-root out a b)
          (dotimes (i 5)
            (let ((expected (if (= (aref a i) (aref b i)) (sqrt (aref a i))
                                (/ (aref a i) (aref b i)))))
              (is (close-enough-p (aref out i) expected real))))
          (dolist (scale (if (eq real 'single-float) '(1f30 1f-30) '(1d300 1d-300)))
            (let* ((z (complex scale scale))
                   (input (make-array 3 :element-type type :initial-element z))
                   (actual (complex-choice-nrm2 input input))
                   (expected (* scale (sqrt (coerce 6 real)))))
              (is (typep actual real))
              (is (< (abs (- (/ actual expected) 1)) (float-tolerance real))))))))))

(test complex-mask-spilling-and-concurrent-calls
  (eval '(simd:define-kernel complex-concurrent (a b)
           (simd:select (= a (/ (simd:sum a) (simd:sum 1))) (/ a (simd:nrm2 a)) b)))
  (dolist (type '((complex single-float) (complex double-float)))
    (multiple-value-bind (a b) (complex-mask-inputs 257 type)
      (dolist (backend (available-backends))
        (with-backend (backend)
          (is (= 86 (funcall (symbol-function 'complex-spilled) a b)))))
      (let ((results (make-array 4)) (threads nil))
        (dotimes (i 4)
          (let ((slot i))
            (push (bt:make-thread
                   (lambda ()
                     (with-backend ((if simd::*native-complex-kernels-p* :native :lisp))
                       (let* ((real (second type))
                              (z (complex (coerce (1+ slot) real) (coerce 2 real)))
                              (input (make-array 257 :element-type type :initial-element z))
                              (out (copy-seq input))
                              (expected (/ z (* (abs z) (sqrt (coerce 257 real))))))
                         (dotimes (round 3)
                           (funcall (symbol-function 'complex-concurrent) out input input))
                         (setf (aref results slot)
                               (every (lambda (value) (close-enough-p value expected real)) out)))))) threads)))
        (mapc #'bt:join-thread threads)
        (is (every #'identity results))))))

(test complex-native-constant-ownership
  (dolist (type '(:c32 :c64))
    (let ((release nil) (frees 0) (free #'simd::free-native-program-buffers))
      (with-function-replaced
          (simd::register-native-program-finalizer
           (lambda (program callback) (declare (ignore program)) (setf release callback)))
        (let ((program (simd::make-native-program '(1 255 0 0) '(#c(3 4)) 0 type)))
          (let ((foreign (if (eq type :c32) :float :double)))
            (is (= 3 (cffi:mem-aref (simd::native-program-constants program) foreign 0)))
            (is (= 4 (cffi:mem-aref (simd::native-program-constants program) foreign 1))))))
      (with-function-replaced
          (simd::free-native-program-buffers
           (lambda (buffers) (incf frees (count-if #'identity buffers)) (funcall free buffers)))
        (funcall release)
        (funcall release)
        (is (= 2 frees))))
    (let ((frees 0) (free #'simd::free-native-program-buffers))
      (with-function-replaced
          (simd::free-native-program-buffers
           (lambda (buffers) (incf frees (count-if #'identity buffers)) (funcall free buffers)))
        (signals error (simd::make-native-program '(1 255 0 0) '(invalid) 0 type)))
      (is (= 1 frees)))))

(test complex-mask-invalid-branches
  (dolist (expression '((< a b) (<= a b) (> a b) (>= a b)
                        (min a b) (max a b) (abs a) (simd:fma a b a)
                        (exp a) (sin a) (cos a)))
    (eval `(simd:define-kernel complex-invalid (a b)
             (simd:select (= a b) ,(if (member (first expression) '(< <= > >=))
                                     `(simd:select ,expression a b) expression) b)))
    (dolist (type '((complex single-float) (complex double-float)))
      (let* ((input (make-array 3 :element-type type :initial-element (coerce 1 type)))
             (out (make-array 3 :element-type type :initial-element (coerce 9 type))))
        (dolist (backend (available-backends))
          (with-backend (backend)
            (signals error (funcall (symbol-function 'complex-invalid) out input input :end 0))
            (signals error (funcall (symbol-function 'complex-invalid) out input input))
            (is (every (lambda (value) (= value 9)) out))))))))
