(in-package #:trivial-simd/tests)

(in-suite :trivial-simd)

(defun complex-vector (type values)
  (make-array (length values) :element-type type :initial-contents values))

(simd:define-kernel complex-arithmetic-kernel (x y) (+ (* x y) (sqrt x)))
(simd:define-kernel complex-sum-kernel (x y) (simd:sum (* x y)))

(test complex-core-arithmetic
  (dolist (type '((complex single-float) (complex double-float)))
    (let* ((real-type (second type))
           (a (complex (coerce 1 real-type) (coerce 2 real-type)))
           (b (complex (coerce 3 real-type) (coerce 4 real-type)))
           (x (complex-vector type (make-list 64 :initial-element a)))
           (y (complex-vector type (make-list 64 :initial-element b)))
           (out (complex-vector type (make-list 64 :initial-element a)))
           (magnitude (make-array 64 :element-type real-type))
           (mask (make-array 64 :element-type '(unsigned-byte 8))))
      (dolist (backend (if trivial-simd::*native-complex-available-p*
                           '(:lisp :native) '(:lisp)))
        (let ((trivial-simd::*backend* backend))
          (simd:add! out x y)
          (is (= (aref out 0) (+ a b)))
          (simd:subtract! out x y)
          (is (= (aref out 63) (- a b)))
          (simd:multiply! out x y)
          (is (= (aref out 0) (* a b)))
          (simd:divide! out y x)
          (is (= (aref out 0) (/ b a)))
          (simd:scale! out a)
          (is (= (aref out 0) (* a (/ b a))))
          (simd:axpy! out a x)
          (is (= (aref out 0) (+ (* a (/ b a)) (* a a))))
          (is (= (simd:sum x) (* 64 a)))
          (is (= (simd:dot x y) (* 64 a b)))
          (is (= (simd:dotc x y) (* 64 (conjugate a) b)))
          (simd:abs! magnitude x)
          (is (close-enough-p (aref magnitude 0) (abs a) real-type))
          (simd:compare! mask :eq x x)
          (is (= (aref mask 0) 1))
          (simd:select! out mask x y)
          (is (= (aref out 0) a)))))))

(test complex-core-unary-and-conversion
  (let* ((x (complex-vector '(complex single-float)
                            '(#C(1.0f0 2.0f0) #C(3.0f0 4.0f0))))
         (out (copy-seq x))
         (real (make-array 2 :element-type 'single-float
                           :initial-contents '(2.0f0 3.0f0))))
    (simd:negate! out x)
    (is (= (aref out 0) #C(-1.0f0 -2.0f0)))
    (simd:reciprocal! out x)
    (is (= (aref out 0) (/ (aref x 0))))
    (simd:sqrt! out x)
    (is (= (aref out 1) (sqrt (aref x 1))))
    (simd:convert! out real)
    (is (= (aref out 0) #C(2.0f0 0.0f0)))
    (signals error (simd:convert! real x))
    (simd:convert! real out)
    (is (= (aref real 0) 2.0f0))
    (signals error (simd:min! out x x))
    (signals error (simd:compare! (make-array 2 :element-type '(unsigned-byte 8))
                                  :lt x x))))

(test complex-kernel-fallback
  (let* ((x (complex-vector '(complex single-float)
                            '(#C(1.0f0 2.0f0) #C(3.0f0 4.0f0))))
         (y (complex-vector '(complex single-float)
                            '(#C(5.0f0 6.0f0) #C(7.0f0 8.0f0))))
         (out (copy-seq x)))
    (complex-arithmetic-kernel out x y)
    (is (= (aref out 0) (+ (* (aref x 0) (aref y 0)) (sqrt (aref x 0)))))
    (is (= (complex-sum-kernel x y)
           (+ (* (aref x 0) (aref y 0)) (* (aref x 1) (aref y 1)))))))
