(eval-when (:compile-toplevel :load-toplevel :execute) (require :asdf))

(eval-when (:compile-toplevel :load-toplevel :execute)
  (load (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname)))
  (let ((root (merge-pathnames "../" (uiop:pathname-directory-pathname
                                      (or *compile-file-truename* *load-truename*)))))
    (asdf:initialize-source-registry `(:source-registry (:directory ,root) :inherit-configuration))
    (asdf:load-system "trivial-simd")
    (load (merge-pathnames "tests/benchmark-timing.lisp" root))))

(trivial-simd:define-kernel profile-mask (a b) (> a b))
(trivial-simd:define-kernel profile-select (a b) (trivial-simd:select (> a b) a b))
(trivial-simd:define-kernel profile-count (a b) (trivial-simd:count (> a b)))
(macrolet ((spilling ()
             (labels ((tree (depth on-true)
                        (if (zerop depth) (if on-true 'a 'b)
                            `(trivial-simd:select (> a b)
                                                 ,(tree (1- depth) t)
                                                 ,(tree (1- depth) nil)))))
               `(trivial-simd:define-kernel profile-spilling (a b)
                  (trivial-simd:count (> ,(tree 7 t) b))))))
  (spilling))

(defun profile-converter (source destination)
  (let ((source-element (second (trivial-simd::numeric-type source)))
        (element (second (trivial-simd::numeric-type destination))))
    (compile nil `(lambda (out input)
                    (declare (type (simple-array ,element (*)) out)
                             (type (simple-array ,source-element (*)) input))
                    (dotimes (i (length out) out)
                      (setf (aref out i)
                            ,(if (member destination '(:f32 :f64))
                                 `(coerce (aref input i) ',element)
                                 (multiple-value-bind (low high) (trivial-simd::integer-limits destination)
                                   `(min ,high (max ,low (aref input i)))))))))))

(defun profile-row (operation pair n baseline run)
  (let ((selection (uiop:getenv "CONVERSION_MASK_OPERATIONS")))
    (when (and selection
               (not (member operation (uiop:split-string selection :separator '(#\,)) :test #'string=)))
      (return-from profile-row)))
  (let ((scalar (benchmark-time baseline)))
    (dolist (backend (append '(:native) (when trivial-simd::*sbcl-simd-available-p* '(:sbcl))))
      (dolist (access (if (eq backend :native) '(:pointer :copy) '(:pointer)))
        (let ((trivial-simd::*backend* backend) (trivial-simd::*native-array-access* access))
          (funcall baseline)
          (let ((expected (let ((value *benchmark-result*))
                            (if (vectorp value) (copy-seq value) value))))
            (assert (equalp expected (funcall run))))
          (let ((elapsed (benchmark-time run)))
            (format t "~&~A,~A,~D,~A,~A,~,6F,~,6F,~,3F~%"
                    operation pair n backend access scalar elapsed (/ scalar elapsed))
            (finish-output)))))))

(let ((trivial-simd::*inline-small-arrays* nil)
      (trivial-simd::*native-numeric-conversion-minimum-count*
        (if (uiop:getenv "CONVERSION_MASK_CROSSOVER") 1 32768)))
  (format t "~&~A ~A ~A~%" (lisp-implementation-type) (lisp-implementation-version) (machine-type))
  (format t "operation,pair,elements,backend,access,scalar_us,candidate_us,speedup~%")
  (dolist (n (if (uiop:getenv "CONVERSION_MASK_CROSSOVER") '(4096 8192 16384 32768) '(32 1024 65536)))
    (dolist (pair '((:s8 :f32) (:u16 :f64) (:s32 :f32) (:u32 :f32)
                    (:s64 :f32) (:u64 :f64) (:s16 :u8) (:u32 :u16)))
      (destructuring-bind (source destination) pair
        (let* ((input (make-array n :element-type (second (trivial-simd::numeric-type source))
                                   :initial-element (coerce 127 (second (trivial-simd::numeric-type source)))))
               (out (make-array n :element-type (second (trivial-simd::numeric-type destination))))
               (reference (profile-converter source destination)))
          (profile-row "convert" (format nil "~A_~A" source destination) n
                       (lambda () (funcall reference out input))
                       (lambda () (trivial-simd:convert! out input))))))
    (unless (uiop:getenv "CONVERSION_MASK_CROSSOVER")
      (dolist (type '(:f32 :s8 :u64))
      (let* ((element (second (trivial-simd::numeric-type type)))
             (a (make-array n :element-type element :initial-element (coerce 2 element)))
             (b (make-array n :element-type element :initial-element (coerce 1 element)))
             (out (make-array n :element-type element))
             (mask (make-array n :element-type '(unsigned-byte 8))))
        (fill mask 255)
        (dolist (row (list (list "bulk-compare" (lambda () (trivial-simd:compare! mask :gt a b)))
                          (list "bulk-select" (lambda () (trivial-simd:select! out mask a b)))
                          (list "byte-count" (lambda () (trivial-simd:count mask)))
                          (list "mask-kernel" (lambda () (profile-mask mask a b)))
                          (list "select-kernel" (lambda () (profile-select out a b)))
                          (list "count-kernel" (lambda () (profile-count a b)))
                          (list "spilled-kernel" (lambda () (profile-spilling a b)))))
          (destructuring-bind (name run) row
            (profile-row name type n
                         (lambda () (let ((trivial-simd::*backend* :lisp)) (funcall run))) run))))))))
