(in-package #:trivial-simd/tests)

(defvar *test-phase-times* nil)

(defun measure-test-phase (phase thunk)
  (if *test-phase-times*
      (let ((start (get-internal-real-time)))
        (when (uiop:getenv "TRIVIAL_SIMD_TEST_PHASES")
          (format t "~&PHASE ~A~%" phase)
          (finish-output))
        (unwind-protect (funcall thunk)
          (incf (gethash phase *test-phase-times* 0)
                (- (get-internal-real-time) start))))
      (funcall thunk)))

(defmethod fiveam::run-test-lambda :around ((test fiveam::test-case))
  (if (uiop:getenv "TRIVIAL_SIMD_TEST_TIMING")
      (let ((start (get-internal-real-time))
            (*test-phase-times* (make-hash-table)))
        (format t "~&START ~A~%" (fiveam::name test))
        (finish-output)
        (unwind-protect (call-next-method)
          (format t "~&END ~A ~,3Fs" (fiveam::name test)
                  (/ (- (get-internal-real-time) start) internal-time-units-per-second))
          (maphash (lambda (phase ticks)
                     (format t " ~A=~,3Fs" phase (/ ticks internal-time-units-per-second)))
                   *test-phase-times*)
          (terpri)
          (finish-output)))
      (call-next-method)))

(defun run-tests ()
  (let ((selection (uiop:getenv "TRIVIAL_SIMD_TESTS"))
        (originals nil))
    (unwind-protect
         (progn
           (when (uiop:getenv "TRIVIAL_SIMD_TEST_TIMING")
             (dolist (entry '((padded-view :setup) (copy-view :setup)
                              (views-close-p :comparison) (view-elements-close-p :comparison)))
               (let* ((name (first entry)) (phase (second entry)) (original (symbol-function name)))
                 (push (cons name original) originals)
                 (setf (symbol-function name)
                       (lambda (&rest arguments)
                         (measure-test-phase phase (lambda () (apply original arguments))))))))
           (fiveam:run!
            (if (and selection (plusp (length selection)))
                (mapcar (lambda (name)
                          (let ((symbol (find-symbol (string-upcase name) :trivial-simd/tests)))
                            (unless (and symbol (fiveam:get-test symbol))
                              (error "Unknown test ~A" name))
                            symbol))
                        (remove "" (uiop:split-string selection :separator '(#\Space #\,)) :test #'equal))
                :trivial-simd)))
      (dolist (entry originals)
        (setf (symbol-function (car entry)) (cdr entry))))))
