(require :asdf)
(unless (find-package :ql)
  (dolist (candidate '("quicklisp/setup.lisp" ".roswell/lisp/quicklisp/setup.lisp"))
    (let ((path (merge-pathnames candidate (user-homedir-pathname))))
      (when (probe-file path) (load path) (return)))))

(let ((root (or (uiop:getenv "TRIVIAL_SIMD_SIZE_ROOT")
                (namestring (merge-pathnames "../" (uiop:pathname-directory-pathname *load-truename*))))))
  (asdf:initialize-source-registry `(:source-registry (:directory ,root) :inherit-configuration)))
(asdf:load-system "trivial-simd")

(defun expression-size (form)
  (if (consp form) (+ 1 (expression-size (car form)) (expression-size (cdr form))) 1))

(defun size-selection-tree (depth)
  (if (zerop depth) 'a
      `(trivial-simd:select (> a b) ,(size-selection-tree (1- depth))
                            ,(size-selection-tree (1- depth)))))

(defun size-baseline ()
  (let ((path (uiop:getenv "TRIVIAL_SIMD_SIZE_BASELINE")) (sizes (make-hash-table :test #'equal)))
    (when path
      (with-open-file (stream path)
        (loop for line = (read-line stream nil) while line
              when (uiop:string-prefix-p "SIZE " line)
                do (destructuring-bind (tag name size) (uiop:split-string line :separator '(#\Space))
                     (declare (ignore tag))
                     (setf (gethash name sizes) (parse-integer size))))))
    (values sizes path)))

(let* ((cases `((compare (> a b))
               (select (trivial-simd:select (> a b) a b))
               (count (trivial-simd:count (> a b)))
               (sum (trivial-simd:sum (trivial-simd:select (> a b) a b)))
               (arithmetic (+ (* a b) a))
               (spilling ,(size-selection-tree 7)))))
  (uiop:with-temporary-file (:stream stream :pathname source :prefix "trivial-simd-size-" :type "lisp" :keep t)
    (dolist (entry cases)
      (let ((form `(trivial-simd:define-kernel ,(intern (format nil "SIZE-~A" (first entry)))
                     (a b) ,(second entry))))
        (let ((size (expression-size (macroexpand form))))
          (format t "~&SIZE ~A ~D~%" (first entry) size)
          (multiple-value-bind (sizes path) (size-baseline)
            (when path
              (let ((baseline (gethash (symbol-name (first entry)) sizes)))
                (unless (and baseline (<= (* 10 size) (* 11 baseline)))
                  (error "~A exceeds the 10% expansion budget: ~D versus ~S" (first entry) size baseline))))))
        (write form :stream stream :readably t)
        (terpri stream)))
    (finish-output stream)
    (let ((start (get-internal-real-time)))
      (multiple-value-bind (file warnings failure) (compile-file source)
        (declare (ignore warnings))
        (when failure (error "Kernel size compilation failed"))
        (format t "~&COMPILE ~,6F~%" (/ (- (get-internal-real-time) start) internal-time-units-per-second))
        (with-open-file (stream file :element-type '(unsigned-byte 8))
          (format t "FASL ~D~%" (file-length stream)))))))
