(in-package #:trivial-simd/tests)

(in-suite :trivial-simd)

(simd:define-kernel input-dot (x (q :type :s8) (scale :repeat 32))
  (simd:sum (* x q scale)))
(simd:define-kernel input-product (x (q :type :s8) (scale :repeat 32)) (* x q scale))
(simd:define-kernel input-mask (x (q :type :s8) (scale :repeat 32)) (> (* x q scale) 0))
(simd:define-kernel input-selected (x (q :type :s8) (scale :repeat 32))
  (simd:sum (simd:select (> q 0) (* x q scale) 0)))
(simd:define-kernel input-fma (x (q :type :s8) (scale :repeat 32)) (simd:fma x q scale))
(simd:define-kernel input-root (x (q :type :s8)) (sqrt (+ x q)))

(macrolet ((define-reducers ()
             `(progn
                ,@(loop for reducer in '(simd:asum simd:nrm2 simd:minimum simd:maximum
                                         simd:argmin simd:argmax simd:count simd:any simd:all)
                        collect
                        `(simd:define-kernel ,(intern (format nil "INPUT-~A" reducer))
                             (x (q :type :s8) (scale :repeat 32))
                           (,reducer ,(if (member reducer '(simd:count simd:any simd:all))
                                          '(> (* x q scale) 0) '(* x q scale))))))))
  (define-reducers))

(defun input-data (n type &optional (repeat 32))
  (values (make-array n :element-type type :initial-element (coerce 0.5 type))
          (make-array n :element-type '(signed-byte 8)
                        :initial-contents (loop for i below n collect (- (mod i 17) 8)))
          (make-array (ceiling n repeat) :element-type type
                      :initial-contents (loop for i below (ceiling n repeat) collect (coerce (1+ i) type)))))

(defun input-reference (x q scale start end &optional (x-start start) (q-start start) (scale-start 0)
                                                          (repeat 32))
  (let ((type (array-element-type x)))
    (make-array (- end start) :element-type type
                :initial-contents
                (loop for i below (- end start)
                      collect (* (* (aref x (+ x-start i)) (coerce (aref q (+ q-start i)) type))
                                 (aref scale (+ scale-start (floor (+ start i) repeat))))))))

(test kernel-input-boundaries
  (dolist (type '(single-float double-float))
    (dolist (n '(0 1 3 4 5 31 32 33 255 256 257 513))
      (multiple-value-bind (x q scale) (input-data n type)
        (let ((before (list (copy-seq x) (copy-seq q) (copy-seq scale))))
          (dolist (backend (available-backends))
            (with-backend (backend)
              (let ((out (make-array n :element-type type))
                    (expected (input-reference x q scale 0 n)))
                (is (eq out (input-product out x q scale)))
                (is (equalp expected out))
                (is (= (loop for value across expected sum value) (input-dot x q scale)))
                (is (= (loop for i below n when (plusp (aref q i)) sum (aref expected i))
                       (input-selected x q scale)))
                (input-product x x q scale)
                (is (equalp expected x))
                (replace x (first before)))))
          (is (equalp before (list x q scale))))))))

(test kernel-input-slices
  (dolist (type '(single-float double-float))
    (multiple-value-bind (x q scale) (input-data 600 type)
      (dolist (backend (available-backends))
        (with-backend (backend)
          (dolist (slice '((5 34) (31 33) (33 290) (255 513)))
            (destructuring-bind (start end) slice
              (let ((expected (input-reference x q scale start end 11 17 1))
                    (out (make-array 600 :element-type type :initial-element (coerce -99 type))))
                (input-product out x q scale :start start :end end :x-start 11 :q-start 17
                               :scale-start 1 :destination-start 3)
                (is (equalp expected (subseq out 3 (+ 3 (- end start)))))
                (is (= -99 (aref out 2)))
                (is (= -99 (aref out (+ 3 (- end start)))))
                (is (= (loop for value across expected sum value)
                       (input-dot x q scale :start start :end end :x-start 11 :q-start 17 :scale-start 1)))))))))))

(test kernel-input-source-types
  (dolist (source '(:s8 :u8 :s16 :u16 :s32 :u32 :s64 :u64))
    (let* ((info (simd::numeric-type source)) (element (second info))
           (bits (fourth info)) (signed (fifth info))
           (maximum (1- (ash 1 (if signed (1- bits) bits))))
           (minimum (if signed (- (ash 1 (1- bits))) 0))
           (function (gensym "INPUT-CONVERT")))
      (eval `(simd:define-kernel ,function (x (q :type ,source)) (+ x q)))
      (dolist (type '(single-float double-float))
        (let* ((samples (remove-if-not (lambda (value) (typep value element))
                                      (list minimum maximum 0 1 -1 16777217 9007199254740993
                                            (+ (ash 1 62) (ash 1 38) 1)
                                            (- (+ (ash 1 62) (ash 1 38) 1)))))
               (q (make-array (length samples) :element-type element :initial-contents samples))
               (x (make-array (length samples) :element-type type :initial-element (coerce 0 type)))
               (out (make-array (length samples) :element-type type)))
          (dolist (backend (available-backends))
            (with-backend (backend)
              (funcall function out x q)
              (loop for sample in samples for i from 0
                    do (is (= (coerce sample type) (aref out i)))))))))))

(test kernel-input-repeat-factors
  (dolist (repeat '(1 3 32 257))
    (let ((function (gensym "INPUT-REPEAT")))
      (eval `(simd:define-kernel ,function (x (q :type :s8 :repeat ,repeat)) (* x q)))
      (let* ((n 600) (start 5) (x (make-array n :element-type 'single-float :initial-element 2f0))
             (q (make-array (+ 2 (ceiling n repeat)) :element-type '(signed-byte 8)
                            :initial-contents (loop for i below (+ 2 (ceiling n repeat)) collect (mod i 17))))
             (out (make-array n :element-type 'single-float :initial-element -99f0)))
        (dolist (backend (available-backends))
          (with-backend (backend)
            (funcall function out x q :start start :end n :q-start 2 :destination-start 0)
            (dotimes (i (- n start))
              (is (= (* 2 (aref q (+ 2 (if (= repeat 1) i (floor (+ start i) repeat)))))
                     (aref out i))))))))))

(test kernel-input-reducers
  (dolist (type '(single-float double-float))
    (dolist (n '(0 33 257 513))
      (multiple-value-bind (x q scale) (input-data n type)
        (let ((expected (input-reference x q scale 0 n)))
          (dolist (backend (available-backends))
            (with-backend (backend)
              (dolist (pair '((input-asum . simd:asum) (input-nrm2 . simd:nrm2)
                              (input-minimum . simd:minimum) (input-maximum . simd:maximum)
                              (input-argmin . simd:argmin) (input-argmax . simd:argmax)))
                (let ((actual (funcall (car pair) x q scale))
                      (reference (let ((simd::*backend* :lisp)) (funcall (cdr pair) expected))))
                  (is (if (floatp reference) (close-enough-p actual reference type) (eql actual reference)))))
              (let* ((truths (loop for value across expected count (plusp value)))
                     (mask (make-array n :element-type '(unsigned-byte 8))))
                (input-mask mask x q scale)
                (is (equalp mask (map '(vector (unsigned-byte 8)) (lambda (value) (if (plusp value) 1 0)) expected)))
                (is (= truths (input-count x q scale)))
                (is (eql (plusp truths) (input-any x q scale)))
                (is (eql (= truths n) (input-all x q scale)))))))))))

(test kernel-input-errors
  (dolist (arguments '((x (q :type :bad)) (x (q :repeat 0)) (x (q :repeat -1))
                       (x (q :repeat 1.5)) (x (q :repeat 3 :repeat 4))
                       (x (q :type :s8 :type :u8)) (x (q :unknown 1))
                       (x (x :type :s8)) ((x :repeat 3) (q :repeat 32))))
    (signals error (macroexpand-1 `(simd:define-kernel invalid-input-kernel ,arguments (+ x q)))))
  (multiple-value-bind (x q scale) (input-data 33 'single-float)
    (let ((out (make-array 33 :element-type 'single-float :initial-element -99f0)))
      (dolist (backend (available-backends))
        (with-backend (backend)
          (signals error (input-product out x x scale))
          (signals error (input-product out x q (subseq scale 0 1)))
          (signals error (input-product out x (subseq q 0 32) scale))
          (signals error (input-product out x q scale :start -1))
          (signals error (input-product out x q scale :scale-start -1))
          (signals error (input-product out x q (make-array 2 :element-type 'double-float)))
          (signals error (input-product out
                                        (simd:make-vector-view
                                         (cffi:make-pointer (- (ash 1 (* 8 (cffi:foreign-type-size :pointer))) 4))
                                         :f32 33)
                                        q scale))
          (signals error (input-product out x q out))
          (signals error (input-dot x q scale :rows 2 :row-length 32 :destination out))
          (signals error (input-dot x q scale :rows 1 :row-length 32 :destination x))
          (signals error (input-dot x q scale :rows 1 :row-length 32 :destination out :start 0))
          (signals error (input-dot x q scale :rows 1 :row-length 32 :destination out :destination-start nil))
          (signals error (input-dot x q scale :rows 1 :row-length 32 :destination out :q-row-stride nil))
          (signals error (input-dot x q scale :rows 1 :row-length 32 :destination out :q-row-stride (ash 1 63)))
          (is (every (lambda (value) (= -99 value)) out)))))))

(test kernel-input-rows
  (dolist (type '(single-float double-float))
    (dolist (length '(0 3 32 33 257))
      (multiple-value-bind (x q scale) (input-data (* 3 length) type)
        (setf scale (make-array (* 3 (ceiling length 32)) :element-type type
                               :initial-contents (loop for i below (* 3 (ceiling length 32))
                                                       collect (coerce (1+ i) type))))
        (dolist (backend (available-backends))
          (with-backend (backend)
            (let ((out (make-array 5 :element-type type :initial-element (coerce -99 type))))
              (is (eq out (input-dot x q scale :rows 3 :row-length length :destination out :destination-start 1)))
              (dotimes (row 3)
                (is (= (input-dot x q scale :end length :x-start (* row length) :q-start (* row length)
                                           :scale-start (* row (ceiling length 32)))
                       (aref out (1+ row)))))
              (input-dot x q scale :rows 3 :row-length length :destination out :destination-start 1
                         :x-start (* 2 length) :x-row-stride (- length)
                         :q-start (* 2 length) :q-row-stride (- length)
                         :scale-row-stride 0)
              (dotimes (row 3)
                (is (= (input-dot x q scale :end length :x-start (* (- 2 row) length)
                                           :q-start (* (- 2 row) length))
                       (aref out (1+ row)))))
              (input-dot x q scale :rows 0 :row-length length :destination out)
              (is (= -99 (aref out 0)))
              (is (= -99 (aref out 4))))))))))

(test kernel-input-native-fallback
  (multiple-value-bind (x q scale) (input-data 257 'single-float)
    (let ((simd::*backend* :native) (simd::*native-kernel-inputs-available-p* nil))
      (is (= (loop for value across (input-reference x q scale 0 257) sum value)
             (input-dot x q scale)))
      (let ((out (make-array 1 :element-type 'single-float)))
        (input-dot x q scale :rows 1 :row-length 257 :destination out)
        (is (= (input-dot x q scale) (aref out 0)))))))

(test kernel-input-views
  (dolist (type '(single-float double-float))
    (multiple-value-bind (x q scale) (input-data 600 type)
      (dolist (backend (available-backends))
        (dolist (block '(5 31 256 4096))
          (with-view-memory
            (with-backend (backend)
              (let ((simd::*view-block-size* block))
                (dolist (pattern '(0 1 2 3))
                  (let* ((vx (if (member pattern '(0 1)) (mirror x) x))
                         (vq (if (member pattern '(0 2)) (mirror q) q))
                         (vs (if (member pattern '(0 3)) (mirror scale) scale))
                         (out (mirror (make-array 600 :element-type type :initial-element (coerce -99 type))))
                         (expected (input-reference x q scale 5 290)))
                    (input-product out vx vq vs :start 5 :end 290 :destination-start 3)
                    (is (equalp expected (subseq (contents out) 3 288)))
                    (is (= (loop for value across expected sum value)
                           (input-dot vx vq vs :start 5 :end 290)))
                    (is (= (+ 5 (position (reduce #'max expected) expected))
                           (input-argmax vx vq vs :start 5 :end 290)))
                    (let ((results (mirror (make-array 2 :element-type type))))
                      (input-dot vx vq vs :rows 2 :row-length 257 :destination results
                                 :scale-row-stride 9)
                      (is (= (input-dot x q scale :end 257) (aref (contents results) 0)))
                      (is (= (input-dot x q scale :end 257 :x-start 257 :q-start 257 :scale-start 9)
                             (aref (contents results) 1))))))))))))))

(test kernel-input-view-overlap
  (dolist (backend (available-backends))
    (multiple-value-bind (x q scale) (input-data 33 'single-float)
      (declare (ignore scale))
      (with-view-memory
        (with-backend (backend)
          (let* ((out (mirror (make-array 33 :element-type 'single-float :initial-element -99f0)))
                 (scale (simd:make-vector-view (simd:vector-view-pointer out) :f32 2)))
            (signals error (input-product out x q scale))
            (signals error (input-dot x q scale :rows 1 :row-length 32 :destination out))
            (is (every (lambda (value) (= value -99)) (contents out))))
          #+(or sbcl ccl ecl)
          (simd::with-vector-pointer (pointer x)
            (let ((scale (simd:make-vector-view pointer :f32 2)))
              (signals error (input-product x x q scale)))))))))

(test kernel-input-fma-and-domain
  (dolist (backend (available-backends))
    (dolist (type '(single-float double-float))
      (multiple-value-bind (x q scale) (input-data 33 type)
        (with-backend (backend)
          (let ((out (make-array 33 :element-type type)))
            (input-fma out x q scale)
            (dotimes (i 33)
              (is (= (simd::portable-fma (aref x i) (coerce (aref q i) type) (aref scale (floor i 32)))
                     (aref out i))))
            (signals error (input-root out x q))))))))

(test kernel-input-norm-scaling
  (dolist (backend (available-backends))
    (let ((x (make-array 3 :element-type 'double-float :initial-contents '(1d200 1d-200 0d0)))
          (q (make-array 3 :element-type '(signed-byte 8) :initial-element 1))
          (scale (make-array 1 :element-type 'double-float :initial-element 1d0)))
      (with-backend (backend)
        (is (close-enough-p (input-nrm2 x q scale) 1d200 'double-float))
        (setf (aref x 0) 0d0)
        (is (= (input-nrm2 x q scale) 1d-200))))))

(test kernel-input-spilling-and-lifetime
  (let ((name (gensym "INPUT-SPILL")))
    (labels ((tree (depth) (if (zerop depth) '(* x q scale)
                              `(+ ,(tree (1- depth)) ,(tree (1- depth))))))
      (eval `(simd:define-kernel ,name (x (q :type :s8) (scale :repeat 32)) (simd:sum ,(tree 8)))))
    (let ((old (symbol-function name)))
      (eval `(simd:define-kernel ,name (x (q :type :s8) (scale :repeat 32)) (simd:sum 7)))
      (multiple-value-bind (x q scale) (input-data 257 'single-float)
        (dolist (backend (available-backends))
          (with-backend (backend)
            (is (= (* 256 (input-dot x q scale)) (funcall old x q scale)))
            (is (= (* 7 257) (funcall name x q scale)))))))))

(test kernel-input-concurrent-calls
  (multiple-value-bind (x q scale) (input-data 513 'single-float)
    (let* ((expected (loop for value across (input-reference x q scale 0 513) sum value))
           (workers (loop repeat 4 collect
                      (bordeaux-threads:make-thread
                       (lambda ()
                         (let ((simd::*backend* :native))
                           (loop repeat 10 always (= expected (input-dot x q scale)))))))))
      (dolist (worker workers)
        (is-true (bordeaux-threads:join-thread worker))))))

(test kernel-input-precision
  (let ((elementwise (gensym "INTEGER-INPUTS")) (reduction (gensym "INTEGER-REDUCTION")))
    (eval `(simd:define-kernel ,elementwise ((q :type :s8) (scale :repeat 32)) (* q scale)))
    (eval `(simd:define-kernel ,reduction ((q :type :s8) (scale :repeat 32)) (simd:sum (* q scale))))
    (dolist (type '(single-float double-float))
      (let ((float-input (gensym "FLOAT-INPUT")))
        (eval `(simd:define-kernel ,float-input (x (y :type ,(if (eq type 'single-float) :f32 :f64))) (+ x y)))
        (multiple-value-bind (x q scale) (input-data 33 type)
          (dolist (backend (available-backends))
            (with-backend (backend)
              (let ((out (make-array 33 :element-type type)))
                (funcall elementwise out q scale)
                (dotimes (i 33)
                  (is (= (* (coerce (aref q i) type) (aref scale (floor i 32))) (aref out i))))
                (funcall float-input out x x)
                (is (every (lambda (value) (= 1 value)) out))
                (signals error (funcall reduction q scale))))))))))

(test kernel-input-native-calls
  (when simd::*native-available-p*
    (is-true simd::*native-kernel-inputs-available-p*)
    (let ((original (symbol-function 'simd::call-declared-native)) (calls 0))
      (unwind-protect
           (progn
             (setf (symbol-function 'simd::call-declared-native)
                   (lambda (&rest arguments) (incf calls) (apply original arguments)))
             (multiple-value-bind (x q scale) (input-data 66 'single-float)
               (let ((out (make-array 2 :element-type 'single-float :initial-element -99f0)))
                 (dolist (backend '(:native :native-copy))
                   (with-backend (backend)
                     (setf calls 0)
                     (input-dot x q scale :rows 2 :row-length 33 :scale-row-stride 0 :destination out)
                     (is (= 1 calls))
                     (setf calls 0)
                     (input-dot x q scale :rows 0 :row-length 33 :destination out)
                     (is (zerop calls))
                     (input-dot x q scale :rows 2 :row-length 0 :destination out
                                :x-row-stride 99 :q-row-stride 99 :scale-row-stride 99)
                     (is (zerop calls))
                     (is (equalp out #(0f0 0f0))))))))
        (setf (symbol-function 'simd::call-declared-native) original)))))
