(in-package #:trivial-simd/tests)

(in-suite :trivial-simd)

(simd:define-kernel kernel-fma (a b c) (+ (* a b) c))
(simd:define-kernel kernel-poly (x) (- (* x x 2) (/ x 4) 1))
(simd:define-kernel kernel-negate (a b) (- (/ a b)))
(simd:define-kernel kernel-deep (a b c d) (/ (- (* a b) (* c d)) (+ a b c d)))
(simd:define-kernel kernel-constant () (+ 1 2))
(simd:define-kernel kernel-reciprocal (a) (/ a))

(defun kernel-reference (function type length &rest inputs)
  (let ((output (make-array length :element-type type)))
    (dotimes (i length output)
      (setf (aref output i)
            (apply function (mapcar (lambda (input) (aref input i)) inputs))))))

(defun check-kernel (kernel reference type length inputs &rest keys)
  (dolist (backend (available-backends))
    (let ((output (make-array length :element-type type))
          (expected (apply #'kernel-reference reference type length inputs)))
      (with-backend (backend)
        (is (eq output (apply kernel output (append inputs keys)))))
      (dotimes (i length)
        (is (close-enough-p (aref output i) (aref expected i) type))))))

(test kernels-across-backends
  (dolist (type '(single-float double-float))
    (dolist (length '(0 1 3 4 5 9 255 256 257 600))
      (let ((a (values-for length type 1))
            (b (values-for length type 2))
            (c (values-for length type 3))
            (d (values-for length type 4)))
        (check-kernel #'kernel-fma (lambda (a b c) (+ (* a b) c)) type length (list a b c))
        (check-kernel #'kernel-poly
                      (lambda (x) (- (* x x (coerce 2 type)) (/ x (coerce 4 type)) (coerce 1 type)))
                      type length (list a))
        (check-kernel #'kernel-negate (lambda (a b) (- (/ a b))) type length (list a b))
        (check-kernel #'kernel-deep
                      (lambda (a b c d) (/ (- (* a b) (* c d)) (+ a b c d)))
                      type length (list a b c d))
        (check-kernel #'kernel-constant (lambda () (coerce 3 type)) type length '())
        (check-kernel #'kernel-reciprocal (lambda (a) (/ (coerce 1 type) a)) type length (list a))))))

(test kernel-aliasing
  (dolist (backend (available-backends))
    (let ((a (values-for 300 'single-float 1))
          (b (values-for 300 'single-float 2))
          (c (values-for 300 'single-float 3)))
      (let ((expected (kernel-reference (lambda (a b c) (+ (* a b) c))
                                        'single-float 300 a b c)))
        (with-backend (backend)
          (kernel-fma a a b c))
        (dotimes (i 300)
          (is (close-enough-p (aref a i) (aref expected i) 'single-float)))))))

(test kernel-slices
  (dolist (backend (available-backends))
    (dolist (type '(single-float double-float))
      (let* ((a (values-for 40 type 1))
             (b (values-for 40 type 2))
             (c (values-for 40 type 3))
             (output (values-for 40 type 100))
             (before (copy-seq output)))
        (with-backend (backend)
          (kernel-fma output a b c :start 0 :end 9 :destination-start 5 :a-start 11 :c-start 20))
        (dotimes (i 40)
          (if (<= 5 i 13)
              (let ((k (- i 5)))
                (is (close-enough-p (aref output i)
                                    (+ (* (aref a (+ 11 k)) (aref b k)) (aref c (+ 20 k)))
                                    type)))
              (is (= (aref output i) (aref before i)))))
        (signals error (kernel-fma output a b c :start 0 :end 9 :b-start 32))))))

(eval-when (:compile-toplevel :load-toplevel :execute)
  (defun balanced-expression (depth)
    (if (zerop depth) 'a
        `(+ ,(balanced-expression (1- depth)) ,(balanced-expression (1- depth))))))

(test kernel-definition-errors
  (signals error (macroexpand-1 '(simd:define-kernel bad (a) (sin a))))
  (signals error (macroexpand-1 '(simd:define-kernel bad (a) (+ a z))))
  (signals error (macroexpand-1 '(simd:define-kernel bad (a) (+))))
  (finishes (macroexpand-1 `(simd:define-kernel fits (a) ,(balanced-expression 8))))
  (signals error (macroexpand-1 `(simd:define-kernel too-many
                                     ,(loop for i below 250 collect (intern (format nil "A~D" i)))
                                     0)))
  (finishes (macroexpand-1 `(simd:define-kernel spills (a) ,(balanced-expression 9)))))

(test kernel-spill-lowering
  (multiple-value-bind (code constants slots)
      (simd::lower-kernel (simd::parse-kernel-expression '(+ (* a b) c) '(a b c)))
    (is (equal '((:multiply 0 8 9) (:add 255 0 10)) code))
    (is (null constants))
    (is (zerop slots)))
  (dolist (depth '(8 9 10))
    (multiple-value-bind (code constants slots)
        (simd::lower-kernel (simd::parse-kernel-expression (balanced-expression depth) '(a)))
      (declare (ignore constants))
      (is (= (max 0 (- depth 8)) slots))
      (is (= (count :spill code :key #'first) (count :reload code :key #'first)))
      (is (= simd::+kernel-output+ (second (car (last code)))))))
  (multiple-value-bind (code constants slots)
      (simd::lower-kernel (simd::parse-kernel-expression
                          `(+ ,(balanced-expression 9) ,(balanced-expression 9)) '(a)))
    (declare (ignore constants))
    (is (= 2 slots))
    (is (> (count :spill code :key #'first) slots))))

(test kernel-spill-encoding
  (dolist (slot '(0 255 256 65535))
    (is (equal (list 7 3 (mod slot 256) (floor slot 256)
                     8 4 (mod slot 256) (floor slot 256))
               (simd::kernel-bytes `((:spill 3 ,slot 0) (:reload 4 ,slot 0))))))
  (dolist (slot '(-1 65536))
    (signals error (simd::kernel-bytes `((:spill 0 ,slot 0))))))

(macrolet ((define-spilling-kernel ()
             (labels ((sum-tree (depth)
                        (if (zerop depth) 'a
                            `(+ ,(sum-tree (1- depth)) ,(sum-tree (1- depth))))))
               (let ((sum (sum-tree 9)))
                 `(simd:define-kernel kernel-spilling (a) (- (/ 3 ,sum) (- ,sum)))))))
  (define-spilling-kernel))

(test spilling-kernels-across-backends
  (dolist (type '(single-float double-float))
    (let ((reference (lambda (a) (+ (/ (coerce 3 type) (* (coerce 512 type) a))
                                   (* (coerce 512 type) a)))))
      (dolist (length '(0 1 3 4 5 255 256 257 600))
        (check-kernel 'kernel-spilling reference type length (list (values-for length type 1))))
      (dolist (backend (available-backends))
        (let* ((a (values-for 620 type 1))
               (before (copy-seq a)))
          (with-backend (backend)
            (kernel-spilling a a :start 7 :end 608))
          (dotimes (i 620)
            (is (close-enough-p (aref a i)
                                (if (<= 7 i 607) (funcall reference (aref before i))
                                    (aref before i)) type))))
        (let* ((a (values-for 640 type 1))
               (out (values-for 630 type 100))
               (before (copy-seq out)))
          (with-backend (backend)
            (kernel-spilling out a :end 601 :destination-start 5 :a-start 11))
          (dotimes (i 630)
            (is (close-enough-p (aref out i)
                                (if (<= 5 i 605) (funcall reference (aref a (+ i 6)))
                                    (aref before i)) type))))))))

(test kernel-scratch-allocation-error
  (when simd::*native-available-p*
    (dolist (type '(:float :double))
      (cffi:with-foreign-object (output type)
        (setf (cffi:mem-ref output type) (if (eq type :float) 17.0 17.0d0))
        (let ((program (simd::%make-native-program
                        :code (cffi:null-pointer) :code-length 0
                        :f32-constants (cffi:null-pointer) :f64-constants (cffi:null-pointer)
                        :scratch-count (1- (ash 1 (* 8 (cffi:foreign-type-size :size)))))))
          (signals error (simd::call-native-kernel program type (cffi:null-pointer) output 1))
          (is (= 17 (cffi:mem-ref output type))))))))

#+ecl
(test interpreted-spilling-kernel
  (let ((sum (balanced-expression 9)))
    (eval `(simd:define-kernel interpreted-spilling (a) (- (/ 3 ,sum) (- ,sum)))))
  (dolist (type '(single-float double-float))
    (check-kernel 'interpreted-spilling
                  (lambda (a) (+ (/ (coerce 3 type) (* (coerce 512 type) a))
                                 (* (coerce 512 type) a)))
                  type 5 (list (values-for 5 type 1)))))

(simd:define-kernel kernel-sqrt (a) (sqrt a))
(simd:define-kernel kernel-abs (a) (abs a))
(simd:define-kernel kernel-min (a b c) (min a b c))
(simd:define-kernel kernel-max (a b c) (max a b c))
(simd:define-kernel kernel-true-fma (a b c) (simd:fma a b c))
(simd:define-kernel kernel-math (a b c) (max (abs (- a b)) (sqrt (min a c))))

(test kernel-math-operators
  (dolist (type '(single-float double-float))
    (dolist (length '(0 1 3 4 5 255 256 257 600))
      (let ((a (values-for length type 1))
            (b (values-for length type 2))
            (c (values-for length type 3)))
        (check-kernel #'kernel-sqrt #'sqrt type length (list a))
        (check-kernel #'kernel-abs #'abs type length
                      (list (make-array length :element-type type :initial-element (coerce -4 type))))
        (check-kernel #'kernel-min #'min type length (list a b c))
        (check-kernel #'kernel-max #'max type length (list a b c))
        (check-kernel #'kernel-true-fma (lambda (a b c) (+ (* a b) c))
                      type length (list a b c))
        (check-kernel #'kernel-math (lambda (a b c) (max (abs (- a b)) (sqrt (min a c))))
                      type length (list a b c))))))

(test kernel-new-operator-errors
  (dolist (expression '((sqrt) (sqrt a a) (abs a a) (min) (max)
                        (simd:fma a a) (simd:fma a a a a)))
    (signals error (macroexpand-1 `(simd:define-kernel bad (a) ,expression))))
  (dolist (backend (available-backends))
    (dolist (type '(single-float double-float))
      (let ((a (make-array 600 :element-type type :initial-element (coerce 4 type)))
            (out (values-for 600 type 10)))
        (dolist (index '(0 3 256 599))
          (setf (aref a index) (coerce -1 type))
          (with-backend (backend) (signals error (kernel-sqrt out a)))
          (setf (aref a index) (coerce 4 type)))))))

(test kernel-fma-single-rounding
  (dolist (type '(single-float double-float))
    (let* ((one (coerce 1 type))
           (epsilon (scale-float one (- 1 (float-digits one))))
           (tiny (if (eq type 'single-float) least-positive-single-float least-positive-double-float))
           (largest (if (eq type 'single-float) most-positive-single-float most-positive-double-float)))
      (dolist (case (list (list (+ one epsilon) (- one epsilon) (- one) (- (* epsilon epsilon)))
                         (list one one (/ epsilon 2) one)
                         (list (+ one epsilon) one (/ epsilon 2) (+ one (* 2 epsilon)))
                         (list tiny one (coerce 0 type) tiny)
                         (list tiny (coerce 0.5 type) tiny (* 2 tiny))
                         (list largest (coerce 2 type) (- largest) largest)))
        (destructuring-bind (a b c expected) case
          (is (= expected (simd:fma a b c)))
          (dolist (backend (available-backends))
            (dolist (length '(1 5 257))
              (let ((out (make-array length :element-type type)))
                (with-backend (backend)
                  (kernel-true-fma out
                                   (make-array length :element-type type :initial-element a)
                                   (make-array length :element-type type :initial-element b)
                                   (make-array length :element-type type :initial-element c)))
                (is (every (lambda (value) (= expected value)) out))))))))))

(test kernel-math-signed-zero
  (dolist (type '(single-float double-float))
    (dolist (backend (available-backends))
      (let* ((zero (coerce 0 type))
             (positive (make-array 5 :element-type type :initial-element zero))
             (negative (make-array 5 :element-type type :initial-element (- zero)))
             (one (make-array 5 :element-type type :initial-element (coerce 1 type)))
             (out (make-array 5 :element-type type)))
        (with-backend (backend)
          (kernel-sqrt out negative)
          (is (every (lambda (x) (minusp (float-sign x))) out))
          (kernel-abs out negative)
          (is (every (lambda (x) (plusp (float-sign x))) out))
          (kernel-min out negative positive positive)
          (is (every (lambda (x) (minusp (float-sign x))) out))
          (kernel-max out negative positive positive)
          (is (every (lambda (x) (minusp (float-sign x))) out))
          (kernel-true-fma out negative one negative)
          (is (every (lambda (x) (minusp (float-sign x))) out))
          (kernel-true-fma out negative one positive)
          (is (every (lambda (x) (plusp (float-sign x))) out)))))))

(macrolet ((define-math-spills ()
             (let ((a (balanced-expression 9))
                   (b (subst 'b 'a (balanced-expression 9)))
                   (c (subst 'c 'a (balanced-expression 9))))
               `(simd:define-kernel kernel-math-spills (a b c)
                  (simd:fma (sqrt ,a) (abs ,b) (min ,c ,a))))))
  (define-math-spills))

(test kernel-math-spilling-slices-and-aliases
  (dolist (type '(single-float double-float))
    (dolist (backend (available-backends))
      (let* ((a (make-array 620 :element-type type :initial-element (coerce 2 type)))
             (b (make-array 620 :element-type type :initial-element (coerce -1 type)))
             (c (make-array 620 :element-type type :initial-element (coerce 3 type)))
             (expected (coerce 17408 type)))
        (with-backend (backend)
          (kernel-math-spills a a b c :end 601 :destination-start 5 :a-start 11))
        (dotimes (i 620)
          (is (= (aref a i) (if (<= 5 i 605) expected (coerce 2 type)))))))))
