(in-package #:trivial-simd/tests)
(in-suite :trivial-simd)

(simd:define-kernel plan-softmax (x)
  (/ (exp (- x (simd:maximum x)))
     (simd:sum (exp (- x (simd:maximum x))))))
(simd:define-kernel plan-silu (x) (/ x (+ 1 (exp (- x)))))
(simd:define-kernel plan-rope (x) (+ (sin x) (cos x)))
(simd:define-kernel plan-exp (x) (exp x))
(simd:define-kernel plan-sin (x) (sin x))
(simd:define-kernel plan-cos (x) (cos x))
(simd:define-kernel plan-exp-sum (x) (simd:sum (exp x)))
(simd:define-kernel plan-nested-sum (x) (simd:sum (simd:sum x)))
(simd:define-kernel plan-nested-norm (x) (simd:nrm2 (simd:asum x)))
(simd:define-kernel plan-complex-unit (x) (/ x (simd:nrm2 x)))
(simd:define-kernel plan-centered-sum (x) (simd:sum (- x (simd:minimum x))))
(simd:define-kernel plan-normalize (x) (/ x (simd:sum x)))
(simd:define-kernel plan-arg (x) (+ x (simd:argmin x)))
(simd:define-kernel plan-selection (x) (simd:select (> x (simd:sum x)) (sin x) (cos x)))
(simd:define-kernel plan-input-softmax (x (q :type :s8) (s :repeat 3))
  (/ (exp (- (* x q s) (simd:maximum (* x q s))))
     (simd:sum (exp (- (* x q s) (simd:maximum (* x q s)))))))

(macrolet ((define-broadcasts ()
             `(progn ,@(loop for reducer in '(simd:sum simd:asum simd:nrm2 simd:minimum
                                              simd:maximum simd:argmin simd:argmax)
                             collect `(simd:define-kernel
                                          ,(intern (format nil "PLAN-BROADCAST-~A" reducer)) (x)
                                        (+ x (,reducer x)))))))
  (define-broadcasts))

(defun softmax-reference (x)
  (let* ((type (array-element-type x))
         (maximum (reduce #'max x))
         (values (map 'vector (lambda (value) (exp (- value maximum))) x))
         (sum (coerce 0 type)))
    (loop for value across values do (incf sum value))
    (map (list 'simple-array type (list (length x))) (lambda (value) (/ value sum)) values)))

(test nested-softmax-slices-and-aliasing
  (dolist (backend (available-backends))
    (with-backend (backend)
      (dolist (type '(single-float double-float))
        (dolist (n '(1 3 5 255 256 257 513))
          (let* ((x (make-array (+ n 7) :element-type type
                                :initial-contents (loop for i below (+ n 7) collect (coerce (+ 1000 (mod i 9)) type))))
                 (out (make-array (+ n 9) :element-type type :initial-element (coerce -1 type)))
                 (expected (softmax-reference (subseq x 3 (+ 3 n)))))
            (is (eq out (plan-softmax out x :start 2 :end (+ 2 n) :x-start 3 :destination-start 4)))
            (is (every #'floats-close-p expected (subseq out 4 (+ 4 n))))
            (is (= -1 (aref out 3)))
            (plan-softmax x x :start 3 :end (+ 3 n))
            (is (every #'floats-close-p expected (subseq x 3 (+ 3 n))))))))))

(test nested-reducers-and-types
  (dolist (backend (available-backends))
    (with-backend (backend)
      (dolist (type '(single-float double-float (signed-byte 8) (unsigned-byte 8)
                      (signed-byte 16) (unsigned-byte 16) (signed-byte 32) (unsigned-byte 32)
                      (signed-byte 64) (unsigned-byte 64)))
        (let* ((x (make-array 7 :element-type type :initial-contents (mapcar (lambda (value) (coerce value type)) '(1 2 3 4 5 6 7))))
               (out (make-array 7 :element-type type)))
          (dolist (reducer '(simd:sum simd:asum simd:minimum simd:maximum simd:argmin simd:argmax))
            (let* ((function (intern (format nil "PLAN-BROADCAST-~A" reducer)))
                   (value (funcall reducer x :start 2 :end 6)))
              (funcall function out x :start 2 :end 6)
              (dotimes (i 4)
                (is (= (+ (aref x (+ i 2)) value) (aref out (+ i 2)))))))
          (is (= (if (equal type '(signed-byte 8)) -60 196) (plan-nested-sum x)))
          (is (= 6 (plan-centered-sum x :start 2 :end 6)))))
      (dolist (type '(single-float double-float))
        (let ((x (make-array 3 :element-type type :initial-element (coerce 2 type)))
              (out (make-array 3 :element-type type)))
          (plan-broadcast-nrm2 out x)
          (is (floats-close-p (aref out 0) (+ (coerce 2 type) (sqrt (coerce 12 type)))))
          (is (floats-close-p (plan-nested-norm x) (sqrt (coerce 108 type))))))
      (let ((x (make-array 3 :element-type '(signed-byte 8) :initial-element 100))
            (out (make-array 3 :element-type '(signed-byte 8))))
        (plan-broadcast-sum out x)
        (is (= -112 (aref out 0))))
      (dolist (type '((complex single-float) (complex double-float)))
        (let* ((real-type (second type))
               (x (make-array 2 :element-type type :initial-element
                              (complex (coerce 3 real-type) (coerce 4 real-type))))
               (out (make-array 2 :element-type type)))
          (plan-broadcast-asum out x)
          (is (= (aref out 0) (complex (coerce 13 real-type) (coerce 4 real-type))))
          (plan-complex-unit out x)
          (is (floats-close-p (realpart (aref out 0)) (/ (coerce 3 real-type) (sqrt (coerce 50 real-type)))))
          (is (floats-close-p (imagpart (aref out 0)) (/ (coerce 4 real-type) (sqrt (coerce 50 real-type))))))))))

(test nested-empty-and-validation
  (dolist (backend (available-backends))
    (with-backend (backend)
      (let ((x (make-array 3 :element-type 'single-float :initial-element -1f0))
            (out (make-array 3 :element-type 'single-float :initial-element 9f0)))
        (is (eq out (plan-softmax out x :start 1 :end 1)))
        (is (= 0 (plan-centered-sum x :end 0)))
        (is (equalp out #(9f0 9f0 9f0)))
        (signals error (plan-softmax out x :end 4))
        (signals error (plan-softmax out x :rows 2 :row-length 2))
        (signals error (plan-softmax out x :row-length 1))
        (signals error (plan-softmax out x :rows 1 :row-length 3 :destination out))
        (is (equalp out #(9f0 9f0 9f0))))))
  (dolist (expression '((exp) (sin x x) (cos x x) (+ x (simd:count (> x 0)))
                        (+ x (simd:sum)) (simd:sum (> x 0))))
    (signals error (macroexpand-1 `(simd:define-kernel bad (x) ,expression))))
  (let ((integers (make-array 2 :element-type '(signed-byte 8) :initial-element 1))
        (complexes (make-array 2 :element-type '(complex single-float) :initial-element #c(1f0 0f0))))
    (signals error (plan-exp integers integers))
    (signals error (plan-sin complexes complexes))))

(test transcendental-values-and-fallback
  (dolist (type '(single-float double-float))
    (let* ((x (make-array 513 :element-type type
                              :initial-contents (loop for i below 513 collect (coerce (- (/ (mod i 23) 4) 3) type))))
           (out (make-array 513 :element-type type)))
      (dolist (backend (available-backends))
        (with-backend (backend)
          (dolist (pair (list (cons #'plan-exp #'exp) (cons #'plan-sin #'sin) (cons #'plan-cos #'cos)
                             (cons #'plan-silu (lambda (x) (/ x (+ (coerce 1 type) (exp (- x))))))))
            (funcall (car pair) out x)
            (dotimes (i 513)
              (is (floats-close-p (aref out i) (funcall (cdr pair) (aref x i)))))
          (is (floats-close-p (plan-exp-sum x) (reduce #'+ (map 'vector #'exp x))))))
      (with-backend (:native)
        (let ((simd::*native-kernel-transcendentals-p* nil))
          (plan-softmax out x)
          (is (every #'floats-close-p out (softmax-reference x)))))))))

(test nested-row-layouts-and-declarations
  (dolist (backend (available-backends))
    (with-backend (backend)
      (multiple-value-bind (x q scale) (input-data 18 'single-float 3)
        (let ((out (make-array 21 :element-type 'single-float :initial-element -1f0)))
          (plan-input-softmax out x q scale :rows 3 :row-length 5 :x-row-stride 6 :q-row-stride 6
                              :s-row-stride 2 :destination-start 15 :destination-row-stride -7)
          (dotimes (row 3)
            (let ((expected (softmax-reference
                             (input-reference x q scale 0 5 (* row 6) (* row 6) (* row 2) 3))))
              (is (every #'floats-close-p expected (subseq out (- 15 (* row 7)) (- 20 (* row 7)))))))
          (is (= -1 (aref out 0)))
          (signals error (plan-input-softmax out x q scale :rows 3 :row-length 5 :destination-row-stride 4))
          (signals error (plan-input-softmax x x q scale :rows 2 :row-length 5))
          (is (eq out (plan-softmax out x :rows 0 :row-length 5)))
          (is (eq out (plan-softmax out x :rows 3 :row-length 0))))
        (let ((out (make-array 3 :element-type 'single-float)))
          (plan-centered-sum x :rows 3 :row-length 6 :destination out)
          (is (equalp out #(0f0 0f0 0f0))))))))

(test nested-views-and-concurrency
  (dolist (backend (available-backends))
    (with-backend (backend)
      (dolist (block '(5 256))
        (let ((simd::*view-block-size* block))
          (with-view-memory
            (let* ((x (make-array 513 :element-type 'single-float
                                  :initial-contents (loop for i below 513 collect (float (mod i 9)))))
                   (view (mirror x))
                   (out (mirror (make-array 513 :element-type 'single-float))))
              (plan-softmax out view)
              (is (every #'floats-close-p (contents out) (softmax-reference x)))
              (plan-softmax view view)
              (is (every #'floats-close-p (contents view) (softmax-reference x)))))))))
  (let ((results (make-array 4)) (threads nil))
    (dotimes (i 4)
      (let ((slot i))
        (push (bt:make-thread
               (lambda ()
                 (with-backend (:native)
                   (let ((x (make-array 257 :element-type 'single-float :initial-element (float (1+ slot))))
                         (out (make-array 257 :element-type 'single-float)))
                     (dotimes (round 4) (plan-normalize out x))
                     (setf (aref results slot) (aref out 0)))))) threads)))
    (mapc #'bt:join-thread threads)
    (is (every (lambda (value) (floats-close-p value (/ 1f0 257))) results))))

(test nested-sharing-and-redefinition
  (multiple-value-bind (passes) (simd::kernel-pass-plan
                                '(/ (exp (- x (simd:maximum x)))
                                    (simd:sum (exp (- x (simd:maximum x))))) '(x))
    (is (= 2 (length passes))))
  (eval '(simd:define-kernel plan-redefined (x) (/ x (simd:sum x))))
  (let ((old (symbol-function 'plan-redefined))
        (x (make-array 3 :element-type 'single-float :initial-element 2f0))
        (out (make-array 3 :element-type 'single-float)))
    (eval '(simd:define-kernel plan-redefined (x) (+ x (simd:sum x))))
    (funcall old out x)
    (is (every (lambda (value) (floats-close-p value (/ 1f0 3))) out))
    (funcall 'plan-redefined out x)
    (is (equalp out #(8f0 8f0 8f0)))))

(test transcendental-finite-domains
  (dolist (type '(single-float double-float))
    (dolist (backend (available-backends))
      (with-backend (backend)
        (let* ((single (eq type 'single-float))
               (angles (make-array 5 :element-type type
                                     :initial-contents (list (coerce -0d0 type) (coerce 1 type)
                                                            (coerce 1000000 type)
                                                            (if single 1f30 1d300)
                                                            (if single most-positive-single-float most-positive-double-float))))
               (out (make-array 5 :element-type type)))
          (plan-sin out angles)
          (is (= -1 (float-sign (aref out 0))))
          (is (floats-close-p (aref out 1) (coerce 0.84147098480789650665d0 type)))
          (dotimes (i 5) (is (floats-close-p (aref out i) (sin (aref angles i)))))
          (plan-cos out angles)
          (is (= 1 (aref out 0)))
          (is (floats-close-p (aref out 1) (coerce 0.54030230586813971740d0 type)))
          (dotimes (i 5) (is (floats-close-p (aref out i) (cos (aref angles i)))))
          (let ((x (make-array 4 :element-type type
                                 :initial-contents (mapcar (lambda (value) (coerce value type))
                                                          (if single '(-80 0 1 80) '(-700 0 1 700))))))
            (plan-exp out x :end 4)
            (is (floats-close-p (aref out 2) (coerce 2.71828182845904523536d0 type)))
            (dotimes (i 4) (is (floats-close-p (aref out i) (exp (aref x i)))))))))))

(test nested-selection-and-spilling
  (dolist (backend (available-backends))
    (with-backend (backend)
      (let ((x (make-array 513 :element-type 'single-float :initial-element 0.5f0))
            (out (make-array 513 :element-type 'single-float)))
        (plan-selection out x)
        (is (every (lambda (value) (floats-close-p value (cos 0.5f0))) out))
        (eval `(simd:define-kernel plan-spilling (a)
                 (+ ,(balanced-expression 9) (simd:sum ,(balanced-expression 9)))))
        (funcall 'plan-spilling out x)
        (is (every (lambda (value) (= value (* 256 514))) out))))))

(simd:define-kernel plan-constant-math () (+ (exp 1) (sin 0) (cos 0)))

(test transcendental-constant-kernels
  (dolist (backend (available-backends))
    (with-backend (backend)
      (let ((out (make-array 8 :element-type 'single-float :initial-element -1f0)))
        (plan-constant-math out :rows 2 :row-length 3 :destination-row-stride 4)
        (dotimes (row 2)
          (dotimes (i 3)
            (is (floats-close-p (aref out (+ (* row 4) i)) (+ (exp 1f0) 1f0)))))
        (is (= -1 (aref out 3)))
        (is (= -1 (aref out 7)))
        (let ((simd::*native-kernel-transcendentals-p* nil))
          (plan-constant-math out)
          (is (every (lambda (value) (floats-close-p value (+ (exp 1f0) 1f0))) out)))))))
