(in-package #:trivial-simd/tests)

(in-suite :trivial-simd)

(simd:define-kernel reducer-values (a b) (- a b))
(simd:define-kernel reducer-minimum (a b) (simd:minimum (- a b)))
(simd:define-kernel reducer-maximum (a b) (simd:maximum (- a b)))
(simd:define-kernel reducer-argmin (a b) (simd:argmin (- a b)))
(simd:define-kernel reducer-argmax (a b) (simd:argmax (- a b)))
(simd:define-kernel reducer-asum (a b) (simd:asum (- a b)))
(simd:define-kernel reducer-nrm2 (a b) (simd:nrm2 (- a b)))
(simd:define-kernel reducer-min-of (a) (simd:minimum a))
(simd:define-kernel reducer-argmin-of (a) (simd:argmin a))
(simd:define-kernel reducer-asum-of (a) (simd:asum a))
(simd:define-kernel reducer-nrm2-of (a) (simd:nrm2 a))
(simd:define-kernel reducer-root-max (a) (simd:maximum (sqrt a)))
(simd:define-kernel reducer-selected-min (a b) (simd:minimum (simd:select (> a b) a b)))
(simd:define-kernel reducer-selected-asum (a b) (simd:asum (simd:select (> a b) a b)))
(simd:define-kernel reducer-selected-argmax (a b) (simd:argmax (simd:select (> a b) a b)))

(macrolet ((define-spilling-reducers ()
             (let ((expression (balanced-expression 9)))
               `(progn
                  (simd:define-kernel reducer-spilling-argmax (a) (simd:argmax ,expression))
                  (simd:define-kernel reducer-spilling-asum (a) (simd:asum ,expression))))))
  (define-spilling-reducers))

(defun reducer-reference-vector (a b &rest keys)
  (let ((values (make-array (length a) :element-type (array-element-type a))))
    (with-backend (:lisp)
      (apply #'reducer-values values a b keys))
    values))

(defun relative-close-p (actual expected tolerance)
  (<= (abs (- actual expected)) (* tolerance (abs expected))))

(defun float-tolerance (type)
  (if (eq type 'single-float) 1.0e-5 1.0d-12))

(test kernel-extremum-reducers-match-bulk
  (dolist (type *real-types*)
    (dolist (length '(0 1 2 3 5 33 255 256 257 513))
      (let* ((a (small-values length type))
             (b (reverse a))
             (values (reducer-reference-vector a b))
             (least (reference-argext values 0 length nil))
             (greatest (reference-argext values 0 length t)))
        (dolist (backend (available-backends))
          (with-backend (backend)
            (is (eql least (reducer-argmin a b)))
            (is (eql greatest (reducer-argmax a b)))
            (is (eql (and least (aref values least)) (reducer-minimum a b)))
            (is (eql (and greatest (aref values greatest)) (reducer-maximum a b)))))))))

(test kernel-reducer-slices-and-indexes
  (dolist (type *real-types*)
    (let* ((a (small-values 80 type))
           (b (reverse a)))
      (dolist (backend (available-backends))
        (with-backend (backend)
          (let ((values (reducer-reference-vector a b)))
            (is (eql (reference-argext values 3 40 t) (reducer-argmax a b :start 3 :end 40)))
            (is (eql (reference-argext values 3 40 nil) (reducer-argmin a b :start 3 :end 40)))
            (is (eql (aref values (reference-argext values 3 40 t))
                     (reducer-maximum a b :start 3 :end 40))))
          (let ((shifted (reducer-reference-vector a b :end 20 :a-start 5)))
            (is (eql (reference-argext shifted 0 20 t)
                     (reducer-argmax a b :end 20 :a-start 5))))
          (let ((shifted (reducer-reference-vector a b :end 20 :a-start 5 :b-start 7)))
            (is (eql (+ 7 (reference-argext shifted 0 20 nil))
                     (reducer-argmin a b :start 7 :end 27 :a-start 5 :b-start 7)))))))))

(test kernel-reducers-keep-the-first-extreme
  (dolist (type '(single-float double-float))
    (let ((zero (coerce 0 type)))
      (dolist (backend (available-backends))
        (with-backend (backend)
          (let ((positive-first (make-array 2 :element-type type
                                              :initial-contents (list zero (- zero))))
                (negative-first (make-array 2 :element-type type
                                              :initial-contents (list (- zero) zero))))
            (is (eql zero (reducer-min-of positive-first)))
            (is (eql (- zero) (reducer-min-of negative-first)))
            (is (eql 0 (reducer-argmin-of positive-first)))
            (is (eql 0 (reducer-argmin-of negative-first)))))))))

(test kernel-asum-reducer
  (dolist (type *real-types*)
    (dolist (length '(0 1 3 33 255 256 257 513))
      (let* ((a (small-values length type))
             (b (reverse a))
             (expected (with-backend (:lisp) (simd:asum (reducer-reference-vector a b)))))
        (dolist (backend (available-backends))
          (with-backend (backend)
            (let ((actual (reducer-asum a b)))
              (is (typep actual type))
              (if (floatp expected)
                  (is (close-enough-p actual expected type))
                  (is (= expected actual))))))))))

(test kernel-asum-wraps-integers
  (dolist (type '((signed-byte 8) (signed-byte 16) (signed-byte 32) (signed-byte 64)))
    (let* ((minimum (- (expt 2 (1- (integer-length (1- (expt 2 (second type))))))))
           (a (make-array 3 :element-type type :initial-contents (list minimum minimum 1)))
           (expected (with-backend (:lisp) (simd:asum a))))
      (dolist (backend (available-backends))
        (with-backend (backend)
          (is (= expected (reducer-asum-of a))))))))

(test kernel-nrm2-reducer
  (dolist (type '(single-float double-float))
    (dolist (length '(0 1 3 33 255 256 257 513))
      (let* ((a (small-values length type))
             (b (reverse a))
             (expected (with-backend (:lisp) (simd:nrm2 (reducer-reference-vector a b)))))
        (dolist (backend (available-backends))
          (with-backend (backend)
            (let ((actual (reducer-nrm2 a b)))
              (is (typep actual type))
              (is (close-enough-p actual expected type)))))))))

(test kernel-nrm2-avoids-overflow-and-underflow
  (dolist (type '(single-float double-float))
    (dolist (exponent (if (eq type 'single-float) '(-20 20) '(-200 200)))
      (let* ((value (scale-float (coerce 1 type) (round (* exponent (log 10 2)))))
             (a (make-array 6 :element-type type :initial-element value))
             (expected (* value (sqrt (coerce 6 type)))))
        (dolist (backend (available-backends))
          (with-backend (backend)
            (is (relative-close-p (reducer-nrm2-of a) expected (float-tolerance type)))))))))

(test kernel-complex-reducers
  (dolist (type '((complex single-float) (complex double-float)))
    (let* ((real (second type))
           (a (make-array 40 :element-type type
                             :initial-contents (loop for i below 40
                                                     collect (complex (coerce (- i 20) real)
                                                                      (coerce (mod i 7) real)))))
           (asum (reduce #'+ a :key #'abs))
           (nrm2 (sqrt (reduce #'+ a :key (lambda (z) (expt (abs z) 2))))))
      (dolist (backend (available-backends))
        (with-backend (backend)
          (is (typep (reducer-asum-of a) real))
          (is (relative-close-p (reducer-asum-of a) asum (float-tolerance real)))
          (is (relative-close-p (reducer-nrm2-of a) nrm2 (float-tolerance real)))
          (signals error (reducer-min-of a))
          (signals error (reducer-argmin-of a)))))))

(test kernel-reducers-on-selections-and-spills
  (dolist (type '(single-float double-float (signed-byte 16) (unsigned-byte 32)))
    (let* ((a (small-values 600 type))
           (b (reverse a))
           (chosen (make-array 600 :element-type type
                                   :initial-contents (map 'list (lambda (x y) (if (> x y) x y)) a b)))
           (largest (reference-argext a 0 600 t)))
      (dolist (backend (available-backends))
        (with-backend (backend)
          (is (eql (aref chosen (reference-argext chosen 0 600 nil)) (reducer-selected-min a b)))
          (is (eql (reference-argext chosen 0 600 t) (reducer-selected-argmax a b)))
          (is (eql largest (reducer-spilling-argmax a)))
          (is (= (with-backend (:lisp) (simd:asum chosen)) (reducer-selected-asum a b))))))))

(test kernel-spilling-asum-reducer
  (dolist (type '(single-float double-float))
    (let ((a (small-values 600 type)))
      (dolist (backend (available-backends))
        (with-backend (backend)
          (is (close-enough-p (reducer-spilling-asum a)
                              (* 512 (with-backend (:lisp) (simd:asum a)))
                              type)))))))

(test kernel-reducer-errors
  (dolist (definition '((simd:define-kernel bad (a) (simd:minimum))
                        (simd:define-kernel bad (a) (simd:argmax a a))
                        (simd:define-kernel bad () (simd:asum 3))
                        (simd:define-kernel bad (a) (simd:nrm2 (simd:asum a)))
                        (simd:define-kernel bad (a) (+ a (simd:argmin a)))
                        (simd:define-kernel bad (a) (simd:maximum (> a a)))))
    (signals error (macroexpand-1 definition)))
  (dolist (backend (available-backends))
    (with-backend (backend)
      (let ((a (small-values 8 '(signed-byte 8)))
            (floats (small-values 8 'single-float)))
        (signals error (reducer-nrm2-of a))
        (setf (aref floats 3) -1.0)
        (signals error (reducer-root-max floats))
        (signals error (reducer-argmin floats (small-values 7 'single-float)))
        (signals error (reducer-asum-of floats :start 5 :end 4))))))

#+ecl
(test ecl-eval-defined-reducers
  (eval '(simd:define-kernel interpreted-argmax (a b) (simd:argmax (- a b))))
  (eval '(simd:define-kernel interpreted-nrm2 (a) (simd:nrm2 a)))
  (dotimes (round 2)
    (dolist (type '(single-float double-float))
      (let* ((a (small-values 300 type))
             (b (reverse a))
             (values (reducer-reference-vector a b)))
        (dolist (backend (available-backends))
          (with-backend (backend)
            (is (eql (reference-argext values 0 300 t) (funcall 'interpreted-argmax a b)))
            (is (close-enough-p (funcall 'interpreted-nrm2 a)
                                (with-backend (:lisp) (simd:nrm2 a))
                                type))))))))
