(in-package #:trivial-simd/tests)

(in-suite :trivial-simd)

(defun nd-test-offsets (shape strides &optional (start 0))
  (if (null shape) (list start)
      (loop for index below (first shape)
            append (nd-test-offsets (rest shape) (rest strides)
                                   (+ start (* index (first strides)))))))

(defun nd-test-start (shape strides)
  (+ 2 (- (reduce #'min (nd-test-offsets shape strides)))))

(defun nd-test-gather (storage shape strides start)
  (make-array (reduce #'* shape :initial-value 1)
              :element-type (second (simd::numeric-type (simd::vector-type storage)))
              :initial-contents (mapcar (lambda (index) (simd::vector-ref storage index))
                                       (nd-test-offsets shape strides start))))

(test nd-broadcasting-and-layouts
  (dolist (backend (available-backends))
    (with-backend (backend)
      (let ((left (values-for 3 'single-float 1))
            (right (values-for 5 'single-float 10))
            (out (make-array 40 :element-type 'single-float :initial-element -1f0)))
        (is (eq out (simd:nd-add! out left right '(3 5)
                                 :destination-start 30 :destination-strides '(-10 2)
                                 :left-strides '(1 0) :right-strides '(0 1))))
        (loop for row below 3 do
          (loop for column below 5 do
            (is (= (+ 11 row column) (aref out (+ 30 (* -10 row) (* 2 column)))))))
      (let ((out (make-array 1 :element-type 'single-float)))
        (simd:nd-negate! out 3f0 nil)
        (is (= -3f0 (aref out 0))))))))

(test nd-operation-and-dtype-coverage
  (dolist (type (append (mapcar #'second simd::*numeric-types*)
                       '((complex single-float) (complex double-float))))
    (let ((complex (subtypep type 'complex)))
      (dolist (backend (available-backends))
        (with-backend (backend)
          (dolist (layout '((5 1) (1 3) (-10 2) (12 -2)))
            (let* ((shape '(3 5)) (start (nd-test-start shape layout))
                   (left (scrambled-vector type 60 1))
                   (right (copy-vector type 60 3))
                   (a (nd-test-gather left shape layout start))
                   (b (nd-test-gather right shape '(0 2) 2)))
              (dolist (pair (append '((simd:nd-add! simd:add!) (simd:nd-subtract! simd:subtract!)
                                     (simd:nd-multiply! simd:multiply!) (simd:nd-divide! simd:divide!))
                                   (unless complex '((simd:nd-min! simd:min!) (simd:nd-max! simd:max!)))))
                (let ((out (copy-vector type 60 0)) (expected (copy-vector type 15 0)))
                  (funcall (second pair) expected a b)
                  (check-views
                   (lambda (out left right)
                     (funcall (first pair) out left right shape
                              :destination-start start :destination-strides layout
                              :left-start start :left-strides layout :right-start 2 :right-strides '(0 2)))
                   (list out left right) :test #'numerically-close-p)
                  (funcall (first pair) out left right shape
                           :destination-start start :destination-strides layout
                           :left-start start :left-strides layout :right-start 2 :right-strides '(0 2))
                  (is (numerically-close-p (list (nd-test-gather out shape layout start)) (list expected)))))
              (dolist (pair '((simd:nd-negate! simd:negate!) (simd:nd-abs! simd:abs!)))
                (let* ((out-type (if (and complex (eq (first pair) 'simd:nd-abs!))
                                     (if (equal type '(complex single-float)) 'single-float 'double-float) type))
                       (out (copy-vector out-type 60 0)) (expected (copy-vector out-type 15 0)))
                  (funcall (second pair) expected a)
                  (funcall (first pair) out left shape :destination-start start :destination-strides layout
                           :input-start start :input-strides layout)
                  (is (numerically-close-p (list (nd-test-gather out shape layout start)) (list expected)))))
              (let ((mask (copy-vector '(unsigned-byte 8) 60 0))
                    (expected (copy-vector '(unsigned-byte 8) 15 0))
                    (out (copy-vector type 60 0)))
                (simd:compare! expected :eq a b)
                (simd:nd-compare! mask :eq left right shape :mask-start start :mask-strides layout
                                  :left-start start :left-strides layout :right-start 2 :right-strides '(0 2))
                (is (equalp expected (nd-test-gather mask shape layout start)))
                (simd:nd-select! out mask left right shape :destination-start start :destination-strides layout
                                 :mask-start start :mask-strides layout :true-start start :true-strides layout
                                 :false-start 2 :false-strides '(0 2))
                (is (equalp (nd-test-gather out shape layout start)
                            (map 'vector (lambda (mask a b) (if (zerop mask) b a)) expected a b)))))))))))

(test nd-unary-clamp-and-scalars
  (dolist (backend (available-backends))
    (with-backend (backend)
      (dolist (type '(single-float double-float (complex single-float) (complex double-float)))
        (let* ((input (copy-vector type 20 1)) (out (copy-vector type 20 0))
               (a (nd-test-gather input '(2 3) '(6 -2) 4)) (expected (copy-vector type 6 0)))
          (dolist (pair '((simd:nd-sqrt! simd:sqrt!) (simd:nd-reciprocal! simd:reciprocal!)))
            (funcall (second pair) expected a)
            (funcall (first pair) out input '(2 3) :input-start 4 :input-strides '(6 -2)
                     :destination-strides '(3 1))
            (is (numerically-close-p (list (subseq out 0 6)) (list expected)))
            (funcall (second pair) expected (subseq input 0 6))
            (funcall (first pair) out input '(2 3))
            (is (numerically-close-p (list (subseq out 0 6)) (list expected))))))
      (let ((input (values-for 20 'single-float 0)) (out (values-for 20 'single-float 0)))
        (simd:nd-clamp! out input 2f0 8f0 '(2 3) :input-strides '(6 2) :destination-strides '(3 1))
        (is (equalp '(2 2 4 6 8 8) (coerce (subseq out 0 6) 'list)))
        (simd:nd-subtract! out 20f0 input '(2 3) :right-strides '(6 2))
        (is (equalp '(20 18 16 14 12 10) (coerce (subseq out 0 6) 'list)))
        (simd:nd-compare! (make-array 6 :element-type '(unsigned-byte 8)) :gt 3f0 input '(2 3)
                          :right-strides '(6 2))))))

(test nd-conversions
  (dolist (backend (available-backends))
    (with-backend (backend)
      (dolist (source (append (mapcar #'second simd::*numeric-types*)
                             '((complex single-float) (complex double-float))))
        (dolist (target (append (mapcar #'second simd::*numeric-types*)
                               '((complex single-float) (complex double-float))))
          (let* ((input (make-array 20 :element-type source :initial-element (coerce 3 source)))
                 (out (make-array 20 :element-type target))
                 (reference (make-array 6 :element-type target)))
            (simd:convert! reference (make-array 6 :element-type source :initial-element (coerce 3 source)))
            (simd:nd-convert! out input '(2 3) :input-start 8 :input-strides '(-6 2)
                              :destination-start 1 :destination-strides '(6 2))
            (is (equalp reference (nd-test-gather out '(2 3) '(6 2) 1))))))
      (dolist (rounding '(:nearest-even :truncate :floor :ceiling))
        (dolist (source '(nil :f16 :bf16))
          (dolist (target '(nil :f16 :bf16))
            (let* ((float (make-array 20 :element-type 'double-float :initial-element 1.003d0))
                   (input (if source (make-array 20 :element-type '(unsigned-byte 16)) float))
                   (out (make-array 20 :element-type (if target '(unsigned-byte 16) 'double-float)))
                   (expected (make-array 6 :element-type (array-element-type out))))
              (when source (simd:convert! input float :destination-encoding source))
              (simd:convert! expected (nd-test-gather input '(2 3) '(6 -2) 4)
                             :input-encoding source :destination-encoding target :rounding rounding)
              (simd:nd-convert! out input '(2 3) :input-start 4 :input-strides '(6 -2)
                                :destination-strides '(3 1) :input-encoding source
                                :destination-encoding target :rounding rounding)
              (is (equalp expected (subseq out 0 6))))))))))

(test nd-aliases-and-validation
  (dolist (backend (available-backends))
    (with-backend (backend)
      (let ((storage (values-for 40 'single-float 0)))
        (simd:nd-add! storage storage 1f0 '(2 3) :destination-start 3 :destination-strides '(3 1)
                      :left-start 0 :left-strides '(3 1))
        (is (equalp '(1 2 3 4 5 6) (coerce (subseq storage 3 9) 'list)))
        (simd:nd-add! storage storage 1f0 '(2 3) :left-start 2 :left-strides '(0 0))
        (is (every (lambda (value) (= value 3f0)) (subseq storage 0 6))))
      (with-view-memory
        (let* ((storage (mirror (values-for 40 'single-float 0)))
               (other (simd:make-vector-view (simd:vector-view-pointer storage) :f32 40)))
          (simd:nd-add! other storage 1f0 '(2 3) :destination-start 0 :destination-strides '(3 1)
                        :left-start 3 :left-strides '(3 1))
          (is (equalp '(4 5 6 7 8 9) (coerce (subseq (contents other) 0 6) 'list)))))
      (let ((out (values-for 20 'single-float 0)) (input (values-for 20 'single-float 1)))
        (dolist (keys '((:destination-strides (0 0)) (:destination-strides (2 3))
                        (:left-start -1) (:left-strides (1)) (:left-strides (1 999))
                        (:destination-start 19) (:left-strides (1 9223372036854775808))))
          (signals error (apply #'simd:nd-add! out input 1f0 '(4 3) keys))
          (is (equalp out (values-for 20 'single-float 0))))
        (signals error (simd:nd-compare! out :bogus input input '(0 3)))
        (signals error (simd:nd-convert! out input '(0 3) :rounding :bogus))
        (simd:nd-add! out input 1f0 '(0 3) :destination-start 100 :destination-strides '(0 0))
        (simd:nd-add! out input 1f0 '(2 3) :destination-strides '(3 2))
        (is (= 7f0 (aref out 7)))))))

(test nd-native-dispatch-and-fallback
  (when simd::*native-nd-available-p*
    (let ((original (symbol-function 'simd::%native-nd-execute)) (calls 0))
      (unwind-protect
           (progn
             (setf (symbol-function 'simd::%native-nd-execute)
                   (lambda (&rest arguments)
                     (incf calls)
                     #+sbcl (sb-ext:gc)
                     #+ccl (ccl:gc)
                     #+ecl (ext:gc)
                     (apply original arguments)))
             (with-backend (:native)
               (let ((out (values-for 1000 'single-float 0)) (input (values-for 1000 'single-float 0)))
                 (simd:nd-add! out input 1f0 '(20 10) :destination-strides '(30 2) :left-strides '(30 2))
                 (is (= 1 calls))
                 (let ((simd::*native-nd-available-p* nil))
                   (simd:nd-add! out input 1f0 '(20 10) :destination-strides '(30 2) :left-strides '(30 2)))
                 (is (= 1 calls)))))
        (setf (symbol-function 'simd::%native-nd-execute) original)))))

(test nd-encoded-bit-patterns
  (let ((input (make-array 65536 :element-type '(unsigned-byte 16))))
    (dotimes (index 65536) (setf (aref input index) index))
    (dolist (backend (available-backends))
      (with-backend (backend)
        (dolist (source '(:f16 :bf16))
          (dolist (target '(:f16 :bf16))
            (let ((expected (make-array 65536 :element-type '(unsigned-byte 16)))
                  (out (make-array 131072 :element-type '(unsigned-byte 16) :initial-element 0)))
              (simd:convert! expected input :input-encoding source :destination-encoding target)
              (simd:nd-convert! out input '(256 256) :input-start 65535 :input-strides '(-256 -1)
                                :destination-strides '(512 2) :input-encoding source :destination-encoding target)
              (is (loop for index below 65536 always (= (aref out (* 2 index)) (aref expected (- 65535 index)))))
              (is (loop for index below 65536 always (zerop (aref out (1+ (* 2 index)))))))))))))

(test nd-does-not-stage-strided-operands
  (let* ((names '(simd::gather-slice simd::scatter-slice simd::stage-in simd::stage-out))
         (originals (mapcar (lambda (name) (cons name (symbol-function name))) names)))
    (unwind-protect
         (progn
           (dolist (name names)
             (setf (symbol-function name) (lambda (&rest arguments)
                                           (declare (ignore arguments)) (error "Unexpected staging"))))
           (dolist (backend (available-backends))
             (with-backend (backend)
               (let ((input (values-for 100 'single-float 1))
                     (out (values-for 100 'single-float 0)))
                 (simd:nd-add! out input 1f0 '(2 3) :destination-strides '(1 4) :left-strides '(20 -2)
                               :left-start 4)
                 (is (= 26f0 (aref out 1)))))))
      (dolist (entry originals) (setf (symbol-function (car entry)) (cdr entry))))))

(defun nd-inference-reference (operation x)
  (let ((one (float 1 x)))
    (ecase operation
      (:exp (exp x)) (:sin (sin x)) (:cos (cos x))
      (:silu (* x (if (minusp x) (/ (exp x) (+ one (exp x)))
                      (/ one (+ one (exp (- x)))))))
      (:gelu (* (float 0.5 x) x
                (+ one (tanh (* (float (sqrt (/ 2d0 pi)) x)
                               (+ x (* (float 0.044715d0 x) x x x))))))))))

(defun nd-inference-operations ()
  '((:exp simd:nd-exp!) (:sin simd:nd-sin!) (:cos simd:nd-cos!)
    (:silu simd:nd-silu!) (:gelu simd:nd-gelu!)))

(test nd-inference-math-backends-and-layouts
  (dolist (backend (available-backends))
    (with-backend (backend)
      (dolist (type '(single-float double-float))
        (dolist (spec (nd-inference-operations))
          (destructuring-bind (operation function) spec
            (let ((input (make-array 8 :element-type type :initial-contents
                                      (mapcar (lambda (x) (coerce x type)) '(-30 -2 -1 0 1 2 3 30))))
                  (out (make-array 16 :element-type type :initial-element (coerce -99 type))))
              (dolist (layout '(((3 -1) 2) ((1 2) 0) ((0 1) 0)))
                (destructuring-bind (strides start) layout
                  (let ((expected (map 'vector (lambda (x) (nd-inference-reference operation x))
                                       (nd-test-gather input '(2 3) strides start))))
                    (check-views
                     (lambda (out input)
                       (funcall function out input '(2 3) :destination-start 1
                                :destination-strides '(1 4) :input-start start :input-strides strides))
                     (list out input) :test #'numerically-close-p)
                    (is (eq out (funcall function out input '(2 3) :destination-start 1
                                         :destination-strides '(1 4) :input-start start :input-strides strides)))
                    (is (every #'floats-close-p (nd-test-gather out '(2 3) '(1 4) 1) expected))
                    (is (= -99 (aref out 0)))
                    (is (= -99 (aref out 3))))))
              (let ((expected (map 'vector (lambda (x) (nd-inference-reference operation x)) input)))
                (funcall function out input '(8))
                (is (every #'floats-close-p (subseq out 0 8) expected))
                (funcall function input input '(8))
                (is (every #'floats-close-p input expected)))
              (funcall function out (coerce 1 type) nil)
              (is (floats-close-p (aref out 0) (nd-inference-reference operation (coerce 1 type))))
              (is (eq out (funcall function out input '(0 3))))
              (let ((simd::*native-nd-inference-math-p* nil))
                (let ((expected (map 'vector (lambda (x) (nd-inference-reference operation x))
                                     (subseq input 0 6))))
                  (funcall function out input '(2 3) :destination-start 10 :destination-strides '(-6 2))
                  (is (every #'floats-close-p (nd-test-gather out '(2 3) '(-6 2) 10) expected)))))
            (let* ((input (make-array 10 :element-type type :initial-contents
                                        (loop for i below 10 collect (coerce (/ (- i 5) 2) type))))
                   (expected (map 'vector (lambda (x) (nd-inference-reference operation x)) (subseq input 0 6))))
              (funcall function input input '(2 3) :destination-start 2)
              (is (every #'floats-close-p (subseq input 2 8) expected)))
            (let* ((input (make-array 6 :element-type type :initial-contents
                                       (mapcar (lambda (x) (coerce x type)) '(-2 -1 0 1 2 3))))
                   (expected (map 'vector (lambda (x) (nd-inference-reference operation x))
                                  (nd-test-gather input '(2 3) '(0 1) 0))))
              (funcall function input input '(2 3) :input-strides '(0 1))
              (is (every #'floats-close-p input expected)))))))))

(test nd-inference-math-validation
  (dolist (spec (nd-inference-operations))
    (let ((function (second spec))
          (out (make-array 6 :element-type 'single-float :initial-element -99f0))
          (input (make-array 6 :element-type 'single-float :initial-element 1f0)))
      (dolist (keys '((:destination-strides (0 1)) (:input-start -1)
                      (:input-strides (1)) (:input-strides (3 99))))
        (signals error (apply function out input '(2 3) keys))
        (is (every (lambda (x) (= -99 x)) out)))
      (signals error (funcall function out (make-array 6 :element-type 'double-float) '(2 3)))
      (is (every (lambda (x) (= -99 x)) out))
      (dolist (type '((signed-byte 8) (unsigned-byte 16) (complex single-float) (complex double-float)))
        (let ((storage (make-array 0 :element-type type)))
          (signals error (funcall function storage storage '(0))))))))

(test nd-inference-large-angles
  (dolist (backend (available-backends))
    (with-backend (backend)
      (dolist (type '(single-float double-float))
        (let ((input (make-array 4 :element-type type :initial-contents
                                  (mapcar (lambda (x) (coerce x type)) '(-1d20 -1d6 1d6 1d20))))
              (out (make-array 4 :element-type type)))
          (dolist (spec '((simd:nd-sin! sin) (simd:nd-cos! cos)))
            (funcall (first spec) out input '(4))
            (is (every #'floats-close-p out (map 'vector (second spec) input)))))))))

#+sbcl
(test nd-inference-native-capability-dispatch
  (when (and simd::*native-nd-available-p* simd::*native-nd-inference-math-p*)
    (let ((original (symbol-function 'simd::%native-nd-execute)) (calls 0))
      (unwind-protect
           (progn
             (setf (symbol-function 'simd::%native-nd-execute)
                   (lambda (&rest arguments) (incf calls) (apply original arguments)))
             (with-backend (:native)
               (dolist (spec (nd-inference-operations))
                 (let ((input (make-array 6 :element-type 'single-float :initial-element 1f0))
                       (out (make-array 6 :element-type 'single-float))
                       (before calls))
                   (funcall (second spec) out input '(2 3))
                   (is (= (1+ before) calls))
                   (let ((simd::*native-nd-inference-math-p* nil))
                     (funcall (second spec) out input '(2 3)))
                   (is (= (1+ before) calls))))))
        (setf (symbol-function 'simd::%native-nd-execute) original)))))
