(in-package #:trivial-simd/tests)

(in-suite :trivial-simd)

(defun available-backends ()
  (append '(:lisp)
          (when simd::*native-available-p* '(:native :native-copy))
          (when simd::*sbcl-simd-available-p* '(:sbcl))))

(defmacro with-backend ((backend) &body body)
  `(let* ((backend ,backend)
          (simd::*backend* (if (eq backend :native-copy) :native backend))
          (simd::*native-array-access*
            (if (eq backend :native-copy) :copy simd::*native-array-access*)))
     ,@body))

(defun values-for (length type offset)
  (make-array length :element-type type
              :initial-contents
              (loop for i below length collect (coerce (+ i offset) type))))

(defun close-enough-p (actual expected type)
  (let ((tolerance (if (eq type 'single-float) 1.0e-5 1.0d-12)))
    (<= (abs (- actual expected)) (* tolerance (max 1 (abs expected))))))

(test backend-is-reported
  (is (member (simd:backend) (remove :native-copy (available-backends)))))

(test arithmetic-across-backends
  (dolist (type '(single-float double-float))
    (dolist (length '(0 1 2 3 4 5 7 8 9 17 257))
      (let ((left (values-for length type 1))
            (right (values-for length type 2)))
        (dolist (operation '(simd:add! simd:subtract! simd:multiply! simd:divide!))
          (let* ((reference (make-array length :element-type type))
                 (function (symbol-function operation)))
            (let ((simd::*backend* :lisp))
              (funcall function reference left right))
            (dolist (backend (available-backends))
              (let ((output (make-array length :element-type type)))
                (with-backend (backend)
                  (is (eq output (funcall function output left right))))
                (dotimes (i length)
                  (is (close-enough-p (aref output i) (aref reference i) type)))))))))))

(test destination-may-alias-an-input
  (dolist (backend (available-backends))
    (dolist (type '(single-float double-float))
      (dolist (operation '(simd:add! simd:subtract! simd:multiply! simd:divide!))
        (let* ((left (values-for 9 type 1))
               (right (values-for 9 type 2))
               (reference (make-array 9 :element-type type)))
          (let ((simd::*backend* :lisp))
            (funcall operation reference left right))
          (with-backend (backend)
            (funcall operation left left right))
          (dotimes (i 9)
            (is (close-enough-p (aref left i) (aref reference i) type)))
          (let ((left (values-for 9 type 1))
                (right (values-for 9 type 2)))
            (with-backend (backend)
              (funcall operation right left right))
            (dotimes (i 9)
              (is (close-enough-p (aref right i) (aref reference i) type)))))))))

(test reductions-across-backends
  (dolist (type '(single-float double-float))
    (dolist (length '(0 1 2 3 4 5 8 9 17 1001))
      (let* ((left (values-for length type 1))
             (right (values-for length type 2))
             (reference-sum (let ((simd::*backend* :lisp)) (simd:sum left)))
             (reference-dot (let ((simd::*backend* :lisp)) (simd:dot left right))))
        (dolist (backend (available-backends))
          (with-backend (backend)
            (is (close-enough-p (simd:sum left) reference-sum type))
            (is (close-enough-p (simd:dot left right) reference-dot type))))))))

(test invalid-vectors
  (let ((single (values-for 4 'single-float 1))
        (double (values-for 4 'double-float 1))
        (short (values-for 3 'single-float 1)))
    (signals error (simd:add! single single short))
    (signals error (simd:add! single single double))
    (signals type-error (simd:sum #(1 2 3)))
    (signals error (simd:dot single short))))

(defun expected-slice (operation type count left-offset right-offset left right)
  (let ((function (ecase operation
                    (simd:add! #'+) (simd:subtract! #'-)
                    (simd:multiply! #'*) (simd:divide! #'/))))
    (loop for i below count
          collect (funcall function
                           (aref left (+ left-offset i))
                           (aref right (+ right-offset i))))))

(test slices-across-backends
  (dolist (backend (available-backends))
    (dolist (type '(single-float double-float))
      (dolist (operation '(simd:add! simd:subtract! simd:multiply! simd:divide!))
        (dolist (case '((3 20 nil nil nil) (0 9 5 0 11) (1 6 7 3 2) (0 0 4 4 4)))
          (destructuring-bind (start end destination-start left-start right-start) case
            (let* ((left (values-for 40 type 1))
                   (right (values-for 40 type 2))
                   (output (values-for 40 type 100))
                   (before (copy-seq output))
                   (count (- end start))
                   (d (or destination-start start))
                   (l (or left-start start))
                   (r (or right-start start))
                   (expected (expected-slice operation type count l r left right)))
              (with-backend (backend)
                (is (eq output (funcall operation output left right
                                        :start start :end end
                                        :destination-start destination-start
                                        :left-start left-start
                                        :right-start right-start))))
              (dotimes (i 40)
                (if (<= d i (+ d count -1))
                    (is (close-enough-p (aref output i) (elt expected (- i d)) type))
                    (is (= (aref output i) (aref before i))))))))))))

(test slice-reductions-across-backends
  (dolist (backend (available-backends))
    (dolist (type '(single-float double-float))
      (let ((left (values-for 40 type 1))
            (right (values-for 40 type 2)))
        (with-backend (backend)
          (is (close-enough-p (simd:sum left :start 3 :end 20)
                              (loop for i from 3 below 20 sum (aref left i)) type))
          (is (close-enough-p (simd:sum left :start 2 :end 11 :input-start 20)
                              (loop for i from 20 below 29 sum (aref left i)) type))
          (is (close-enough-p (simd:dot left right :start 1 :end 10 :right-start 30)
                              (loop for i from 1 below 10
                                    sum (* (aref left i) (aref right (+ 29 i)))) type))
          (is (zerop (simd:sum left :start 5 :end 5))))))))

(test invalid-slices
  (let ((a (values-for 8 'single-float 1))
        (b (values-for 8 'single-float 1)))
    (signals error (simd:add! a a b :start 4 :end 2))
    (signals error (simd:add! a a b :start -1 :end 4))
    (signals error (simd:add! a a b :start 0 :end 9))
    (signals error (simd:add! a a b :start 0 :end 4 :right-start 5))
    (signals error (simd:add! a a b :start 0 :end 4 :left-start -1))
    (signals error (simd:sum a :start 0 :end 4 :input-start 5))
    (signals error (simd:add! a a (values-for 9 'single-float 1)))))

(test native-copy-round-trips
  (dolist (type '(single-float double-float))
    (dolist (length '(0 1 5 257 1024))
      (let* ((input (values-for length type -4))
             (output (values-for length type 100))
             (foreign (simd::foreign-type input)))
        (cffi:with-foreign-object (pointer foreign (max 1 length))
          (simd::copy-to-foreign input pointer foreign 0 length)
          (simd::copy-from-foreign pointer output foreign 0 length)
          (is (equalp input output))
          (when (> length 1)
            (fill output (coerce 100 type))
            (simd::copy-from-foreign (simd::element-pointer pointer foreign 1)
                                     output foreign 1 (1- length))
            (is (= 100 (aref output 0)))
            (loop for index from 1 below length
                  do (is (= (aref input index) (aref output index)))))
          (let ((before (copy-seq output)))
            (simd::copy-from-foreign pointer output foreign length 0)
            (is (equalp before output))))))))

(test integer-slice-indices
  (let ((a (values-for 8 'single-float 1))
        (out (values-for 8 'single-float -1)))
    (dolist (backend (available-backends))
      (with-backend (backend)
        (dolist (keys '((:start 0.0 :end 4) (:start 0 :end 4.0)
                        (:end 4 :left-start 0.5) (:end 4 :right-start 0.5)
                        (:end 4 :destination-start 0.5)))
          (signals error (apply #'simd:add! out a a keys)))
        (signals error (simd:sum a :end 4 :input-start 0.5))
        (signals error (simd:dot a a :end 4 :right-start 0.5))))))

(test scalar-bulk-operations
  (dolist (backend (available-backends))
    (dolist (type '(single-float double-float))
      (dolist (length '(0 1 2 3 4 5 17 257))
        (let* ((input (values-for length type 1))
               (scalar (coerce 2 type)))
          (dolist (operation '((simd:add! . +) (simd:subtract! . -)
                               (simd:multiply! . *) (simd:divide! . /)))
            (dolist (scalar-left '(nil t))
              (let ((out (make-array length :element-type type)))
                (with-backend (backend)
                  (is (eq out (funcall (symbol-function (car operation)) out
                                       (if scalar-left scalar input)
                                       (if scalar-left input scalar)))))
                (dotimes (i length)
                  (is (close-enough-p
                       (aref out i)
                       (funcall (symbol-function (cdr operation))
                                (if scalar-left scalar (aref input i))
                                (if scalar-left (aref input i) scalar)) type)))))))))))

(test scalar-bulk-slices-and-errors
  (dolist (backend (available-backends))
    (let ((x (values-for 12 'single-float 1))
          (out (make-array 12 :element-type 'single-float :initial-element -1.0)))
      (with-backend (backend)
        (is (eq out (simd:subtract! out 20.0 x :start 0 :end 4
                                    :destination-start 6 :right-start 2)))
        (dotimes (i 12)
          (is (= (aref out i) (if (<= 6 i 9) (- 20 (aref x (- i 4))) -1))))
        (signals error (simd:add! out x 2.0 :right-start 0))
        (signals error (simd:add! out 1.0 2.0))
        (signals error (simd:add! out x 2.0d0))
        (signals error (simd:add! out x 2.0 :end 13))))))

(test scale-axpy-and-bulk-fma
  (dolist (backend (available-backends))
    (dolist (type '(single-float double-float))
      (let* ((a (coerce 2 type))
             (x (values-for 9 type 1))
             (y (values-for 9 type 11))
             (before (copy-seq y))
             (out (make-array 9 :element-type type :initial-element (coerce -1 type))))
        (with-backend (backend)
          (is (eq x (simd:scale! x a :start 2 :end 7)))
          (dotimes (i 9)
            (is (= (aref x i) (* (if (<= 2 i 6) a (coerce 1 type))
                                   (coerce (1+ i) type)))))
          (is (eq y (simd:axpy! y a x :start 0 :end 4 :y-start 5 :x-start 1)))
          (dotimes (i 9)
            (is (= (aref y i)
                   (if (<= 5 i 8) (+ (* a (aref x (- i 4))) (aref before i))
                       (aref before i)))))
          (is (eq out (simd:fma! out x a y)))
          (dotimes (i 9)
            (is (= (aref out i) (simd:fma (aref x i) a (aref y i)))))
          (is (eq out (simd:fma! out a a a :start 2 :end 5)))
          (dotimes (i 9)
            (when (<= 2 i 4) (is (= (aref out i) (* 3 a)))))
          (simd:fma! out x a y :start 0 :end 3
                     :destination-start 6 :x-start 1 :z-start 4)
          (dotimes (i 3)
            (is (= (aref out (+ 6 i))
                   (simd:fma (aref x (+ 1 i)) a (aref y (+ 4 i))))))
          (let ((same (values-for 9 type 1)))
            (simd:axpy! same a same)
            (dotimes (i 9)
              (is (= (aref same i) (* (+ (coerce 1 type) a)
                                        (coerce (1+ i) type))))))
          (signals error (simd:fma! out x a y :y-start 0))
          (signals error (simd:scale! x 2))
          (signals error (simd:axpy! y 2 x)))))))

(test bulk-fma-single-rounding-and-alias
  (dolist (backend (available-backends))
    (dolist (type '(single-float double-float))
      (let* ((one (coerce 1 type))
             (epsilon (scale-float one (- 1 (float-digits one))))
             (a (+ one epsilon))
             (b (- one epsilon))
             (c (- one))
             (expected (simd:fma a b c))
             (x (make-array 9 :element-type type :initial-element a))
             (out (make-array 9 :element-type type :initial-element c)))
        (with-backend (backend)
          (simd:fma! out x b out)
          (is (every (lambda (value) (= expected value)) out))
          (simd:fma! x x b c)
          (is (every (lambda (value) (= expected value)) x)))))))

(test whole-vector-calls-match-explicit-slices
  (dolist (backend (available-backends))
    (dolist (type '(single-float double-float (signed-byte 32) (unsigned-byte 8)))
      (dolist (length '(0 1 4 17))
        (let ((left (values-for length type 1))
              (right (values-for length type 2))
              (scalar (coerce 3 type)))
          (with-backend (backend)
            (dolist (operation '(simd:add! simd:subtract! simd:multiply!))
              (flet ((call (&rest keys)
                       (let ((out (make-array length :element-type type)))
                         (apply operation out left right keys)
                         out)))
                (is (equalp (call) (call :start 0)))))
            (flet ((call (&rest keys)
                     (let ((out (make-array length :element-type type)))
                       (apply #'simd:add! out left scalar keys)
                       (apply #'simd:multiply! out scalar out keys)
                       out)))
              (is (equalp (call) (call :start 0))))
            (flet ((call (&rest keys)
                     (let ((y (copy-seq left)))
                       (apply #'simd:scale! y scalar keys)
                       (apply #'simd:axpy! y scalar right keys)
                       y)))
              (is (equalp (call) (call :start 0))))
            (is (eql (simd:sum left) (simd:sum left :start 0)))
            (is (eql (simd:dot left right) (simd:dot left right :start 0)))))))))

(test whole-vector-calls-still-validate
  (let ((short (make-array 3 :element-type 'single-float))
        (long (make-array 4 :element-type 'single-float))
        (double (make-array 4 :element-type 'double-float)))
    (signals error (simd:add! long long short))
    (signals error (simd:add! long long double))
    (signals error (simd:add! long long 1d0))
    (signals error (simd:scale! long 1d0))
    (signals error (simd:axpy! long 1f0 short))
    (signals error (simd:dot long short))
    (signals error (simd:dot long double))))
