(require :asdf)

(defparameter *diagnostic-backend*
  (intern (string-upcase (or (uiop:getenv "TRIVIAL_SIMD_ISOLATION_BACKEND") "native")) :keyword))
(defparameter *diagnostic-workers*
  (parse-integer (or (uiop:getenv "TRIVIAL_SIMD_ISOLATION_WORKERS") "4")))
(unless (and (member *diagnostic-backend* '(:native :lisp :plain))
             (member *diagnostic-workers* '(1 4)))
  (error "Choose native/lisp/plain and 1/4 workers"))

(unless (eq *diagnostic-backend* :plain)
  (load (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname)))
  (asdf:initialize-source-registry
   `(:source-registry
     (:directory ,(or (uiop:getenv "TRIVIAL_SIMD_DIAGNOSTIC_ROOT")
                      (merge-pathnames "../" (uiop:pathname-directory-pathname *load-truename*))))
     :inherit-configuration))
  (asdf:load-system "trivial-simd")
  (eval (read-from-string
         "(trivial-simd:define-kernel diagnostic-concurrent (a b)
             (trivial-simd:select (= a (/ (trivial-simd:sum a) (trivial-simd:sum 1)))
                                  (/ a (trivial-simd:nrm2 a)) b))")))

(defun diagnostic-value (slot real)
  (complex (coerce (1+ slot) real) (coerce 2 real)))

(defun diagnostic-work (slot real)
  (declare (notinline + - * / abs sqrt))
  (let ((z (diagnostic-value slot real)))
    (if (eq *diagnostic-backend* :plain)
        (let ((value z))
          (dotimes (i 10000)
            (setf value (/ (+ value z) 2)))
          (= value z))
        (let* ((type (list 'complex real))
               (input (make-array 257 :element-type type :initial-element z))
               (output (copy-seq input))
               (expected (/ z (* (abs z) (sqrt (coerce 257 real)))))
               (backend (find-symbol "*BACKEND*" :trivial-simd)))
          (when (and (eq *diagnostic-backend* :native)
                     (not (symbol-value (find-symbol "*NATIVE-COMPLEX-KERNELS-P*" :trivial-simd))))
            (error "Native complex kernels are unavailable"))
          (progv (list backend) (list *diagnostic-backend*)
            (dotimes (round 3)
              (funcall 'diagnostic-concurrent output input input)))
          (every (lambda (value)
                   (<= (abs (- value expected))
                       (* (if (eq real 'single-float) 1f-5 1d-12) (max 1 (abs expected)))))
                 output)))))

(format t "~&CCL ~A architecture=~A backend=~A workers=~D~%"
        (lisp-implementation-version) (machine-type) *diagnostic-backend* *diagnostic-workers*)
(finish-output)
(dolist (real '(single-float double-float))
  (let ((results (make-array 4 :initial-element nil)) (threads nil))
    (format t "~&START ~A~%" real)
    (finish-output)
    (dotimes (i 4)
      (let* ((slot i)
             (work (lambda ()
                     (setf (aref results slot)
                           (handler-case (diagnostic-work slot real)
                             (error (condition) condition))))))
        (if (= *diagnostic-workers* 1)
            (funcall work)
            (push (ccl:process-run-function "complex isolation" work) threads))))
    (mapc #'ccl:join-process threads)
    (unless (every (lambda (value) (eq value t)) results)
      (format *error-output* "~&Isolation failed: ~S~%" results)
      (uiop:quit 1))
    (format t "~&PASS ~A~%" real)
    (finish-output)))
(uiop:quit)
