(require :asdf)
(asdf:load-system :trivial-simd)

(let ((out (make-array 6 :element-type 'single-float))
      (rows (make-array 2 :element-type 'single-float :initial-contents '(1f0 2f0)))
      (columns (make-array 3 :element-type 'single-float :initial-contents '(10f0 20f0 30f0))))
  (trivial-simd:nd-add! out rows columns '(2 3)
                       :left-strides '(1 0) :right-strides '(0 1)
                       :destination-strides '(1 2))
  (assert (equalp out #(11f0 12f0 21f0 22f0 31f0 32f0)))
  (trivial-simd:nd-negate! out out '(2 3)
                          :destination-strides '(1 2)
                          :input-start 5 :input-strides '(-1 -2))
  (assert (equalp out #(-32f0 -31f0 -22f0 -21f0 -12f0 -11f0)))
  (format t "~&Broadcasting and aliased reversed N-D views passed.~%"))
