(require :asdf)
(asdf:load-system :trivial-simd)

(let ((out (make-array 6 :element-type 'single-float))
      (rows (make-array 2 :element-type 'single-float :initial-contents '(1f0 2f0)))
      (columns (make-array 3 :element-type 'single-float :initial-contents '(10f0 20f0 30f0))))
  (trivial-simd:nd-add! out rows columns '(2 3)
                       :left-strides '(1 0) :right-strides '(0 1)
                       :destination-strides '(1 2))
  (assert (equalp out #(11f0 12f0 21f0 22f0 31f0 32f0)))
  (trivial-simd:nd-negate! out out '(2 3)
                          :destination-strides '(1 2)
                          :input-start 5 :input-strides '(-1 -2))
  (assert (equalp out #(-32f0 -31f0 -22f0 -21f0 -12f0 -11f0)))
  (format t "~&Broadcasting and aliased reversed N-D views passed.~%"))

(let ((input (make-array 3 :element-type 'double-float :initial-contents '(-1d0 0d0 1d0)))
      (out (make-array 3 :element-type 'double-float)))
  (trivial-simd:nd-exp! out input '(3))
  (assert (= 1d0 (aref out 1)))
  (trivial-simd:nd-sin! out input '(3))
  (assert (= 0d0 (aref out 1)))
  (trivial-simd:nd-cos! out input '(3))
  (assert (= 1d0 (aref out 1)))
  (trivial-simd:nd-silu! out input '(3))
  (assert (< (abs (- (aref out 2) 0.7310585786300049d0)) 1d-14))
  (trivial-simd:nd-gelu! out input '(3))
  (assert (< (abs (- (aref out 2) 0.8411919906082768d0)) 1d-14))
  (format t "~&N-D exponential, trigonometric and activation examples passed.~%"))
