(in-package #:trivial-simd/blas)

(defun extended-gcd (a b)
  "Return GCD(A, B) and the coefficient of A in Bezout's identity."
  (let ((x 1) (next-x 0))
    (loop until (zerop b)
          for quotient = (floor a b)
          do (psetf a b b (- a (* quotient b))
                    x next-x next-x (- x (* quotient next-x))))
    (values a x)))

(defun bounded-affine-solution-p (steps lower upper target)
  "Solve SUM(STEP[i] * X[i]) = TARGET within inclusive integer bounds."
  (let* ((capacity (length steps))
         (coefficients (make-array capacity))
         (limits (make-array capacity))
         (count 0) (span 0))
    (loop for step across steps for low across lower for high across upper
          do (when (> low high) (return-from bounded-affine-solution-p nil))
             (decf target (* step (if (minusp step) high low)))
             (unless (or (zerop step) (= low high))
               (let* ((coefficient (abs step)) (limit (- high low))
                      (index (or (position coefficient coefficients :end count) count)))
                 (if (= index count)
                     (setf (aref coefficients count) coefficient
                           (aref limits count) limit count (1+ count))
                     (incf (aref limits index) limit))
                 (incf span (* coefficient limit)))))
    (labels ((solve-two (target)
               (let* ((a (aref coefficients 0)) (b (aref coefficients 1))
                      (low (max 0 (ceiling (- target (* b (aref limits 1))) a)))
                      (high (min (aref limits 0) (floor target a))))
                 (multiple-value-bind (g inverse) (extended-gcd a b)
                   (and (<= low high) (zerop (mod target g))
                        (<= (+ low (mod (- (* (floor target g) inverse) low)
                                        (floor b g)))
                            high)))))
             (solve (count target span)
               (when (or (minusp target) (> target span)) (return-from solve nil))
               (setf target (min target (- span target)))
               (when (zerop target) (return-from solve t))
               (case count
                 (0 nil)
                 (1 (zerop (mod target (aref coefficients 0))))
                 (2 (solve-two target))
                 (otherwise
                  ;; TODO: candidate enumeration grows with bounds; add lattice pruning (#154).
                  (let ((best-index 0) (best-start 0) (best-period 1) (best-count nil))
                    (dotimes (index count)
                      (let* ((coefficient (aref coefficients index))
                             (rest-span (- span (* coefficient (aref limits index))))
                             (low (max 0 (ceiling (- target rest-span) coefficient)))
                             (high (min (aref limits index) (floor target coefficient)))
                             (rest-gcd (loop with divisor = 0 for other below count
                                             unless (= other index)
                                               do (setf divisor (gcd divisor (aref coefficients other)))
                                             finally (return divisor))))
                        (multiple-value-bind (g inverse) (extended-gcd coefficient rest-gcd)
                          (unless (zerop (mod target g)) (return-from solve nil))
                          (let* ((period (floor rest-gcd g))
                                 (start (+ low (mod (- (* (floor target g) inverse) low) period)))
                                 (candidates (if (> start high) 0 (1+ (floor (- high start) period)))))
                            (when (zerop candidates) (return-from solve nil))
                            (when (or (null best-count) (< candidates best-count))
                              (setf best-index index best-start start best-period period
                                    best-count candidates))))))
                    (rotatef (aref coefficients best-index) (aref coefficients (1- count)))
                    (rotatef (aref limits best-index) (aref limits (1- count)))
                    (let* ((coefficient (aref coefficients (1- count)))
                           (rest-span (- span (* coefficient (aref limits (1- count)))))
                           (answer (loop repeat best-count
                                         for value from best-start by best-period
                                         thereis (solve (1- count) (- target (* coefficient value)) rest-span))))
                      (rotatef (aref coefficients best-index) (aref coefficients (1- count)))
                      (rotatef (aref limits best-index) (aref limits (1- count)))
                      answer))))))
      (solve count target span))))

(defun gemm-layout-unique-p (dimensions steps)
  (when (find 0 dimensions) (return-from gemm-layout-unique-p t))
  (let ((axes (sort (loop for dimension across dimensions for step across steps
                          when (> dimension 1) collect (cons (abs step) dimension))
                    #'< :key #'car))
        (extent 0))
    (when (loop for (step . dimension) in axes
                always (> step extent)
                do (incf extent (* step (1- dimension))))
      (return-from gemm-layout-unique-p t)))
  (let* ((rank (length dimensions))
         (lower (map 'vector (lambda (dimension) (- 1 dimension)) dimensions))
         (upper (map 'vector #'1- dimensions)))
    ;; The first nonzero difference is positive after reflecting a collision.
    (dotimes (axis rank t)
      (setf (aref lower axis) 1)
      (when (bounded-affine-solution-p steps lower upper 0)
        (return nil))
      (setf (aref lower axis) 0 (aref upper axis) 0))))

(defun matrix-elements-overlap-p (a acount astride b bcount bstride)
  (unless (matrix-spans-overlap-p a acount astride b bcount bstride)
    (return-from matrix-elements-overlap-p nil))
  (multiple-value-bind (am ao) (storage-origin (matrix-view-data a))
    (declare (ignore am))
    (multiple-value-bind (bm bo) (storage-origin (matrix-view-data b))
      (declare (ignore bm))
      (let* ((size (trivial-simd::vector-element-size
                    (trivial-simd::vector-type (matrix-view-data a))))
             (shift (+ (- bo ao) (* size (- (matrix-view-offset b) (matrix-view-offset a)))))
             (steps (vector (matrix-view-row-stride a) (matrix-view-column-stride a) astride
                            (- (matrix-view-row-stride b)) (- (matrix-view-column-stride b)) (- bstride)))
             (lower #(0 0 0 0 0 0))
             (upper (vector (1- (matrix-view-rows a)) (1- (matrix-view-cols a)) (1- acount)
                            (1- (matrix-view-rows b)) (1- (matrix-view-cols b)) (1- bcount))))
        (loop for target from (ceiling (- shift (1- size)) size)
              to (floor (+ shift (1- size)) size)
              thereis (bounded-affine-solution-p steps lower upper target))))))
