(in-package #:trivial-simd/blas)

;; TODO: Scalar loops limit Level 2 throughput; benchmark native kernels (#76).

(defun level2-zero (type)
  (if (consp type)
      (complex (coerce 0 (second type)) (coerce 0 (second type)))
      (coerce 0 type)))

(defun validate-level2-view (view type kind &optional square)
  (unless (and (matrix-view-p view) (eq (matrix-view-kind view) kind)
               (equal (matrix-element-type (matrix-view-data view)) type)
               (or (not square) (= (matrix-view-rows view)
                                   (matrix-view-cols view))))
    (error "Invalid Level 2 matrix view")))

(defun validate-level2-scalar (value type)
  (unless (typep value type)
    (error 'type-error :datum value :expected-type type)))

(defun validate-uplo (uplo)
  (unless (member uplo '(:upper :lower)) (error "Invalid triangle: ~S" uplo)))

(defun validate-transpose (transpose)
  (unless (member transpose '(:no-transpose :transpose :conjugate-transpose))
    (error "Invalid transpose flag: ~S" transpose)))

(defun validate-diag (diag)
  (unless (member diag '(:unit :non-unit)) (error "Invalid diagonal flag: ~S" diag)))

(defun vector-position (n increment offset i)
  (+ (span-index n increment offset) (* i increment)))

(defun matrix-value (view row column type &optional uplo hermitian)
  (let ((value
          (if (or (null uplo)
                  (if (eq uplo :upper) (<= row column) (>= row column)))
              (stored-ref view row column uplo (level2-zero type))
              (let ((reflected (stored-ref view column row uplo
                                          (level2-zero type))))
                (if hermitian (conjugate reflected) reflected)))))
    (if (and hermitian (= row column))
        (complex (realpart value) (coerce 0 (second type))) value)))

(defun operated-value (view row column transpose type &optional uplo hermitian)
  (if (eq transpose :no-transpose)
      (matrix-value view row column type uplo hermitian)
      (let ((value (matrix-value view column row type uplo hermitian)))
        (if (eq transpose :conjugate-transpose) (conjugate value) value))))

(defun level2-mv (kind transpose uplo hermitian alpha view x incx beta y incy
                  x-offset y-offset type)
  (validate-level2-view view type kind uplo)
  (when transpose (validate-transpose transpose))
  (when uplo (validate-uplo uplo))
  (validate-level2-scalar alpha type)
  (validate-level2-scalar beta type)
  (let* ((rows (matrix-view-rows view)) (cols (matrix-view-cols view))
         (m (if (member transpose '(:transpose :conjugate-transpose)) cols rows))
         (n (if (member transpose '(:transpose :conjugate-transpose)) rows cols))
         (operation (or transpose :no-transpose)))
    (validate-span n x incx x-offset type)
    (validate-span m y incy y-offset type)
    (dotimes (i m y)
      (let ((sum (level2-zero type)) (iy (vector-position m incy y-offset i)))
        (unless (zerop alpha)
          (dotimes (j n)
            (incf sum (* (operated-value view i j operation type uplo hermitian)
                         (aref x (vector-position n incx x-offset j))))))
        (unless (and (zerop alpha) (= beta 1))
          (setf (aref y iy)
                (+ (if (zerop alpha) (level2-zero type) (* alpha sum))
                   (if (zerop beta) (level2-zero type)
                       (* beta (aref y iy))))))))))

(defmacro define-level2-mv (name type kind &key transpose uplo hermitian)
  `(defun ,name (,@(when transpose '(transpose)) ,@(when uplo '(uplo))
                 alpha view x incx beta y incy &key (x-offset 0) (y-offset 0))
     (level2-mv ,kind ,(if transpose 'transpose nil) ,(if uplo 'uplo nil)
                ,hermitian alpha view x incx beta y incy x-offset y-offset ',type)))

(define-level2-mv sgemv single-float :dense :transpose t)
(define-level2-mv dgemv double-float :dense :transpose t)
(define-level2-mv cgemv (complex single-float) :dense :transpose t)
(define-level2-mv zgemv (complex double-float) :dense :transpose t)
(define-level2-mv sgbmv single-float :general :transpose t)
(define-level2-mv dgbmv double-float :general :transpose t)
(define-level2-mv cgbmv (complex single-float) :general :transpose t)
(define-level2-mv zgbmv (complex double-float) :general :transpose t)
(define-level2-mv ssymv single-float :dense :uplo t)
(define-level2-mv dsymv double-float :dense :uplo t)
(define-level2-mv ssbmv single-float :symmetric :uplo t)
(define-level2-mv dsbmv double-float :symmetric :uplo t)
(define-level2-mv sspmv single-float :packed :uplo t)
(define-level2-mv dspmv double-float :packed :uplo t)
(define-level2-mv chemv (complex single-float) :dense :uplo t :hermitian t)
(define-level2-mv zhemv (complex double-float) :dense :uplo t :hermitian t)
(define-level2-mv chbmv (complex single-float) :hermitian :uplo t :hermitian t)
(define-level2-mv zhbmv (complex double-float) :hermitian :uplo t :hermitian t)
(define-level2-mv chpmv (complex single-float) :packed :uplo t :hermitian t)
(define-level2-mv zhpmv (complex double-float) :packed :uplo t :hermitian t)

(defun triangular-value (view row column uplo transpose diag type)
  (if (and (= row column) (eq diag :unit))
      (if (consp type)
          (complex (coerce 1 (second type)) (coerce 0 (second type)))
          (coerce 1 type))
      (let ((r (if (eq transpose :no-transpose) row column))
            (c (if (eq transpose :no-transpose) column row)))
        (if (if (eq uplo :upper) (<= r c) (>= r c))
            (let ((value (stored-ref view r c uplo (level2-zero type))))
              (if (eq transpose :conjugate-transpose) (conjugate value) value))
            (level2-zero type)))))

(defun level2-triangular (operation kind uplo transpose diag view x incx x-offset type)
  (validate-level2-view view type kind t)
  (validate-uplo uplo)
  (validate-transpose transpose)
  (validate-diag diag)
  (let ((n (matrix-view-rows view)))
    (validate-span n x incx x-offset type)
    (let ((values (make-array n :element-type type)))
      (dotimes (i n)
        (setf (aref values i) (aref x (vector-position n incx x-offset i))))
      (if (eq operation :multiply)
          (dotimes (i n)
            (let ((sum (level2-zero type)))
              (dotimes (j n)
                (incf sum (* (triangular-value view i j uplo transpose diag type)
                             (aref values j))))
              (setf (aref x (vector-position n incx x-offset i)) sum)))
          (let ((forward (if (eq transpose :no-transpose)
                             (eq uplo :lower) (eq uplo :upper))))
            (dotimes (step n)
              (let* ((i (if forward step (- n step 1)))
                     (sum (aref values i)))
                (dotimes (j n)
                  (when (if forward (< j i) (> j i))
                    (decf sum (* (triangular-value view i j uplo transpose diag type)
                                 (aref values j)))))
                (setf (aref values i)
                      (if (eq diag :unit) sum
                          (/ sum (triangular-value view i i uplo transpose diag type))))))
            (dotimes (i n)
              (setf (aref x (vector-position n incx x-offset i))
                    (aref values i))))))
    x))

(defmacro define-level2-triangular (name operation kind type)
  `(defun ,name (uplo transpose diag view x incx &key (x-offset 0))
     (level2-triangular ,operation ,kind uplo transpose diag view x incx
                        x-offset ',type)))

(define-level2-triangular strmv :multiply :dense single-float)
(define-level2-triangular dtrmv :multiply :dense double-float)
(define-level2-triangular ctrmv :multiply :dense (complex single-float))
(define-level2-triangular ztrmv :multiply :dense (complex double-float))
(define-level2-triangular stbmv :multiply :triangular single-float)
(define-level2-triangular dtbmv :multiply :triangular double-float)
(define-level2-triangular ctbmv :multiply :triangular (complex single-float))
(define-level2-triangular ztbmv :multiply :triangular (complex double-float))
(define-level2-triangular stpmv :multiply :packed single-float)
(define-level2-triangular dtpmv :multiply :packed double-float)
(define-level2-triangular ctpmv :multiply :packed (complex single-float))
(define-level2-triangular ztpmv :multiply :packed (complex double-float))
(define-level2-triangular strsv :solve :dense single-float)
(define-level2-triangular dtrsv :solve :dense double-float)
(define-level2-triangular ctrsv :solve :dense (complex single-float))
(define-level2-triangular ztrsv :solve :dense (complex double-float))
(define-level2-triangular stbsv :solve :triangular single-float)
(define-level2-triangular dtbsv :solve :triangular double-float)
(define-level2-triangular ctbsv :solve :triangular (complex single-float))
(define-level2-triangular ztbsv :solve :triangular (complex double-float))
(define-level2-triangular stpsv :solve :packed single-float)
(define-level2-triangular dtpsv :solve :packed double-float)
(define-level2-triangular ctpsv :solve :packed (complex single-float))
(define-level2-triangular ztpsv :solve :packed (complex double-float))

(defun level2-rank-one (conjugate-y alpha x incx y incy view x-offset y-offset type)
  (validate-level2-view view type :dense)
  (validate-level2-scalar alpha type)
  (let ((m (matrix-view-rows view)) (n (matrix-view-cols view)))
    (validate-span m x incx x-offset type)
    (validate-span n y incy y-offset type)
    (unless (zerop alpha)
      (dotimes (i m)
        (dotimes (j n)
          (incf (matrix-ref view i j)
                (* alpha (aref x (vector-position m incx x-offset i))
                   (let ((value (aref y (vector-position n incy y-offset j))))
                     (if conjugate-y (conjugate value) value)))))))
    view))

(defmacro define-level2-ger (name conjugate-y type)
  `(defun ,name (alpha x incx y incy view &key (x-offset 0) (y-offset 0))
     (level2-rank-one ,conjugate-y alpha x incx y incy view
                      x-offset y-offset ',type)))

(define-level2-ger sger nil single-float)
(define-level2-ger dger nil double-float)
(define-level2-ger cgeru nil (complex single-float))
(define-level2-ger zgeru nil (complex double-float))
(define-level2-ger cgerc t (complex single-float))
(define-level2-ger zgerc t (complex double-float))

(defun level2-rank-symmetric (operation kind uplo alpha x incx y incy view
                              x-offset y-offset type)
  (validate-level2-view view type kind t)
  (validate-uplo uplo)
  (validate-level2-scalar alpha
                          (if (member operation '(:her :hpr)) (second type) type))
  (let ((n (matrix-view-rows view))
        (hermitian (member operation '(:her :hpr :her2 :hpr2)))
        (second-vector (member operation '(:syr2 :spr2 :her2 :hpr2))))
    (validate-span n x incx x-offset type)
    (when second-vector (validate-span n y incy y-offset type))
    (when (zerop alpha) (return-from level2-rank-symmetric view))
    (dotimes (i n view)
      (loop for j from (if (eq uplo :upper) i 0)
            below (if (eq uplo :upper) n (1+ i)) do
        (let* ((xi (aref x (vector-position n incx x-offset i)))
               (xj (aref x (vector-position n incx x-offset j)))
               (yi (when second-vector
                     (aref y (vector-position n incy y-offset i))))
               (yj (when second-vector
                     (aref y (vector-position n incy y-offset j))))
               (delta (if second-vector
                          (+ (* alpha xi (if hermitian (conjugate yj) yj))
                             (* (if hermitian (conjugate alpha) alpha) yi
                                (if hermitian (conjugate xj) xj)))
                          (* alpha xi (if hermitian (conjugate xj) xj))))
               (value (+ (stored-ref view i j uplo (level2-zero type)) delta)))
          (setf (stored-ref view i j uplo (level2-zero type))
                (if (and hermitian (= i j))
                    (complex (realpart value) (coerce 0 (second type))) value)))))))

(defmacro define-level2-rank-symmetric (name operation kind type &optional second-vector)
  `(defun ,name (uplo alpha x incx ,@(when second-vector '(y incy)) view
                 &key (x-offset 0) ,@(when second-vector '((y-offset 0))))
     (level2-rank-symmetric ,operation ,kind uplo alpha x incx
                            ,(if second-vector 'y nil) ,(if second-vector 'incy 1)
                            view x-offset ,(if second-vector 'y-offset 0) ',type)))

(define-level2-rank-symmetric ssyr :syr :dense single-float)
(define-level2-rank-symmetric dsyr :syr :dense double-float)
(define-level2-rank-symmetric sspr :spr :packed single-float)
(define-level2-rank-symmetric dspr :spr :packed double-float)
(define-level2-rank-symmetric ssyr2 :syr2 :dense single-float t)
(define-level2-rank-symmetric dsyr2 :syr2 :dense double-float t)
(define-level2-rank-symmetric sspr2 :spr2 :packed single-float t)
(define-level2-rank-symmetric dspr2 :spr2 :packed double-float t)
(define-level2-rank-symmetric cher :her :dense (complex single-float))
(define-level2-rank-symmetric zher :her :dense (complex double-float))
(define-level2-rank-symmetric chpr :hpr :packed (complex single-float))
(define-level2-rank-symmetric zhpr :hpr :packed (complex double-float))
(define-level2-rank-symmetric cher2 :her2 :dense (complex single-float) t)
(define-level2-rank-symmetric zher2 :her2 :dense (complex double-float) t)
(define-level2-rank-symmetric chpr2 :hpr2 :packed (complex single-float) t)
(define-level2-rank-symmetric zhpr2 :hpr2 :packed (complex double-float) t)
