(in-package #:trivial-simd/blas)

;; TODO: Checked scalar matrix access limits throughput; use typed/blocked kernels (#77).

(defun validate-level3-view (view type &optional square)
  (unless (and (matrix-view-p view) (eq (matrix-view-kind view) :dense)
               (equal (matrix-element-type (matrix-view-data view)) type)
               (or (not square) (= (matrix-view-rows view) (matrix-view-cols view))))
    (error "Invalid Level 3 matrix view")))

(defun matrix-intervals-overlap-p (a b)
  (when (and (eq (matrix-view-data a) (matrix-view-data b))
             (plusp (matrix-view-rows a)) (plusp (matrix-view-cols a))
             (plusp (matrix-view-rows b)) (plusp (matrix-view-cols b)))
    (let* ((ar (eq (matrix-view-layout a) :row-major))
           (br (eq (matrix-view-layout b) :row-major))
           (ac (if ar (matrix-view-rows a) (matrix-view-cols a)))
           (bc (if br (matrix-view-rows b) (matrix-view-cols b)))
           (aw (if ar (matrix-view-cols a) (matrix-view-rows a)))
           (bw (if br (matrix-view-cols b) (matrix-view-rows b)))
           (ai 0) (bi 0))
      (loop while (and (< ai ac) (< bi bc)) do
        (let ((as (+ (matrix-view-offset a) (* ai (matrix-view-leading-dimension a))))
              (bs (+ (matrix-view-offset b) (* bi (matrix-view-leading-dimension b)))))
          (when (and (< as (+ bs bw)) (< bs (+ as aw)))
            (return-from matrix-intervals-overlap-p t))
          (if (<= (+ as aw) (+ bs bw)) (incf ai) (incf bi)))))))

(defun validate-level3-overlap (output &rest inputs)
  (dolist (input inputs)
    (when (matrix-intervals-overlap-p output input)
      (error "Level 3 input and output matrix views overlap"))))

(defun operated-shape (view transpose)
  (if (eq transpose :no-transpose)
      (values (matrix-view-rows view) (matrix-view-cols view))
      (values (matrix-view-cols view) (matrix-view-rows view))))

(defun level3-result (sum alpha beta c i j type)
  (+ (if (zerop alpha) (level2-zero type) (* alpha sum))
     (if (zerop beta) (level2-zero type) (* beta (matrix-ref c i j)))))

(defun level3-gemm (transa transb alpha a b beta c type)
  (validate-transpose transa)
  (validate-transpose transb)
  (dolist (view (list a b c)) (validate-level3-view view type))
  (validate-level2-scalar alpha type)
  (validate-level2-scalar beta type)
  (multiple-value-bind (m k) (operated-shape a transa)
    (multiple-value-bind (bk n) (operated-shape b transb)
      (unless (and (= k bk) (= m (matrix-view-rows c))
                   (= n (matrix-view-cols c)))
        (error "Incompatible GEMM matrix dimensions"))
      (validate-level3-overlap c a b)
      (dotimes (i m c)
        (dotimes (j n)
          (let ((sum (level2-zero type)))
            (unless (zerop alpha)
              (dotimes (p k)
                (incf sum (* (operated-value a i p transa type)
                             (operated-value b p j transb type)))))
            (setf (matrix-ref c i j)
                  (level3-result sum alpha beta c i j type))))))))

(defun validate-side (side)
  (unless (member side '(:left :right))
    (error "Invalid matrix side: ~S" side)))

(defun level3-symm (hermitian side uplo alpha a b beta c type)
  (validate-side side)
  (validate-uplo uplo)
  (validate-level3-view a type t)
  (validate-level3-view b type)
  (validate-level3-view c type)
  (validate-level2-scalar alpha type)
  (validate-level2-scalar beta type)
  (let ((m (matrix-view-rows c)) (n (matrix-view-cols c)))
    (unless (and (= m (matrix-view-rows b)) (= n (matrix-view-cols b))
                 (= (matrix-view-rows a) (if (eq side :left) m n)))
      (error "Incompatible symmetric matrix dimensions"))
    (validate-level3-overlap c a b)
    (dotimes (i m c)
      (dotimes (j n)
        (let ((sum (level2-zero type)))
          (unless (zerop alpha)
            (dotimes (p (matrix-view-rows a))
              (incf sum (if (eq side :left)
                            (* (matrix-value a i p type uplo hermitian)
                               (matrix-ref b p j))
                            (* (matrix-ref b i p)
                               (matrix-value a p j type uplo hermitian))))))
          (setf (matrix-ref c i j)
                (level3-result sum alpha beta c i j type)))))))

(defun validate-rank-transpose (transpose hermitian type)
  (validate-transpose transpose)
  (when (and hermitian (eq transpose :transpose))
    (error "Hermitian rank updates require no transpose or conjugate transpose"))
  (when (and (not hermitian) (consp type)
             (eq transpose :conjugate-transpose))
    (error "Complex symmetric rank updates require no transpose or transpose")))

(defun level3-rank (hermitian second-input uplo transpose alpha a b beta c type)
  (validate-uplo uplo)
  (validate-rank-transpose transpose hermitian type)
  (validate-level3-view a type)
  (when second-input (validate-level3-view b type))
  (validate-level3-view c type t)
  (validate-level2-scalar alpha (if (and hermitian (not second-input))
                                    (second type) type))
  (validate-level2-scalar beta (if hermitian (second type) type))
  (multiple-value-bind (n k) (operated-shape a transpose)
    (unless (and (= n (matrix-view-rows c))
                 (or (not second-input)
                     (multiple-value-bind (bn bk) (operated-shape b transpose)
                       (and (= n bn) (= k bk)))))
      (error "Incompatible rank-update matrix dimensions"))
    (if second-input
        (validate-level3-overlap c a b)
        (validate-level3-overlap c a))
    (dotimes (i n c)
      (loop for j from (if (eq uplo :upper) i 0)
            below (if (eq uplo :upper) n (1+ i)) do
        (let ((sum (level2-zero type)))
          (unless (zerop alpha)
            (dotimes (p k)
              (let* ((ai (operated-value a i p transpose type))
                     (aj (operated-value a j p transpose type))
                     (bj (when second-input
                           (operated-value b j p transpose type)))
                     (bi (when second-input
                           (operated-value b i p transpose type))))
                (incf sum
                      (if second-input
                          (+ (* alpha ai (if hermitian (conjugate bj) bj))
                             (* (if hermitian (conjugate alpha) alpha) bi
                                (if hermitian (conjugate aj) aj)))
                          (* alpha ai (if hermitian (conjugate aj) aj)))))))
          (let ((value (+ sum (if (zerop beta) (level2-zero type)
                                  (* beta (matrix-ref c i j))))))
            (setf (matrix-ref c i j)
                  (if (and hermitian (= i j))
                      (complex (realpart value) (coerce 0 (second type)))
                      value))))))))

(defun level3-triangular (solve side uplo transpose diag alpha a b type)
  (validate-side side)
  (validate-uplo uplo)
  (validate-transpose transpose)
  (validate-diag diag)
  (validate-level3-view a type t)
  (validate-level3-view b type)
  (validate-level2-scalar alpha type)
  (let* ((m (matrix-view-rows b)) (n (matrix-view-cols b))
         (order (if (eq side :left) m n)))
    (unless (= (matrix-view-rows a) order)
      (error "Incompatible triangular matrix dimensions"))
    (validate-level3-overlap b a)
    (let ((result (make-array (list m n) :element-type type
                             :initial-element (level2-zero type))))
      (unless (zerop alpha)
        (if solve
            (let* ((upper (if (eq transpose :no-transpose)
                              (eq uplo :upper) (eq uplo :lower)))
                   (forward (if (eq side :left) (not upper) upper)))
              (dotimes (outer (if (eq side :left) n m))
                (dotimes (step order)
                  (let* ((index (if forward step (- order step 1)))
                         (value (* alpha (if (eq side :left)
                                             (matrix-ref b index outer)
                                             (matrix-ref b outer index)))))
                    (dotimes (prior step)
                      (let ((other (if forward prior (- order prior 1))))
                        (decf value
                              (if (eq side :left)
                                  (* (triangular-value a index other uplo transpose
                                                       diag type)
                                     (aref result other outer))
                                  (* (aref result outer other)
                                     (triangular-value a other index uplo transpose
                                                       diag type))))))
                    (let ((solved (if (eq diag :unit) value
                                      (/ value (triangular-value a index index uplo
                                                                 transpose diag type)))))
                      (if (eq side :left)
                          (setf (aref result index outer) solved)
                          (setf (aref result outer index) solved)))))))
            (dotimes (i m)
              (dotimes (j n)
                (let ((sum (level2-zero type)))
                  (dotimes (p order)
                    (incf sum
                          (if (eq side :left)
                              (* (triangular-value a i p uplo transpose diag type)
                                 (matrix-ref b p j))
                              (* (matrix-ref b i p)
                                 (triangular-value a p j uplo transpose diag type)))))
                  (setf (aref result i j) (* alpha sum)))))))
      (dotimes (i m b)
        (dotimes (j n)
          (setf (matrix-ref b i j) (aref result i j)))))))

(defmacro define-level3-gemm (name type)
  `(defun ,name (transa transb alpha a b beta c)
     (level3-gemm transa transb alpha a b beta c ',type)))

(defmacro define-level3-symm (name hermitian type)
  `(defun ,name (side uplo alpha a b beta c)
     (level3-symm ,hermitian side uplo alpha a b beta c ',type)))

(defmacro define-level3-rank (name hermitian second-input type)
  `(defun ,name (uplo transpose alpha a ,@(when second-input '(b)) beta c)
     (level3-rank ,hermitian ,second-input uplo transpose alpha a
                  ,(when second-input 'b) beta c ',type)))

(defmacro define-level3-triangular (name solve type)
  `(defun ,name (side uplo transpose diag alpha a b)
     (level3-triangular ,solve side uplo transpose diag alpha a b ',type)))

(define-level3-gemm sgemm single-float)
(define-level3-gemm dgemm double-float)
(define-level3-gemm cgemm (complex single-float))
(define-level3-gemm zgemm (complex double-float))
(define-level3-symm ssymm nil single-float)
(define-level3-symm dsymm nil double-float)
(define-level3-symm csymm nil (complex single-float))
(define-level3-symm zsymm nil (complex double-float))
(define-level3-symm chemm t (complex single-float))
(define-level3-symm zhemm t (complex double-float))
(define-level3-rank ssyrk nil nil single-float)
(define-level3-rank dsyrk nil nil double-float)
(define-level3-rank csyrk nil nil (complex single-float))
(define-level3-rank zsyrk nil nil (complex double-float))
(define-level3-rank cherk t nil (complex single-float))
(define-level3-rank zherk t nil (complex double-float))
(define-level3-rank ssyr2k nil t single-float)
(define-level3-rank dsyr2k nil t double-float)
(define-level3-rank csyr2k nil t (complex single-float))
(define-level3-rank zsyr2k nil t (complex double-float))
(define-level3-rank cher2k t t (complex single-float))
(define-level3-rank zher2k t t (complex double-float))
(define-level3-triangular strmm nil single-float)
(define-level3-triangular dtrmm nil double-float)
(define-level3-triangular ctrmm nil (complex single-float))
(define-level3-triangular ztrmm nil (complex double-float))
(define-level3-triangular strsm t single-float)
(define-level3-triangular dtrsm t double-float)
(define-level3-triangular ctrsm t (complex single-float))
(define-level3-triangular ztrsm t (complex double-float))
