(in-package #:trivial-simd/blas)

(defun validate-level3-view (view type &optional square)
  (unless (and (matrix-view-p view) (eq (matrix-view-kind view) :dense)
               (equal (matrix-element-type (matrix-view-data view)) type)
               (or (not square) (= (matrix-view-rows view) (matrix-view-cols view))))
    (error "Invalid Level 3 matrix view"))
  (validate-kernel-limits view))

(defun matrix-intervals-overlap-p (a b)
  (when (and (eq (matrix-view-data a) (matrix-view-data b))
             (plusp (matrix-view-rows a)) (plusp (matrix-view-cols a))
             (plusp (matrix-view-rows b)) (plusp (matrix-view-cols b)))
    (let* ((ar (eq (matrix-view-layout a) :row-major))
           (br (eq (matrix-view-layout b) :row-major))
           (ac (if ar (matrix-view-rows a) (matrix-view-cols a)))
           (bc (if br (matrix-view-rows b) (matrix-view-cols b)))
           (aw (if ar (matrix-view-cols a) (matrix-view-rows a)))
           (bw (if br (matrix-view-cols b) (matrix-view-rows b)))
           (ai 0) (bi 0))
      (loop while (and (< ai ac) (< bi bc)) do
        (let ((as (+ (matrix-view-offset a) (* ai (matrix-view-leading-dimension a))))
              (bs (+ (matrix-view-offset b) (* bi (matrix-view-leading-dimension b)))))
          (when (and (< as (+ bs bw)) (< bs (+ as aw)))
            (return-from matrix-intervals-overlap-p t))
          (if (<= (+ as aw) (+ bs bw)) (incf ai) (incf bi)))))))

(defun validate-level3-overlap (output &rest inputs)
  (dolist (input inputs)
    (when (matrix-intervals-overlap-p output input)
      (error "Level 3 input and output matrix views overlap"))))

(defun operated-shape (view transpose)
  (if (eq transpose :no-transpose)
      (values (matrix-view-rows view) (matrix-view-cols view))
      (values (matrix-view-cols view) (matrix-view-rows view))))

(defmacro define-level3-kernels (type)
  ;; TODO: Complex types use scalar loops without cache blocking or SIMD; native kernels (#80).
  (let ((array `(simple-array ,type (*))) (zero `(coerce 0 ',type)))
    `(progn
       (define-kernel gemm-kernel ,type
           (alpha a abase ars acs conj-a b bbase brs bcs conj-b beta
            c cbase crs ccs m n k)
         (declare (optimize (speed 3) (safety 0) (debug 0))
                  (type ,type alpha beta) (type ,array a b c)
                  (type blas-offset abase bbase cbase)
                  (type blas-dim ars acs brs bcs crs ccs)
                  (type blas-dim m n k))
         (scale-matrix ,type c cbase crs ccs m n beta)
         (unless (zerop alpha)
           (if (>= crs ccs)
               (dotimes (i m)
                 (let ((arow (+ abase (* i ars))) (crow (+ cbase (* i crs))))
                   (declare (type fixnum arow crow))
                   (dotimes (p k)
                     (let ((scaled (* alpha (conj-if ,type conj-a
                                                     (aref a (+ arow (* p acs))))))
                           (bpos (+ bbase (* p brs))) (cpos crow))
                       (declare (type ,type scaled) (type fixnum bpos cpos))
                       (dotimes (j n)
                         (incf (aref c cpos)
                               (* scaled (conj-if ,type conj-b (aref b bpos))))
                         (incf bpos bcs)
                         (incf cpos ccs))))))
               (dotimes (j n)
                 (let ((bcol (+ bbase (* j bcs))) (ccol (+ cbase (* j ccs))))
                   (declare (type fixnum bcol ccol))
                   (dotimes (p k)
                     (let ((scaled (* alpha (conj-if ,type conj-b
                                                     (aref b (+ bcol (* p brs))))))
                           (apos (+ abase (* p acs))) (cpos ccol))
                       (declare (type ,type scaled) (type fixnum apos cpos))
                       (dotimes (i m)
                         (incf (aref c cpos)
                               (* scaled (conj-if ,type conj-a (aref a apos))))
                         (incf apos ars)
                         (incf cpos crs))))))))
         nil)

       (define-kernel expand-kernel ,type
           (a abase ars acs n upper hermitian full)
         (declare (optimize (speed 3) (safety 0) (debug 0))
                  (type ,array a full) (type blas-offset abase) (type blas-dim ars acs)
                  (type blas-dim n))
         (dotimes (i n)
           (dotimes (j n)
             (setf (aref full (+ (* i n) j))
                   (if (if upper (<= i j) (>= i j))
                       (let ((value (aref a (+ abase (* i ars) (* j acs)))))
                         (if (and hermitian (= i j)) (realify ,type value) value))
                       (conj-if ,type hermitian
                                (aref a (+ abase (* j ars) (* i acs))))))))
         nil)

       (define-kernel rank-kernel ,type
           (alpha alpha2 a abase ars acs conj-a b bbase brs bcs conj-b beta
            c cbase crs ccs n k upper hermitian second)
         (declare (optimize (speed 3) (safety 0) (debug 0))
                  (type ,type alpha alpha2 beta) (type ,array a b c)
                  (type blas-offset abase bbase cbase)
                  (type blas-dim ars acs brs bcs crs ccs)
                  (type blas-dim n k))
         (let ((conj-aj (not (eq (and hermitian t) (and conj-a t))))
               (conj-bj (not (eq (and hermitian t) (and conj-b t))))
               (skip (zerop alpha)))
           (dotimes (i n)
             (loop for j of-type blas-dim from (if upper i 0)
                   below (if upper n (1+ i)) do
               (let ((first-sum ,zero) (second-sum ,zero))
                 (declare (type ,type first-sum second-sum))
                 (unless skip
                   (let ((ai (+ abase (* i ars))) (aj (+ abase (* j ars)))
                         (bi (+ bbase (* i brs))) (bj (+ bbase (* j brs))))
                     (declare (type fixnum ai aj bi bj))
                     (dotimes (p k)
                       (incf first-sum
                             (* (conj-if ,type conj-a (aref a ai))
                                (conj-if ,type conj-bj (aref b bj))))
                       (when second
                         (incf second-sum
                               (* (conj-if ,type conj-b (aref b bi))
                                  (conj-if ,type conj-aj (aref a aj)))))
                       (incf ai acs) (incf aj acs) (incf bi bcs) (incf bj bcs))))
                 (let* ((position (+ cbase (* i crs) (* j ccs)))
                        (value (+ (* alpha first-sum)
                                  (if second (* alpha2 second-sum) ,zero)
                                  (if (zerop beta) ,zero
                                      (* beta (aref c position))))))
                   (declare (type fixnum position))
                   (setf (aref c position)
                         (if (and hermitian (= i j)) (realify ,type value) value))))))
           nil))

       (define-kernel triangular-kernel ,type
           (solve left upper unit alpha a abase ars acs conj b bbase brs bcs m n)
         (declare (optimize (speed 3) (safety 0) (debug 0))
                  (type ,type alpha) (type ,array a b)
                  (type blas-offset abase bbase) (type blas-dim ars acs brs bcs)
                  (type blas-dim m n))
         (let* ((rows (if left m n)) (cols (if left n m))
                (rs (if left brs bcs)) (cs (if left bcs brs))
                (tars (if left ars acs)) (tacs (if left acs ars))
                (upper (if left upper (not upper)))
                (w (make-array (* rows cols) :element-type ',type
                                             :initial-element ,zero)))
           (declare (type blas-dim rows cols rs cs tars tacs)
                    (type ,array w))
           (unless (zerop alpha)
             (dotimes (r rows)
               (let ((bpos (+ bbase (* r rs))))
                 (declare (type fixnum bpos))
                 (dotimes (c cols)
                   (setf (aref w (+ (* r cols) c)) (* alpha (aref b bpos)))
                   (incf bpos cs))))
             (flet ((coefficient (i k)
                      (declare (type blas-dim i k))
                      (conj-if ,type conj (aref a (+ abase (* i tars) (* k tacs))))))
               (declare (inline coefficient))
               (flet ((row-combine (i k scale)
                        (declare (type blas-dim i k) (type ,type scale))
                        (let ((irow (* i cols)) (krow (* k cols)))
                          (declare (type fixnum irow krow))
                          (dotimes (c cols)
                            (incf (aref w (+ irow c)) (* scale (aref w (+ krow c)))))))
                      (row-subtract (i k scale)
                        (declare (type blas-dim i k) (type ,type scale))
                        (let ((irow (* i cols)) (krow (* k cols)))
                          (declare (type fixnum irow krow))
                          (dotimes (c cols)
                            (decf (aref w (+ irow c)) (* scale (aref w (+ krow c)))))))
                      (row-scale (i scale)
                        (declare (type blas-dim i) (type ,type scale))
                        (let ((irow (* i cols)))
                          (declare (type fixnum irow))
                          (dotimes (c cols)
                            (setf (aref w (+ irow c)) (* scale (aref w (+ irow c)))))))
                      (row-divide (i divisor)
                        (declare (type blas-dim i) (type ,type divisor))
                        (let ((irow (* i cols)))
                          (declare (type fixnum irow))
                          (dotimes (c cols)
                            (setf (aref w (+ irow c)) (/ (aref w (+ irow c)) divisor))))))
                 (declare (inline row-combine row-subtract row-scale row-divide))
                 (cond
                   ((and solve upper)
                    (loop for i of-type fixnum from (1- rows) downto 0 do
                      (loop for k of-type blas-dim from (1+ i) below rows do
                        (row-subtract i k (coefficient i k)))
                      (unless unit (row-divide i (coefficient i i)))))
                   (solve
                    (dotimes (i rows)
                      (dotimes (k i) (row-subtract i k (coefficient i k)))
                      (unless unit (row-divide i (coefficient i i)))))
                   (upper
                    (dotimes (i rows)
                      (unless unit (row-scale i (coefficient i i)))
                      (loop for k of-type blas-dim from (1+ i) below rows do
                        (row-combine i k (coefficient i k)))))
                   (t
                    (loop for i of-type fixnum from (1- rows) downto 0 do
                      (unless unit (row-scale i (coefficient i i)))
                      (dotimes (k i) (row-combine i k (coefficient i k)))))))))
           (dotimes (r rows)
             (let ((bpos (+ bbase (* r rs))))
               (declare (type fixnum bpos))
               (dotimes (c cols)
                 (setf (aref b bpos) (aref w (+ (* r cols) c)))
                 (incf bpos cs)))))
         nil))))

(define-level3-kernels single-float)
(define-level3-kernels double-float)
(define-level3-kernels (complex single-float))
(define-level3-kernels (complex double-float))

(defun call-gemm (type alpha a abase ars acs conj-a b bbase brs bcs conj-b beta
                 c cbase crs ccs m n k)
  (if (native-blas-p type (* m n k))
      (call-native-blas type (trivial-simd::%native-blas-gemm-f32
                              trivial-simd::%native-blas-gemm-f64)
          ((ap a abase) (bp b bbase) (cp c cbase))
        m n k alpha ap ars acs bp brs bcs beta cp crs ccs)
      (funcall (find-kernel 'gemm-kernel type)
               alpha a abase ars acs conj-a b bbase brs bcs conj-b beta
               c cbase crs ccs m n k))
  nil)

(defun call-rank (type hermitian alpha a abase ars acs conj-a b bbase brs bcs conj-b
                  beta c cbase crs ccs n k upper second)
  (if (native-blas-p type (* n n k))
      (call-native-blas type (trivial-simd::%native-blas-rank-f32
                              trivial-simd::%native-blas-rank-f64)
          ((ap a abase) (bp b bbase) (cp c cbase))
        n k alpha ap ars acs bp brs bcs beta cp crs ccs (if upper 1 0) (if second 1 0))
      (funcall (find-kernel 'rank-kernel type)
               alpha (if hermitian (conjugate alpha) alpha)
               a abase ars acs conj-a b bbase brs bcs conj-b beta
               c cbase crs ccs n k upper hermitian second))
  nil)

(defun call-triangular (type solve left upper unit alpha a abase ars acs conj
                        b bbase brs bcs m n)
  (if (native-blas-p type (* m n (if left m n)))
      (call-native-blas type (trivial-simd::%native-blas-triangular-f32
                              trivial-simd::%native-blas-triangular-f64)
          ((ap a abase) (bp b bbase))
        (if solve 1 0) (if left 1 0) (if upper 1 0) (if unit 1 0) alpha
        ap ars acs bp brs bcs m n)
      (funcall (find-kernel 'triangular-kernel type)
               solve left upper unit alpha a abase ars acs conj b bbase brs bcs m n))
  nil)

(defun level3-gemm (transa transb alpha a b beta c type)
  (validate-transpose transa)
  (validate-transpose transb)
  (dolist (view (list a b c)) (validate-level3-view view type))
  (validate-level2-scalar alpha type)
  (validate-level2-scalar beta type)
  (multiple-value-bind (m k) (operated-shape a transa)
    (multiple-value-bind (bk n) (operated-shape b transb)
      (unless (and (= k bk) (= m (matrix-view-rows c))
                   (= n (matrix-view-cols c)))
        (error "Incompatible GEMM matrix dimensions"))
      (validate-level3-overlap c a b)
      (multiple-value-bind (adata abase ars acs) (dense-strides a transa)
        (multiple-value-bind (bdata bbase brs bcs) (dense-strides b transb)
          (multiple-value-bind (cdata cbase crs ccs) (dense-strides c :no-transpose)
            (call-gemm type alpha adata abase ars acs (eq transa :conjugate-transpose)
                       bdata bbase brs bcs (eq transb :conjugate-transpose)
                       beta cdata cbase crs ccs m n k))))
      c)))

(defun validate-side (side)
  (unless (member side '(:left :right))
    (error "Invalid matrix side: ~S" side)))

(defun level3-symm (hermitian side uplo alpha a b beta c type)
  (validate-side side)
  (validate-uplo uplo)
  (validate-level3-view a type t)
  (validate-level3-view b type)
  (validate-level3-view c type)
  (validate-level2-scalar alpha type)
  (validate-level2-scalar beta type)
  (let ((m (matrix-view-rows c)) (n (matrix-view-cols c))
        (order (matrix-view-rows a)))
    (unless (and (= m (matrix-view-rows b)) (= n (matrix-view-cols b))
                 (= order (if (eq side :left) m n)))
      (error "Incompatible symmetric matrix dimensions"))
    (validate-level3-overlap c a b)
    (let ((full (make-array (* order order) :element-type type)))
      (multiple-value-bind (adata abase ars acs) (dense-strides a :no-transpose)
        (funcall (find-kernel 'expand-kernel type)
                 adata abase ars acs order (eq uplo :upper) hermitian full))
      (multiple-value-bind (bdata bbase brs bcs) (dense-strides b :no-transpose)
        (multiple-value-bind (cdata cbase crs ccs) (dense-strides c :no-transpose)
          (if (eq side :left)
              (call-gemm type alpha full 0 order 1 nil bdata bbase brs bcs nil
                         beta cdata cbase crs ccs m n order)
              (call-gemm type alpha bdata bbase brs bcs nil full 0 order 1 nil
                         beta cdata cbase crs ccs m n order)))))
    c))

(defun validate-rank-transpose (transpose hermitian type)
  (validate-transpose transpose)
  (when (and hermitian (eq transpose :transpose))
    (error "Hermitian rank updates require no transpose or conjugate transpose"))
  (when (and (not hermitian) (consp type)
             (eq transpose :conjugate-transpose))
    (error "Complex symmetric rank updates require no transpose or transpose")))

(defun level3-rank (hermitian second-input uplo transpose alpha a b beta c type)
  (validate-uplo uplo)
  (validate-rank-transpose transpose hermitian type)
  (validate-level3-view a type)
  (when second-input (validate-level3-view b type))
  (validate-level3-view c type t)
  (validate-level2-scalar alpha (if (and hermitian (not second-input))
                                    (second type) type))
  (validate-level2-scalar beta (if hermitian (second type) type))
  (multiple-value-bind (n k) (operated-shape a transpose)
    (unless (and (= n (matrix-view-rows c))
                 (or (not second-input)
                     (multiple-value-bind (bn bk) (operated-shape b transpose)
                       (and (= n bn) (= k bk)))))
      (error "Incompatible rank-update matrix dimensions"))
    (if second-input
        (validate-level3-overlap c a b)
        (validate-level3-overlap c a))
    (let ((alpha (coerce alpha type)) (beta (coerce beta type))
          (conjugate (eq transpose :conjugate-transpose)))
      (multiple-value-bind (adata abase ars acs) (dense-strides a transpose)
        (multiple-value-bind (bdata bbase brs bcs)
            (dense-strides (if second-input b a) transpose)
          (multiple-value-bind (cdata cbase crs ccs) (dense-strides c :no-transpose)
            (call-rank type hermitian alpha adata abase ars acs conjugate
                       bdata bbase brs bcs conjugate beta cdata cbase crs ccs
                       n k (eq uplo :upper) second-input)))))
    c))

(defun level3-triangular (solve side uplo transpose diag alpha a b type)
  (validate-side side)
  (validate-uplo uplo)
  (validate-transpose transpose)
  (validate-diag diag)
  (validate-level3-view a type t)
  (validate-level3-view b type)
  (validate-level2-scalar alpha type)
  (let* ((m (matrix-view-rows b)) (n (matrix-view-cols b))
         (order (if (eq side :left) m n)))
    (unless (= (matrix-view-rows a) order)
      (error "Incompatible triangular matrix dimensions"))
    (validate-level3-overlap b a)
    (multiple-value-bind (adata abase ars acs) (dense-strides a transpose)
      (multiple-value-bind (bdata bbase brs bcs) (dense-strides b :no-transpose)
        (call-triangular type solve (eq side :left)
                         (if (eq transpose :no-transpose) (eq uplo :upper) (eq uplo :lower))
                         (eq diag :unit) alpha adata abase ars acs
                         (eq transpose :conjugate-transpose) bdata bbase brs bcs m n)))
    b))

(defmacro define-level3-gemm (name type)
  `(defun ,name (transa transb alpha a b beta c)
     (level3-gemm transa transb alpha a b beta c ',type)))

(defmacro define-level3-symm (name hermitian type)
  `(defun ,name (side uplo alpha a b beta c)
     (level3-symm ,hermitian side uplo alpha a b beta c ',type)))

(defmacro define-level3-rank (name hermitian second-input type)
  `(defun ,name (uplo transpose alpha a ,@(when second-input '(b)) beta c)
     (level3-rank ,hermitian ,second-input uplo transpose alpha a
                  ,(when second-input 'b) beta c ',type)))

(defmacro define-level3-triangular (name solve type)
  `(defun ,name (side uplo transpose diag alpha a b)
     (level3-triangular ,solve side uplo transpose diag alpha a b ',type)))

(define-level3-gemm sgemm single-float)
(define-level3-gemm dgemm double-float)
(define-level3-gemm cgemm (complex single-float))
(define-level3-gemm zgemm (complex double-float))
(define-level3-symm ssymm nil single-float)
(define-level3-symm dsymm nil double-float)
(define-level3-symm csymm nil (complex single-float))
(define-level3-symm zsymm nil (complex double-float))
(define-level3-symm chemm t (complex single-float))
(define-level3-symm zhemm t (complex double-float))
(define-level3-rank ssyrk nil nil single-float)
(define-level3-rank dsyrk nil nil double-float)
(define-level3-rank csyrk nil nil (complex single-float))
(define-level3-rank zsyrk nil nil (complex double-float))
(define-level3-rank cherk t nil (complex single-float))
(define-level3-rank zherk t nil (complex double-float))
(define-level3-rank ssyr2k nil t single-float)
(define-level3-rank dsyr2k nil t double-float)
(define-level3-rank csyr2k nil t (complex single-float))
(define-level3-rank zsyr2k nil t (complex double-float))
(define-level3-rank cher2k t t (complex single-float))
(define-level3-rank zher2k t t (complex double-float))
(define-level3-triangular strmm nil single-float)
(define-level3-triangular dtrmm nil double-float)
(define-level3-triangular ctrmm nil (complex single-float))
(define-level3-triangular ztrmm nil (complex double-float))
(define-level3-triangular strsm t single-float)
(define-level3-triangular dtrsm t double-float)
(define-level3-triangular ctrsm t (complex single-float))
(define-level3-triangular ztrsm t (complex double-float))
