(in-package #:trivial-simd/blas)

(defun blas-pair (operation n x incx y incy x-offset y-offset type &optional alpha)
  (validate-span n x incx x-offset type)
  (validate-span n y incy y-offset type)
  (when (eq operation :axpy)
    (unless (typep alpha type)
      (error 'type-error :datum alpha :expected-type type)))
  (let ((x-start (span-start n incx x-offset))
        (y-start (span-start n incy y-offset)))
    (ecase operation
      (:copy (trivial-simd:copy! y x :start 0 :end n
                                     :source-start x-start :source-stride incx
                                     :destination-start y-start :destination-stride incy))
      (:swap (trivial-simd:swap! x y :start 0 :end n
                                     :x-start x-start :x-stride incx
                                     :y-start y-start :y-stride incy))
      (:axpy (unless (zerop alpha)
               (trivial-simd:axpy! y alpha x :start 0 :end n
                                             :x-start x-start :x-stride incx
                                             :y-start y-start :y-stride incy))
       y)
      ((:dot :dotc)
       (funcall (if (eq operation :dot) #'trivial-simd:dot #'trivial-simd:dotc)
                x y :start 0 :end n
                    :left-start x-start :left-stride incx
                    :right-start y-start :right-stride incy)))))

(defmacro define-pair (name operation type &optional alpha-p)
  `(defun ,name (n ,@(when alpha-p '(alpha)) x incx y incy
                 &key (x-offset 0) (y-offset 0))
     (blas-pair ,operation n x incx y incy x-offset y-offset ',type
                ,(if alpha-p 'alpha nil))))

(define-pair sswap :swap single-float)
(define-pair dswap :swap double-float)
(define-pair cswap :swap (complex single-float))
(define-pair zswap :swap (complex double-float))
(define-pair scopy :copy single-float)
(define-pair dcopy :copy double-float)
(define-pair ccopy :copy (complex single-float))
(define-pair zcopy :copy (complex double-float))
(define-pair caxpy :axpy (complex single-float) t)
(define-pair zaxpy :axpy (complex double-float) t)
(define-pair sdot :dot single-float)
(define-pair ddot :dot double-float)
(define-pair cdotu :dot (complex single-float))
(define-pair zdotu :dot (complex double-float))
(define-pair cdotc :dotc (complex single-float))
(define-pair zdotc :dotc (complex double-float))

(defun blas-scale (n alpha x incx x-offset type alpha-type)
  (validate-span n x incx x-offset type)
  (unless (typep alpha alpha-type)
    (error "Scale factor has the wrong type"))
  (if (equal type alpha-type)
      (let ((start (span-start n incx x-offset)))
        (trivial-simd:scale! x alpha :start start :end (+ start n) :stride incx))
      (let ((ix (span-index n incx x-offset)))
        (dotimes (i n x)
          (setf (aref x ix) (* alpha (aref x ix)))
          (incf ix incx)))))

(defmacro define-scale (name type &optional real-alpha)
  `(defun ,name (n alpha x incx &key (x-offset 0))
     (blas-scale n alpha x incx x-offset ',type ',(or real-alpha type))))

(define-scale sscal single-float)
(define-scale dscal double-float)
(define-scale cscal (complex single-float))
(define-scale zscal (complex double-float))
(define-scale csscal (complex single-float) single-float)
(define-scale zdscal (complex double-float) double-float)

(defun absolute-one (value)
  (if (complexp value)
      (+ (abs (realpart value)) (abs (imagpart value)))
      (abs value)))

(defun blas-reduce (operation n x incx x-offset type)
  (validate-span n x incx x-offset type)
  (let ((start (span-start n incx x-offset)))
    (if (and (plusp n)
             (or (member type '(single-float double-float))
                 (eq operation :nrm2)))
        (let ((end (+ start n)))
          (ecase operation
            (:asum (trivial-simd:asum x :start start :end end :stride incx))
            (:nrm2 (trivial-simd:nrm2 x :start start :end end :stride incx))
            (:iamax (/ (- (trivial-simd::absolute-argmax x n start incx) start) incx))))
        (blas-reduce-strided operation n x incx x-offset type))))

(defun blas-reduce-strided (operation n x incx x-offset type)
  (let* ((real-type (if (consp type) (second type) type))
         (sum (coerce 0 real-type))
         (scale (coerce 0 real-type))
         (ssq (coerce 1 real-type))
         (best-index 0)
         (best (coerce 0 real-type))
         (ix (span-index n incx x-offset)))
    (dotimes (i n)
      (let* ((value (aref x ix))
             (magnitude (absolute-one value)))
        (case operation
          (:asum (incf sum magnitude))
          (:iamax (when (or (zerop i) (> magnitude best))
                    (setf best magnitude best-index i)))
          (:nrm2
           (dolist (part (if (complexp value)
                             (list (realpart value) (imagpart value))
                             (list value)))
             (let ((a (abs part)))
               (unless (zerop a)
                 (if (< scale a)
                     (setf ssq (+ 1 (* ssq (expt (/ scale a) 2)))
                           scale a)
                     (incf ssq (expt (/ a scale) 2)))))))))
      (incf ix incx))
    (ecase operation
      (:asum sum) (:iamax best-index) (:nrm2 (* scale (sqrt ssq))))))

(defmacro define-reduction (name operation type)
  `(defun ,name (n x incx &key (x-offset 0))
     (blas-reduce ,operation n x incx x-offset ',type)))

(define-reduction snrm2 :nrm2 single-float)
(define-reduction dnrm2 :nrm2 double-float)
(define-reduction scnrm2 :nrm2 (complex single-float))
(define-reduction dznrm2 :nrm2 (complex double-float))
(define-reduction sasum :asum single-float)
(define-reduction dasum :asum double-float)
(define-reduction scasum :asum (complex single-float))
(define-reduction dzasum :asum (complex double-float))
(define-reduction isamax :iamax single-float)
(define-reduction idamax :iamax double-float)
(define-reduction icamax :iamax (complex single-float))
(define-reduction izamax :iamax (complex double-float))

(defun dsdot (n x incx y incy &key (x-offset 0) (y-offset 0))
  (validate-span n x incx x-offset 'single-float)
  (validate-span n y incy y-offset 'single-float)
  (trivial-simd:dot x y :start 0 :end n
                        :left-start (span-start n incx x-offset) :left-stride incx
                        :right-start (span-start n incy y-offset) :right-stride incy
                        :accumulate :f64))

(defun sdsdot (n alpha x incx y incy &key (x-offset 0) (y-offset 0))
  (unless (typep alpha 'single-float)
    (error 'type-error :datum alpha :expected-type 'single-float))
  (float (+ (float alpha 0.0d0)
            (dsdot n x incx y incy :x-offset x-offset :y-offset y-offset))
         0.0f0))

(defun blas-rotg (a b type)
  (unless (and (typep a type) (typep b type))
    (error "ROTG inputs must have the same float precision"))
  (let ((zero (coerce 0 type)) (one (coerce 1 type)))
    (cond ((zerop b) (values a zero one zero))
          ((zerop a) (values b one zero one))
          (t (let* ((scale (max (abs a) (abs b)))
                    (r (coerce (* (if (> (abs a) (abs b)) (signum a) (signum b))
                                  scale
                                  (sqrt (+ (expt (/ a scale) 2)
                                           (expt (/ b scale) 2)))) type))
                    (c (/ a r))
                    (s (/ b r))
                    (z (if (> (abs a) (abs b)) s
                           (if (zerop c) one (/ c)))))
               (values r z c s))))))

(defun srotg (a b) (blas-rotg a b 'single-float))
(defun drotg (a b) (blas-rotg a b 'double-float))

(defun blas-complex-rotg (a b type)
  (unless (and (typep a type) (typep b type))
    (error "Complex ROTG inputs must have the same precision"))
  (let* ((real-type (second type))
         (zero (complex (coerce 0 real-type) (coerce 0 real-type)))
         (one (coerce 1 real-type)))
    (cond ((zerop b) (values a b one zero))
          ((zerop a)
           (let ((magnitude (abs b)))
             (values (complex magnitude (coerce 0 real-type)) b
                     (coerce 0 real-type) (/ (conjugate b) magnitude))))
          (t (let* ((a-magnitude (abs a))
                    (b-magnitude (abs b))
                    (scale (max a-magnitude b-magnitude))
                    (norm (* scale
                             (sqrt (+ (expt (/ a-magnitude scale) 2)
                                      (expt (/ b-magnitude scale) 2)))))
                    (phase (/ a a-magnitude)))
               (values (* phase norm) b (/ a-magnitude norm)
                       (/ (* phase (conjugate b)) norm)))))))

(defun crotg (a b) (blas-complex-rotg a b '(complex single-float)))
(defun zrotg (a b) (blas-complex-rotg a b '(complex double-float)))

(defun blas-rot (n x incx y incy c s x-offset y-offset type)
  (validate-span n x incx x-offset type)
  (validate-span n y incy y-offset type)
  (unless (and (typep c type) (typep s type))
    (error "Rotation coefficients have the wrong precision"))
  (let ((ix (span-index n incx x-offset)) (iy (span-index n incy y-offset)))
    (dotimes (i n (values x y))
      (let ((a (aref x ix)) (b (aref y iy)))
        (setf (aref x ix) (+ (* c a) (* s b))
              (aref y iy) (- (* c b) (* s a))))
      (incf ix incx)
      (incf iy incy))))

(defmacro define-rot (name type)
  `(defun ,name (n x incx y incy c s &key (x-offset 0) (y-offset 0))
     (blas-rot n x incx y incy c s x-offset y-offset ',type)))

(define-rot srot single-float)
(define-rot drot double-float)

(defun blas-complex-rot (n x incx y incy c s x-offset y-offset type sine-type)
  (validate-span n x incx x-offset type)
  (validate-span n y incy y-offset type)
  (unless (and (typep c (second type)) (typep s sine-type))
    (error "Complex rotation coefficients have the wrong precision"))
  (let ((ix (span-index n incx x-offset)) (iy (span-index n incy y-offset)))
    (dotimes (i n (values x y))
      (let ((a (aref x ix)) (b (aref y iy)))
        (setf (aref x ix) (+ (* c a) (* s b))
              (aref y iy) (- (* c b) (* (conjugate s) a))))
      (incf ix incx)
      (incf iy incy))))

(defmacro define-complex-rot (name type sine-type)
  `(defun ,name (n x incx y incy c s &key (x-offset 0) (y-offset 0))
     (blas-complex-rot n x incx y incy c s x-offset y-offset ',type ',sine-type)))

(define-complex-rot csrot (complex single-float) single-float)
(define-complex-rot zdrot (complex double-float) double-float)
(define-complex-rot crot (complex single-float) (complex single-float))
(define-complex-rot zrot (complex double-float) (complex double-float))

(defun blas-rotm (n x incx y incy parameters x-offset y-offset type)
  (validate-span n x incx x-offset type)
  (validate-span n y incy y-offset type)
  (unless (typep parameters `(simple-array ,type (5)))
    (error 'type-error :datum parameters :expected-type `(simple-array ,type (5))))
  (let ((flag (aref parameters 0))
        (ix (span-index n incx x-offset))
        (iy (span-index n incy y-offset)))
    (unless (member flag '(-2.0 -1.0 0.0 1.0) :test #'=)
      (error "Invalid ROTM flag"))
    (dotimes (i n (values x y))
      (unless (= flag -2)
        (let ((a (aref x ix)) (b (aref y iy)))
          (cond ((= flag -1)
                 (setf (aref x ix) (+ (* (aref parameters 1) a)
                                      (* (aref parameters 3) b))
                       (aref y iy) (+ (* (aref parameters 2) a)
                                      (* (aref parameters 4) b))))
                ((= flag 0)
                 (setf (aref x ix) (+ a (* (aref parameters 3) b))
                       (aref y iy) (+ (* (aref parameters 2) a) b)))
                (t (setf (aref x ix) (+ (* (aref parameters 1) a) b)
                         (aref y iy) (- (* (aref parameters 4) b) a))))))
      (incf ix incx)
      (incf iy incy))))

(defmacro define-rotm (name type)
  `(defun ,name (n x incx y incy parameters &key (x-offset 0) (y-offset 0))
     (blas-rotm n x incx y incy parameters x-offset y-offset ',type)))

(define-rotm srotm single-float)
(define-rotm drotm double-float)

(defun blas-rotmg (d1 d2 b1 b2 type)
  (unless (every (lambda (value) (typep value type)) (list d1 d2 b1 b2))
    (error "ROTMG inputs must have the same float precision"))
  (let* ((zero (coerce 0 type)) (one (coerce 1 type))
         (gam (coerce 4096 type)) (gamsq (coerce 16777216 type))
         (rgamsq (/ one gamsq))
         (flag (coerce -2 type))
         (h11 zero) (h12 zero) (h21 zero) (h22 zero))
    (labels ((clear ()
               (setf flag (- one) h11 zero h12 zero h21 zero h22 zero
                     d1 zero d2 zero b1 zero))
             (expand-flag ()
               (cond ((zerop flag) (setf h11 one h22 one))
                     ((= flag one) (setf h21 (- one) h12 one)))
               (setf flag (- one))))
      (cond ((minusp d1) (clear))
            (t (let* ((p2 (* d2 b2))
                      (p1 (* d1 b1))
                      (q1 (* p1 b1))
                      (q2 (* p2 b2)))
                 (unless (zerop p2)
                   (if (> (abs q1) (abs q2))
                       (let* ((new-h21 (- (/ b2 b1)))
                              (new-h12 (/ p2 p1))
                              (u (- one (* new-h12 new-h21))))
                         (if (plusp u)
                             (setf flag zero h21 new-h21 h12 new-h12
                                   d1 (/ d1 u) d2 (/ d2 u) b1 (* b1 u))
                             (clear)))
                       (if (minusp q2)
                           (clear)
                           (let* ((new-h11 (/ p1 p2))
                                  (new-h22 (/ b1 b2))
                                  (u (+ one (* new-h11 new-h22)))
                                  (old-d1 d1))
                             (setf flag one h11 new-h11 h22 new-h22
                                   d1 (/ d2 u) d2 (/ old-d1 u) b1 (* b2 u)))))
                   (when (not (= flag (- (coerce 2 type))))
                     (when (not (zerop d1))
                       (loop while (or (<= d1 rgamsq) (>= d1 gamsq)) do
                         (expand-flag)
                         (if (<= d1 rgamsq)
                             (setf d1 (* d1 gamsq) b1 (/ b1 gam)
                                   h11 (/ h11 gam) h12 (/ h12 gam))
                             (setf d1 (/ d1 gamsq) b1 (* b1 gam)
                                   h11 (* h11 gam) h12 (* h12 gam)))))
                     (when (not (zerop d2))
                       (loop while (or (<= (abs d2) rgamsq)
                                       (>= (abs d2) gamsq)) do
                         (expand-flag)
                         (if (<= (abs d2) rgamsq)
                             (setf d2 (* d2 gamsq)
                                   h21 (/ h21 gam) h22 (/ h22 gam))
                             (setf d2 (/ d2 gamsq)
                                   h21 (* h21 gam) h22 (* h22 gam))))))))))
      (let ((parameters (make-array 5 :element-type type :initial-element zero)))
        (setf (aref parameters 0) flag)
        (cond ((minusp flag)
               (unless (= flag (- (coerce 2 type)))
                 (setf (aref parameters 1) h11 (aref parameters 2) h21
                       (aref parameters 3) h12 (aref parameters 4) h22)))
              ((zerop flag)
               (setf (aref parameters 2) h21 (aref parameters 3) h12))
              (t (setf (aref parameters 1) h11 (aref parameters 4) h22)))
        (values d1 d2 b1 parameters)))))

(defun srotmg (d1 d2 b1 b2) (blas-rotmg d1 d2 b1 b2 'single-float))
(defun drotmg (d1 d2 b1 b2) (blas-rotmg d1 d2 b1 b2 'double-float))
