(in-package #:trivial-simd/blas)

(defstruct (matrix-view (:constructor %make-matrix-view))
  (data nil :read-only t)
  (rows 0 :read-only t)
  (cols 0 :read-only t)
  (layout :row-major :read-only t)
  (leading-dimension 1 :read-only t)
  (row-stride 1 :read-only t)
  (column-stride 1 :read-only t)
  (offset 0 :read-only t)
  (kind :dense :read-only t)
  (kl 0 :read-only t)
  (ku 0 :read-only t))

(defun matrix-element-type (data)
  (or (storage-element-type data)
      (error "Matrix backing storage must be a simple float or complex float vector, ~
              or a vector view of one")))

(defun validate-view-arguments (data rows cols layout offset)
  (matrix-element-type data)
  (unless (and (integerp rows) (<= 0 rows) (integerp cols) (<= 0 cols))
    (error "Matrix dimensions must be nonnegative integers"))
  (unless (member layout '(:row-major :column-major))
    (error "Invalid matrix layout: ~S" layout))
  (unless (and (integerp offset) (<= 0 offset) (<= offset (storage-length data)))
    (error "Matrix offset exceeds backing storage")))

(defun matrix-stride-layout (rows cols rs cs)
  (cond ((and (or (= cols 1) (= cs 1))
              (or (= rows 1) (<= (max 1 cols) rs)))
         (values :row-major (if (= rows 1) (max 1 cols) rs)))
        ((and (or (= rows 1) (= rs 1))
              (or (= cols 1) (<= (max 1 rows) cs)))
         (values :column-major (if (= cols 1) (max 1 rows) cs)))
        (t (values :strided 1))))

(defun matrix-bounds (view &optional (count 1) (stride 0))
  (let ((low (matrix-view-offset view)) (high (matrix-view-offset view)))
    (loop for dimension in (list (matrix-view-rows view) (matrix-view-cols view) count)
          for step in (list (matrix-view-row-stride view)
                            (matrix-view-column-stride view) stride)
          for delta = (* (max 0 (1- dimension)) step)
          do (incf low (min 0 delta)) (incf high (max 0 delta)))
    (values low high)))

(defun make-matrix-view (data rows cols &key (layout :row-major)
                                           (leading-dimension nil ld-p) (offset 0)
                                           (row-stride nil rs-p) (column-stride nil cs-p))
  (validate-view-arguments data rows cols layout offset)
  (unless (eq rs-p cs-p) (error "Specify both row and column strides"))
  (when (and rs-p ld-p) (error "Explicit strides exclude a leading dimension"))
  (let* ((minor (if (eq layout :row-major) cols rows))
         (ld (or leading-dimension (max 1 minor)))
         (rs (if rs-p row-stride (if (eq layout :row-major) ld 1)))
         (cs (if cs-p column-stride (if (eq layout :row-major) 1 ld))))
    (unless (and (integerp rs) (integerp cs)
                 (or rs-p (and (integerp ld) (<= (max 1 minor) ld))))
      (error "Invalid matrix strides or leading dimension"))
    (when rs-p
      (multiple-value-setq (layout ld) (matrix-stride-layout rows cols rs cs)))
    (let ((view (%make-matrix-view :data data :rows rows :cols cols :layout layout
                                   :leading-dimension ld :offset offset :kind :dense
                                   :row-stride rs :column-stride cs :kl 0 :ku 0)))
      (multiple-value-bind (low high) (matrix-bounds view)
        (unless (or (zerop rows) (zerop cols)
                    (and (<= 0 low) (< high (storage-length data))))
          (error "Matrix view exceeds backing storage")))
      view)))

(defun matrix-subview (view row column rows cols)
  (unless (and (matrix-view-p view) (eq (matrix-view-kind view) :dense)
               (integerp row) (integerp column) (integerp rows) (integerp cols)
               (<= 0 row) (<= 0 column) (<= 0 rows) (<= 0 cols)
               (<= (+ row rows) (matrix-view-rows view))
               (<= (+ column cols) (matrix-view-cols view)))
    (error "Invalid dense matrix subview"))
  (%make-matrix-view :data (matrix-view-data view) :rows rows :cols cols
                     :layout (matrix-view-layout view)
                     :leading-dimension (matrix-view-leading-dimension view)
                     :row-stride (matrix-view-row-stride view)
                     :column-stride (matrix-view-column-stride view)
                     :offset (max 0 (min (storage-length (matrix-view-data view))
                                        (+ (matrix-view-offset view)
                                           (matrix-index view row column))))))

(defun matrix-index (view row column)
  (+ (* row (matrix-view-row-stride view))
     (* column (matrix-view-column-stride view))))

(defun matrix-ref (view row column)
  (unless (and (matrix-view-p view) (eq (matrix-view-kind view) :dense)
               (integerp row) (integerp column)
               (<= 0 row) (< row (matrix-view-rows view))
               (<= 0 column) (< column (matrix-view-cols view)))
    (error "Invalid dense matrix index"))
  (trivial-simd::vector-ref (matrix-view-data view)
                            (+ (matrix-view-offset view) (matrix-index view row column))))

(defun (setf matrix-ref) (value view row column)
  (matrix-ref view row column)
  (setf (trivial-simd::vector-ref (matrix-view-data view)
                                  (+ (matrix-view-offset view) (matrix-index view row column)))
        value))

(defun make-band-matrix-view (data rows cols &key (kind :general) (kl 0) (ku 0)
                                                     bandwidth
                                                     (layout :row-major)
                                                     leading-dimension (offset 0))
  (validate-view-arguments data rows cols layout offset)
  (when bandwidth
    (unless (and (not (eq kind :general)) (integerp bandwidth)
                 (<= 0 bandwidth) (zerop kl) (zerop ku))
      (error "Invalid band bandwidth"))
    (setf kl bandwidth ku bandwidth))
  (unless (and (member kind '(:general :symmetric :hermitian :triangular))
               (integerp kl) (<= 0 kl) (integerp ku) (<= 0 ku)
               (or (eq kind :general) (= rows cols)))
    (error "Invalid band matrix kind or bandwidth"))
  (let* ((width (if (eq kind :general) (+ kl ku 1) (1+ (max kl ku))))
         (ld (or leading-dimension width))
         (major (if (eq layout :row-major) rows cols)))
    (unless (and (integerp ld) (<= width ld))
      (error "Invalid band leading dimension"))
    (unless (or (zerop rows) (zerop cols)
                (<= (+ offset (* (1- major) ld) width) (storage-length data)))
      (error "Band view exceeds backing storage"))
    (%make-matrix-view :data data :rows rows :cols cols :layout layout
                       :leading-dimension ld :offset offset :kind kind
                       :kl kl :ku ku)))

(defun make-packed-matrix-view (data n &key (layout :row-major) (offset 0))
  (validate-view-arguments data n n layout offset)
  (unless (<= (+ offset (floor (* n (1+ n)) 2)) (storage-length data))
    (error "Packed view exceeds backing storage"))
  (%make-matrix-view :data data :rows n :cols n :layout layout
                     :leading-dimension 0 :offset offset :kind :packed
                     :kl 0 :ku 0))

(defun stored-index (view row column uplo)
  (let* ((kind (matrix-view-kind view))
         (layout (matrix-view-layout view))
         (ld (matrix-view-leading-dimension view))
         (n (matrix-view-rows view)))
    (case kind
      (:dense (matrix-index view row column))
      (:general
       (when (<= (- row (matrix-view-kl view)) column
                 (+ row (matrix-view-ku view)))
         (if (eq layout :row-major)
             (+ (* row ld) (- column row) (matrix-view-kl view))
             (+ (* column ld) (- row column) (matrix-view-ku view)))))
      ((:symmetric :hermitian :triangular)
       (let ((k (max (matrix-view-kl view) (matrix-view-ku view))))
         (when (and (<= (abs (- row column)) k)
                    (if (eq uplo :upper) (<= row column) (>= row column)))
           (if (eq layout :row-major)
               (+ (* row ld) (if (eq uplo :upper) (- column row)
                                  (+ k (- column row))))
               (+ (* column ld) (if (eq uplo :upper) (+ k (- row column))
                                     (- row column)))))))
      (:packed
       (when (if (eq uplo :upper) (<= row column) (>= row column))
         (if (eq layout :row-major)
             (if (eq uplo :upper)
                 (+ (floor (* row (- (1+ (* 2 n)) row)) 2) (- column row))
                 (+ (floor (* row (1+ row)) 2) column))
             (if (eq uplo :upper)
                 (+ (floor (* column (1+ column)) 2) row)
                 (+ (floor (* column (- (1+ (* 2 n)) column)) 2)
                    (- row column)))))))))

(defun stored-ref (view row column uplo zero)
  (let ((index (stored-index view row column uplo)))
    (if index
        (trivial-simd::vector-ref (matrix-view-data view) (+ (matrix-view-offset view) index))
        zero)))

(defun (setf stored-ref) (value view row column uplo zero)
  (declare (ignore zero))
  (let ((index (stored-index view row column uplo)))
    (unless index (error "Matrix element is outside the stored triangle or band"))
    (setf (trivial-simd::vector-ref (matrix-view-data view) (+ (matrix-view-offset view) index))
          value)))
