name: ql-dist

on:
  push:
    tags: ['*']

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: takeiteasy/gh-ql-dist/notify@v1
        with:
          repo: takeiteasy/ql-dist
          project: ${{ github.event.repository.name }}
          token: ${{ secrets.QL_DIST_TOKEN }}
